#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
  Project Euler Problem 44: Pentagon Numbers.

  Problem Statement:
    Pentagonal numbers are generated by the formula, P_n = n (3n - 1) / 2. The first
    ten pentagonal numbers are:
    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

    It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their difference,
    70 - 22 = 48, is not pentagonal.

    Find the pair of pentagonal numbers, P_j and P_k, for which their sum and
difference are pentagonal and D = |P_k - P_j| is minimised; what is the value of D?

  Solution Approach:
    To solve this problem, begin by understanding the pentagonal number formula and
    how to efficiently test whether a number is pentagonal. The key challenge is to
    find pairs of pentagonal numbers whose sum and difference are also pentagonal.

    Generate pentagonal numbers iteratively and for each pair, check the pentagonality
    of their sum and difference. Use the formula to invert and check pentagonality
    rather than searching a set, which improves efficiency.

    Maintain the minimal difference found during the process and stop the search
    when no smaller difference can be found by examining larger pentagonal numbers.

    This approach involves careful nested loops or search combined with a pentagonal
    check function, balancing completeness with computational efficiency.

  Test Cases:
    main:
      answer=5482660.


  Answer: 5482660
  URL: https://projecteuler.net/problem=44
"""
from __future__ import annotations

from euler.logger import logger
from euler.maths.polynomial_numbers import is_pentagonal_number, nth_pentagonal_number
from euler.setup import TestCaseCategory, evaluate, register_solution


@register_solution(euler_problem=44, test_case_category=TestCaseCategory.EXTENDED)
def pentagon_numbers() -> int:
    i = 0
    while (i := (i + 1)):
        pi = nth_pentagonal_number(i)
        for j in range(i - 1, 0, -1):
            pj = nth_pentagonal_number(j)
            if is_pentagonal_number(pi - pj) and is_pentagonal_number(pi + pj):
                return pi - pj
    else:
        raise ValueError('No solution found')


if __name__ == '__main__':
    logger.setLevel('ERROR')
    raise SystemExit(evaluate(euler_problem=44, time_out_in_seconds=300, mode='evaluate'))
