#!/usr/bin/env python3.14
# -*- coding: utf-8 -*-
""" Available models and their pricing, plus a utility function to calculate costs. """
from __future__ import annotations

__all__ = ['Model', 'Price', 'TokenKind', 'costs', 'get_accumulated_charges', 'get_api_key', 'record_usage']

from enum import StrEnum
from functools import lru_cache
from typing import Any, Literal, NamedTuple

from solver.config import ExitCodes, config
from solver.shell import console, register


# GEN:models — regenerated by `update-models`; do not hand-edit (curated comments are preserved)
class Model(StrEnum):  # Available models (as of 7th July 2026; pricing from platform.claude.com)
    CLAUDE_FABLE_5 = 'claude-fable-5'  # most capable; demanding reasoning and long-horizon agentic work
    CLAUDE_OPUS_4_8 = 'claude-opus-4-8'  # most intelligent Opus; best for hard reasoning, agents, coding
    CLAUDE_OPUS_4_7 = 'claude-opus-4-7'  # Claude Opus 4.7
    CLAUDE_OPUS_4_6 = 'claude-opus-4-6'  # Claude Opus 4.6
    CLAUDE_OPUS_4_5 = 'claude-opus-4-5'  # Claude Opus 4.5
    CLAUDE_SONNET_4_6 = 'claude-sonnet-4-6'  # best speed/intelligence balance; good for structured generation
    CLAUDE_SONNET_4_5 = 'claude-sonnet-4-5'  # Claude Sonnet 4.5
    CLAUDE_SONNET_5 = 'claude-sonnet-5'  # Claude Sonnet 5
    CLAUDE_HAIKU_4_5 = 'claude-haiku-4-5'  # fastest and cheapest; simple/high-volume tasks only

    @property
    def price(self) -> Price:  # Cost in USD per million tokens, scraped from the pricing page
        return {
            Model.CLAUDE_FABLE_5: Price(input=10.00, output=50.00),
            Model.CLAUDE_OPUS_4_8: Price(input=5.00, output=25.00),
            Model.CLAUDE_OPUS_4_7: Price(input=5.00, output=25.00),
            Model.CLAUDE_OPUS_4_6: Price(input=5.00, output=25.00),
            Model.CLAUDE_OPUS_4_5: Price(input=5.00, output=25.00),
            Model.CLAUDE_SONNET_4_6: Price(input=3.00, output=15.00),
            Model.CLAUDE_SONNET_4_5: Price(input=3.00, output=15.00),
            Model.CLAUDE_SONNET_5: Price(input=2.00, output=10.00),
            Model.CLAUDE_HAIKU_4_5: Price(input=1.00, output=5.00),
        }[self]
# /GEN:models


class Price(NamedTuple):
    input: float
    output: float

    #: Cache writes (cache_creation_input_tokens) are billed at 1.25x the input rate;
    #: cache reads (cache_read_input_tokens) are billed at 0.10x the input rate.
    @property
    def cache_write(self) -> float:
        """The per-million cache-write rate (1.25x the input rate)."""
        return self.input * 1.25

    @property
    def cache_read(self) -> float:
        """The per-million cache-read rate (0.10x the input rate)."""
        return self.input * 0.10

    def cost(self, *,
             input_tokens: int,
             output_tokens: int,
             cache_creation_tokens: int = 0,
             cache_read_tokens: int = 0) -> float:
        """Return the USD cost of the given token counts at this model's rates."""
        return (self.input * input_tokens
                + self.cache_write * cache_creation_tokens
                + self.cache_read * cache_read_tokens
                + self.output * output_tokens) / 1_000_000


TokenKind = Literal['input', 'output', 'cache_creation', 'cache_read']

consumed_tokens: dict[Model, dict[TokenKind, int]] = {
    model: {'input': 0, 'output': 0, 'cache_creation': 0, 'cache_read': 0}
    for model in Model
}


def record_usage(model: Model, usage: Any) -> None:
    """Record token counts from an Anthropic 'response.usage' into 'consumed_tokens'.

    Tolerates older SDKs that may not expose cache-token attributes by treating missing
    or 'None' fields as zero.
    """
    bucket = consumed_tokens[model]
    bucket['input'] += int(getattr(usage, 'input_tokens', 0) or 0)
    bucket['output'] += int(getattr(usage, 'output_tokens', 0) or 0)
    bucket['cache_creation'] += int(getattr(usage, 'cache_creation_input_tokens', 0) or 0)
    bucket['cache_read'] += int(getattr(usage, 'cache_read_input_tokens', 0) or 0)


def get_accumulated_charges() -> float:
    """Return the total accumulated charges for all models in the session."""
    return sum(model.price.cost(input_tokens=consumed_tokens[model]['input'],
                                output_tokens=consumed_tokens[model]['output'],
                                cache_creation_tokens=consumed_tokens[model]['cache_creation'],
                                cache_read_tokens=consumed_tokens[model]['cache_read'])
               for model in consumed_tokens)


@register(requires=('solver:execute',), help_text='Display total cost of AI API tokens consumed in session.')
def costs(ecb_usd_rate: float = config.ecb_usd_rate) -> int:
    """
    Print the total cost of all AI tokens consumed in the session so far, broken down per model,
    or a "No charges so far." notice if nothing has been consumed. Always returns EXIT_OK.

    Totals the charges across all models in "consumed_tokens" using each model's published USD
    price per million tokens (with cache writes at 1.25x and cache reads at 0.10x the input rate),
    then converts to EUR using "ecb_usd_rate".

    Args:
        ecb_usd_rate: conversion rate (1 € = N $). Defaults to 'config.ecb_usd_rate'.
    """
    charges_usd: float = get_accumulated_charges()
    if charges_usd == 0.0:
        console.print('[muted]No charges so far.[/muted]')
        return ExitCodes.EXIT_OK
    charges_eur: float = charges_usd / ecb_usd_rate
    parts: list[str] = []
    for model, b in consumed_tokens.items():
        if any(b.values()):
            parts.append(f'{model}: input {b["input"]}, output {b["output"]}, '
                         f'cache_write {b["cache_creation"]}, cache_read {b["cache_read"]}')
    console.print(f'[muted]Charges so far: '
                  f'${charges_usd:.4f} (€{charges_eur:.4f} at {ecb_usd_rate:.2f} €/$)'
                  f'({'; '.join(parts)})'
                  '[/muted]')
    return ExitCodes.EXIT_OK


@lru_cache(maxsize=None)
def get_api_key() -> str:
    """Read 'ANTHROPIC_API_KEY' from the project env file (`config.env_file`).

    Delegates to 'python-dotenv' ('ai' extra), which handles the full dotenv grammar:
    'export' prefix, single/double-quoted values, inline '#' comments, escape sequences,
    multi-line quoted values, and variable interpolation. Imported on demand so this module
    (and the `costs` command it registers) loads without the 'ai' group installed.

    The env file is read either plain or -- once a per-user vault is initialised -- decrypted from
    its vault form under the session vault key (`solver.crypto.vault`) before parsing, so the
    Anthropic key rests encrypted at the same boundary as the private key.
    """
    from io import StringIO

    from dotenv import dotenv_values

    from solver.crypto.vault import decrypt_secret, is_vault_encrypted, session_vault_key

    env_file = config.env_file
    name = 'ANTHROPIC_API_KEY'
    if not env_file.exists():
        values: dict[str, str | None] = {}
    else:
        raw = env_file.read_bytes()
        if is_vault_encrypted(raw):
            vault_key = session_vault_key()
            if vault_key is None:
                raise ValueError(f'{env_file} is vault-encrypted but the vault is locked; unlock it first')
            values = dotenv_values(stream=StringIO(decrypt_secret(vault_key, raw).decode('utf-8')))
        else:
            values = dotenv_values(env_file)
    value = values.get(name)
    if not value:
        raise ValueError(f'{name} not found in {env_file}, please set it to your Anthropic API key')
    return value
