#!/usr/bin/env python3.14
# -*- coding: utf-8 -*-
"""Migrated from
    euler_solver/solutions/solutions_0001_0100/solution_0029/p0029.py :: solve_distinct_powers_p0029_s1_pps.

Project Euler Problem 29: Distinct Powers.

Problem Statement:
    Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

        2^2=4, 2^3=8, 2^4=16, 2^5=32
        3^2=9, 3^3=27, 3^4=81, 3^5=243
        4^2=16, 4^3=64, 4^4=256, 4^5=1024
        5^2=25, 5^3=125, 5^4=625, 5^5=3125

    If they are then placed in numerical order, with any repeats removed, we get the
    following sequence of 15 distinct terms:

        4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125.

    How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100
    and 2 ≤ b ≤ 100?

Solution Approach:
    Generation of all powers a^b for the given ranges is straightforward. Use a set
    to store and eliminate duplicates efficiently. The main challenge is to do this
    within reasonable time by avoiding recalculation and exploiting properties of
    powers if needed. Time complexity is O(N^2) with N=99 here, which is acceptable.

Answer: 9183
URL: https://projecteuler.net/problem=29"""
from __future__ import annotations

import pyprimesieve as pps


def solve(*, a_min: int, a_max: int, b_min: int, b_max: int) -> int:
    if min(a_max, b_max) > 100:
        unique_powers = set()
        for a in range(a_min, a_max + 1):
            prime_factors = pps.factorize(a)
            for b in range(b_min, b_max + 1):
                signature = tuple(((prime, power * b) for prime, power in prime_factors))
                unique_powers.add(signature)
        return len(unique_powers)
    else:
        return len({a ** b for a in range(a_min, a_max + 1) for b in range(a_min, a_max + 1)})


if __name__ == '__main__':
    import sys

    print(solve(a_min=int(sys.argv[1]), a_max=int(sys.argv[2]), b_min=int(sys.argv[3]), b_max=int(sys.argv[4])))
