#!/usr/bin/env python3.14
# -*- coding: utf-8 -*-
"""Build the presentation's data file from `solutions/problems.json`.

Writes `docs/presentation/data/history.js`, a plain script that sets `window.HISTORY`, so the
deck opens straight from disk (`file://`) without a fetch. Only public metadata is exported —
number, title, difficulty, upstream solver count, solved flag and date — never an answer, and
nothing from `solutions/private/`.

    python docs/presentation/build_data.py

`make release` runs it too and stages the result into the release commit
(scripts/version/release.sh), so a redeployed `/story/` shows the data as of that release.
"""
from __future__ import annotations

import re
import subprocess
from datetime import datetime
from json import dumps, loads
from pathlib import Path

from solver.core.progress import read_problems

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SOURCE = ROOT / 'solutions' / 'problems.json'
TARGET = HERE / 'data' / 'history.js'


def iso(date: object) -> str:
    """'Thu, 2 Jul 2015, 17:16' → '2015-07-02T17:16', or '' when absent or unreadable."""
    try:
        return datetime.strptime(str(date), '%a, %d %b %Y, %H:%M').strftime('%Y-%m-%dT%H:%M')
    except ValueError:
        return ''


def project_stats() -> dict[str, int]:
    """Counts for the "what changed" slide — file names and counts only, never file contents."""
    solutions = ROOT / 'solutions'
    commits = subprocess.run(['git', 'rev-list', '--count', 'HEAD'], cwd=ROOT,
                             capture_output=True, text=True, check=False).stdout.strip()
    articles = loads((ROOT / 'topics' / 'articles.json').read_text(encoding='utf-8'))['articles']
    commands = re.findall(r'^#### Command:', (ROOT / 'docs' / 'commands-index.md').read_text(encoding='utf-8'),
                          flags=re.MULTILINE)
    return {'python': sum(1 for _ in solutions.rglob('p*_s*.py')),
            'c': sum(1 for _ in solutions.rglob('p*_s*.c')),
            'notes': sum(1 for _ in solutions.rglob('notes.html')),
            'articles': len(articles),
            'articles_final': sum(1 for a in articles if a.get('status') == 'final'),
            'commands': len(commands),
            'commits': int(commits) if commits.isdigit() else 0}


def main() -> int:
    problems = read_problems(SOURCE)
    if not problems:
        print(f'{SOURCE} is missing or empty')
        return 1
    rows = [[number, record.get('title', ''), record.get('level', ''), record.get('pct', ''),
             record.get('solvers', ''), bool(record.get('solved')), iso(record.get('date', ''))]
            for number, record in sorted(problems.items())]
    payload = {'generated': datetime.now().strftime('%Y-%m-%d'),
               'fields': ['number', 'title', 'level', 'pct', 'solvers', 'solved', 'date'],
               'problems': rows,
               'project': project_stats()}
    TARGET.parent.mkdir(exist_ok=True)
    TARGET.write_text(f'// Generated by build_data.py from solutions/problems.json — do not edit.\n'
                      f'window.HISTORY = {dumps(payload, ensure_ascii=False, separators=(",", ":"))};\n',
                      encoding='utf-8')
    solved = sum(1 for row in rows if row[5])
    counted = sum(1 for row in rows if row[4] != '')
    print(f'{TARGET.relative_to(ROOT)}: {len(rows)} problems, {solved} solved, '
          f'{counted} with solver counts')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
