#!/usr/bin/env python3.14
# -*- coding: utf-8 -*-
"""Build the presentation's data file from `solutions/problems.json`.

Writes `docs/presentation/data/history.js`, a plain script that sets `window.HISTORY`, so the
deck opens straight from disk (`file://`) without a fetch. Only public metadata is exported —
number, title, difficulty, upstream solver count, solved flag and date — never an answer, and
nothing from `solutions/private/`.

    python docs/presentation/build_data.py
"""
from __future__ import annotations

from datetime import datetime
from json import dumps
from pathlib import Path

from solver.core.progress import read_problems

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SOURCE = ROOT / 'solutions' / 'problems.json'
TARGET = HERE / 'data' / 'history.js'


def iso(date: object) -> str:
    """'Thu, 2 Jul 2015, 17:16' → '2015-07-02T17:16', or '' when absent or unreadable."""
    try:
        return datetime.strptime(str(date), '%a, %d %b %Y, %H:%M').strftime('%Y-%m-%dT%H:%M')
    except ValueError:
        return ''


def main() -> int:
    problems = read_problems(SOURCE)
    if not problems:
        print(f'{SOURCE} is missing or empty')
        return 1
    rows = [[number, record.get('title', ''), record.get('level', ''), record.get('pct', ''),
             record.get('solvers', ''), bool(record.get('solved')), iso(record.get('date', ''))]
            for number, record in sorted(problems.items())]
    payload = {'generated': datetime.now().strftime('%Y-%m-%d'),
               'fields': ['number', 'title', 'level', 'pct', 'solvers', 'solved', 'date'],
               'problems': rows}
    TARGET.parent.mkdir(exist_ok=True)
    TARGET.write_text(f'// Generated by build_data.py from solutions/problems.json — do not edit.\n'
                      f'window.HISTORY = {dumps(payload, ensure_ascii=False, separators=(",", ":"))};\n',
                      encoding='utf-8')
    solved = sum(1 for row in rows if row[5])
    counted = sum(1 for row in rows if row[4] != '')
    print(f'{TARGET.relative_to(ROOT)}: {len(rows)} problems, {solved} solved, '
          f'{counted} with solver counts')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
