#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Solution to Project Euler problem 45: Triangular, pentagonal, and hexagonal

Problem Statement:
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle: Tn = n(n+1)/2
1, 3, 6, 10, 15, ...

Pentagonal: Pn = n(3n-1)/2
1, 5, 12, 22, 35, ...

Hexagonal: Hn = n(2n-1)
1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

Solution Approach:
This solution uses mathematical properties to efficiently identify numbers that are
simultaneously triangular, pentagonal, and hexagonal:

1. We start by generating triangular numbers in sequence, beginning after T285
2. For each triangular number, we check if it's pentagonal using the formula:
   - A number is pentagonal if (1 + sqrt(24n + 1))/6 is an integer
3. Similarly, we check if it's hexagonal using the formula:
   - A number is hexagonal if (1 + sqrt(8n + 1))/4 is an integer
4. The first number that satisfies all three conditions is our answer

Rather than generating all three sequences, we use these mathematical shortcuts
to efficiently test if a number belongs to each sequence.

Test Cases:
- T285 = P165 = H143 = 40755 (known example from the problem)
- The next such number is 1533776805

URL: https://projecteuler.net/problem=45
Answer: 1533776805
"""

from euler.types import ProblemArgs, ProblemArgsList, SolutionProtocol

problem_args_list: ProblemArgsList = [
    ProblemArgs(
        kwargs={'n': 285},  # Start the search from a triangular number T_285
        answer=1533776805,  # The expected result (the next triangular-pentagonal-hexagonal number)
    ),
]


def solution(n: int) -> int:
    """
    Find the next triangular number that is also pentagonal and hexagonal.

    This solution finds the next number after T_n that belongs to all three sequences:
    triangular, pentagonal, and hexagonal. It uses mathematical properties to efficiently
    test sequence membership rather than generating all three sequences.

    Args:
        n: The triangular index to start from (the function will find the next solution after T_n)
           The problem uses n=285 as the starting point

    Returns:
        The next triangular number that is also pentagonal and hexagonal

    Example:
        >>> solution(285)
        1533776805

    Note:
        The problem statement confirms that T_285 = P_165 = H_143 = 40755, and we need to find
        the next such number that appears in all three sequences.
    """
    while n := n + 1:
        triangular_number = n * (n + 1) // 2  # triangular number
        if ((1 + 24 * triangular_number) ** 0.5) % 6 == 5.0:  # is a pentagonal number
            if ((1 + 8 * triangular_number) ** 0.5) % 4 == 3.0:  # is a hexagonal number
                return triangular_number
    else:
        raise ValueError('No solution found')


if __name__ == '__main__':
    # This block is executed when the Python module is run directly.
    # It evaluates the solution function to ensure its correctness against test cases.

    # Importing required modules: `module_main` manages how the solution is invoked and tested,
    # while `cast` helps with type safety in passing the solution as a `SolutionProtocol`.
    from typing import cast
    from euler.evaluator import module_main

    # The `module_main` function handles the evaluation process by:
    # 1. Extracting the problem number from the file name for contextual usage.
    # 2. Accepting command-line arguments to configure execution, e.g., timeout or threading options.
    # 3. Running the `solution` function for all test cases defined in `problem_args_list`.
    # 4. Outputting the test results, including details such as whether the test passed/failed and time taken.
    # 5. Returning an appropriate exit code (exit code 0 indicates success, non-zero for failures).

    # The `SystemExit` ensures the program exits with the exit code returned by `module_main`.
    raise SystemExit(module_main(module_name=__file__,
                                 solution=cast(SolutionProtocol, solution),
                                 args_list=problem_args_list))
