# !/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Solution to Project Euler problem 2: Even Fibonacci numbers

Problem Statement:
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

Solution Approach:
This implementation uses a mathematical property of the Fibonacci sequence where
every third Fibonacci number is even. Rather than calculating all Fibonacci numbers
and filtering for even ones, we directly generate only the even Fibonacci numbers
using the recurrence relation:

F(n+3) = 4*F(n) + F(n-3)

where F(n) represents the nth even Fibonacci number (2, 8, 34, ...).

This approach is more efficient as it requires fewer iterations and calculations.

URL: https://projecteuler.net/problem=2
Answer: 4613732
"""

from euler.types import ProblemArgs, ProblemArgsList, SolutionProtocol

problem_args_list: ProblemArgsList = [
    ProblemArgs(kwargs={'max_limit': 10}, answer=10, ),
    ProblemArgs(kwargs={'max_limit': 100}, answer=44, ),
    ProblemArgs(kwargs={'max_limit': 4000000}, answer=4613732, ),
]


def solution(*, max_limit: int) -> int:
    """
    Calculates the sum of all even Fibonacci numbers below a specified maximum limit.

    Args:
        max_limit (int): The upper limit for the Fibonacci sequence. Only terms less than this value are considered.

    Returns:
        int: The sum of the even Fibonacci numbers below the given max_limit.
    """

    def even_fibonacci_numbers():
        """
        Generates even Fibonacci numbers below the given max_limit using an optimized formula.

        This generator uses the fact that every third Fibonacci number
        is even, starting from the second Fibonacci term. The series
        of even Fibonacci numbers is: 2, 8, 34, ...

        Yields:
            int: The next even Fibonacci number below max_limit.
        """
        even_fib_a, even_fib_b = 2, 8  # Initialize the first two even Fibonacci numbers.
        while even_fib_a < max_limit:
            yield even_fib_a
            even_fib_a, even_fib_b = even_fib_b, 4 * even_fib_b + even_fib_a

    # Calculate and return the sum of all even Fibonacci numbers below max_limit.
    return sum(even_fibonacci_numbers())


if __name__ == '__main__':
    # This block is executed when the Python module is run directly.
    # It evaluates the solution function to ensure its correctness against test cases.

    # Importing required modules: `module_main` manages how the solution is invoked and tested,
    # while `cast` helps with type safety in passing the solution as a `SolutionProtocol`.
    from typing import cast
    from euler.evaluator import module_main

    # The `module_main` function handles the evaluation process by:
    # 1. Extracting the problem number from the file name for contextual usage.
    # 2. Accepting command-line arguments to configure execution, e.g., timeout or threading options.
    # 3. Running the `solution` function for all test cases defined in `problem_args_list`.
    # 4. Outputting the test results, including details such as whether the test passed/failed and time taken.
    # 5. Returning an appropriate exit code (exit code 0 indicates success, non-zero for failures).

    # The `SystemExit` ensures the program exits with the exit code returned by `module_main`.
    raise SystemExit(module_main(module_name=__file__,
                                 solution=cast(SolutionProtocol, solution),
                                 args_list=problem_args_list))
