#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# solution to Project Euler problem 29
# https://projecteuler.net/problem=29
# Answer: 9183
# Notes: 
import textwrap

from euler.primes import prime_factorization
from euler.types import ProblemArgs, ProblemArgsList, SolutionProtocol

problem_args_list: ProblemArgsList = [
    ProblemArgs(
        kwargs={'max_number': 5},
        answer=15,
    ),
    ProblemArgs(
        kwargs={'max_number': 100},
        answer=9183,
    ),
    ProblemArgs(
        kwargs={'max_number': 1000},
        answer=977358,
    ),
]


def solution(*, max_number: int) -> int:
    """Calculate the number of distinct terms in the sequence of a^b.

    This function computes all possible integer combinations of a^b where 
    2 <= a <= max_number and 2 <= b <= max_number, then counts the number of 
    unique values in the resulting set.

    The solution adaptively chooses between two implementation strategies:
    1. For max_number ≤ 100: Uses a direct set comprehension approach that calculates all powers
       and automatically eliminates duplicates
    2. For max_number > 100: Uses a more efficient prime factorization approach that avoids
       computing extremely large numbers directly

    Mathematical Background:
    When generating all powers a^b, certain combinations yield the same value. For example,
    - 4^2 = 2^4 = 16
    - 8^2 = 4^3 = 2^6 = 64
    - 9^2 = 3^4 = 81

    These duplications follow specific patterns based on prime factorization. If we express each
    number in terms of its prime factors, two different expressions a₁^b₁ and a₂^b₂ will be equal
    if and only if they have the same prime factorization after raising to their respective powers.

    Time Complexity:
    - Brute force approach: O(n²) where n is max_number
    - Prime factorization approach: O(n² * log(n)), but avoids computing extremely large integers

    Space Complexity: 
    - O(n²) in the worst case, though the actual space used is less due to duplicates

    Args:
        max_number: The upper limit for both a and b (inclusive)

    Returns:
        The number of distinct terms in the sequence
    """
    if max_number > 100:
        # This approach would analyze the mathematical properties of powers to directly
        # count unique values without generating them all
        unique_powers = set()
        for a in range(2, max_number + 1):
            # Decompose 'a' into its prime factors to identify patterns
            prime_factors = prime_factorization(a)
            for b in range(2, max_number + 1):
                # Calculate a signature that uniquely identifies this power value without actually computing a^b
                signature = tuple((prime, power * b) for prime, power in prime_factors)
                unique_powers.add(signature)
        return len(unique_powers)
    else:
        # The simple approach is efficient enough for the problem constraints
        # For max_number=100, this runs in milliseconds on modern hardware
        return len({a ** b for a in range(2, max_number + 1) for b in range(2, max_number + 1)})


# Explicitly annotate that this function implements SolutionProtocol
solution: SolutionProtocol

solution.__doc__ = textwrap.dedent(r'''
Solution to Project Euler Problem 29: Distinct Powers
https://projecteuler.net/problem=29

Problem Description:
Consider all integer combinations of a^b for 2 <= a <= 5 and 2 <= b <= 5:
2^2=4, 2^3=8, 2^4=16, 2^5=32
3^2=9, 3^3=27, 3^4=81, 3^5=243
4^2=16, 4^3=64, 4^4=256, 4^5=1024
5^2=25, 5^3=125, 5^4=625, 5^5=3125

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125.

How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?

Solution Approach:
This problem requires finding the number of unique values in the set of all possible powers a^b
within the given range. Our implementation uses two different approaches depending on the input size:

1. For smaller inputs (max_number ≤ 100):
   - Generate all a^b combinations using a set comprehension
   - Python's set automatically eliminates duplicates
   - Count the resulting unique values

2. For larger inputs (max_number > 100):
   - Use prime factorization to avoid computing extremely large numbers
   - Express each number as its prime factorization
   - When raising to a power, multiply the exponents of each prime factor
   - Store unique prime factorization patterns to count distinct values

Mathematical Analysis of Duplicates:
The key insight is understanding when different base-exponent pairs produce identical values.
This happens due to the fundamental properties of exponentiation:

1. Duplicate Pattern: When a = c^k for some integers c and k, then a^b = c^(k*b)
   Example: 4 = 2², so 4³ = (2²)³ = 2⁶

2. Classification of Bases:
   - Prime bases (2, 3, 5, 7, 11, ...) never create duplicates with other bases
   - Composite bases can create duplicates when they share prime factorizations

3. Counting Unique Values:
   For a given maximum value n:
   - Total possible pairs: (n-1)² (for 2≤a≤n, 2≤b≤n)
   - For each composite base a = p₁^e₁ × p₂^e₂ × ... × pₖ^eₖ, we identify duplicates
   - A value a^b will be a duplicate if and only if there exists another pair (c,d) where
     c^d = a^b, which happens when they share the same prime factorization

Example Analysis for n=5:
- Total possible pairs: 16 (a,b pairs where 2≤a≤5, 2≤b≤5)
- Unique values: 15 (because 2⁴=4² creates one duplicate)

For n=100:
- Total possible pairs: 9,801
- Unique values: 9,183 (due to 618 duplicate values)

Implemented Approaches:
1. Direct Set Calculation (for smaller inputs):
   - Generates all powers using a simple set comprehension
   - Python's set automatically eliminates duplicates
   - Efficient for max_number ≤ 100
   - Time complexity: O(n²) where n is max_number

2. Prime Factorization Method (for larger inputs):
   - Decomposes each number into its prime factors
   - Multiplies the exponents when raising to a power
   - Stores unique factorization patterns
   - Avoids computing extremely large numbers
   - Time complexity: O(n² × log(n))

Performance Considerations:
- For n=100, the direct set calculation approach is sufficiently efficient
- For n=1000 and beyond, the prime factorization method saves time by avoiding large numbers
- The largest number that would need to be computed with the direct approach
  for n=1000 would be 1000^1000, which has approximately 3000 digits
''').strip()

if __name__ == '__main__':
    # When run directly, evaluate the solution with test cases
    # Import required modules for evaluating the solution
    from euler.evaluator import evaluate_solution
    from euler.cli import parser
    from euler.logger import logger

    # Parse command-line arguments
    args = parser.parse_args()

    # Set the logging level based on command-line arguments
    logger.setLevel(args.log_level)

    # Extract timeout and maximum worker threads from arguments
    timeout, max_workers = args.timeout, args.max_workers

    # Run the solution with the specified test cases and parameters
    # This validates that our implementation gives the correct answers
    evaluate_solution(solution=solution, args_list=problem_args_list, timeout=timeout, max_workers=max_workers)
