#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Solution to Project Euler problem 44: Pentagon numbers

Problem Statement:
Pentagonal numbers are generated by the formula, Pn = n(3n-1)/2. 
The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 
70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference 
are pentagonal and D = |Pk - Pj| is minimized; what is the value of D?

Solution Approach:
This solution methodically searches for pairs of pentagonal numbers that satisfy the required conditions:
1. Generate pentagonal numbers in increasing order
2. For each new pentagonal number Pk, check all previous pentagonal numbers Pj
3. Test if both the sum (Pk + Pj) and difference (Pk - Pj) are pentagonal
4. Return the first (minimum) difference that satisfies all conditions

We use the mathematical property that a number p is pentagonal if and only if
(1 + sqrt(24p + 1))/6 is an integer, which allows us to efficiently check if
a number is pentagonal without generating the entire sequence.

Test Cases:
- The example in the problem shows that P4 + P7 = P8, but their difference is not pentagonal
- The answer is 5482660

URL: https://projecteuler.net/problem=44
Answer: 5482660
"""

from euler.types import ProblemArgs, ProblemArgsList, SolutionProtocol

problem_args_list: ProblemArgsList = [
    ProblemArgs(
        kwargs={},  # No input parameters required for this problem
        answer=5482660,  # The expected minimum difference between pentagonal numbers
    ),
]


def pentagonal(n: int) -> int:
    """
    Calculate the nth pentagonal number.

    This function computes the nth number in the pentagonal sequence using the formula
    Pn = n(3n-1)/2. Pentagonal numbers have interesting mathematical properties and
    are used throughout number theory.

    Args:
        n: The index of the pentagonal number to calculate (1-indexed)
           Must be a positive integer

    Returns:
        The nth pentagonal number

    Examples:
        >>> pentagonal(1)
        1
        >>> pentagonal(4)
        22
        >>> pentagonal(8)
        92
    """
    return n * (3 * n - 1) // 2


def is_pentagonal(p: int) -> bool:
    """
    Check if a number is a pentagonal number.

    This function efficiently determines if a given number belongs to the pentagonal 
    sequence without generating the entire sequence. It uses the mathematical property
    that a number p is pentagonal if and only if (1 + sqrt(24p + 1))/6 is an integer,
    which can be verified by checking if sqrt(24p + 1) mod 6 equals 5.0.

    Args:
        p: The number to check

    Returns:
        True if p is a pentagonal number, False otherwise

    Examples:
        >>> is_pentagonal(22)  # P4 = 22
        True
        >>> is_pentagonal(48)  # 48 is not a pentagonal number
        False
        >>> is_pentagonal(92)  # P8 = 92
        True
    """
    return (1 + 24 * p) ** 0.5 % 6 == 5.0


def solution() -> int:
    """
    Find the minimum difference between pentagonal numbers with special properties.

    This solution searches for the pair of pentagonal numbers (Pj, Pk) where:
    1. Their sum (Pj + Pk) is also a pentagonal number
    2. Their difference (Pk - Pj) is also a pentagonal number
    3. The difference D = |Pk - Pj| is minimized

    The algorithm incrementally generates pentagonal numbers and tests each new number
    against all previously generated pentagonal numbers, checking if both their sum and
    difference are also pentagonal numbers.

    Returns:
        The minimum difference D between the pentagonal number pair that satisfies all conditions

    Example:
        >>> solution()
        5482660
    """
    i = 0
    while i := i + 1:
        for j in range(i - 1, 0, -1):
            pi, pj = pentagonal(i), pentagonal(j)
            if is_pentagonal(pi - pj) and is_pentagonal(pi + pj):
                return pi - pj
    else:
        raise ValueError("No solution found")


if __name__ == '__main__':
    # This block is executed when the Python module is run directly.
    # It evaluates the solution function to ensure its correctness against test cases.

    # Importing required modules: `module_main` manages how the solution is invoked and tested,
    # while `cast` helps with type safety in passing the solution as a `SolutionProtocol`.
    from typing import cast
    from euler.evaluator import module_main

    # The `module_main` function handles the evaluation process by:
    # 1. Extracting the problem number from the file name for contextual usage.
    # 2. Accepting command-line arguments to configure execution, e.g., timeout or threading options.
    # 3. Running the `solution` function for all test cases defined in `problem_args_list`.
    # 4. Outputting the test results, including details such as whether the test passed/failed and time taken.
    # 5. Returning an appropriate exit code (exit code 0 indicates success, non-zero for failures).

    # The `SystemExit` ensures the program exits with the exit code returned by `module_main`.
    raise SystemExit(module_main(module_name=__file__,
                                 solution=cast(SolutionProtocol, solution),
                                 args_list=problem_args_list))
