#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# solution to Project Euler problem 12
# https://projecteuler.net/problem=12
# Answer: answers={5: 28, 500: 76576500}
# Notes: This solution finds the first triangle number with over a specified number of divisors.
#        It uses an optimized divisor-counting algorithm that only checks up to the square root of the number.
#        Triangle numbers are calculated using the formula n*(n+1)/2 to avoid repeated addition.
import textwrap

from euler.types import ProblemArgs, ProblemArgsList, SolutionProtocol

problem_args_list: ProblemArgsList = [
    ProblemArgs(
        kwargs={'num_divisors': 5},
        answer=28,
    ),
    ProblemArgs(
        kwargs={'num_divisors': 500},
        answer=76576500,
    ),
]


def num_factors(n: int) -> int:
    """Calculate the number of factors (divisors) for a given integer.

    This function uses an optimized approach that only checks divisors up to the square root of n.
    For each divisor 'i' found below sqrt(n), we count both i and n/i as factors.
    This gives us a 2x speedup compared to checking all numbers from 1 to n.
    The 1 is added at the beginning (to count 1 as a factor), and n is counted implicitly.
    We handle perfect-squares specially by subtracting 1 when sqrt(n) is a divisor to avoid counting it twice.

    Args:
        n: A positive integer

    Returns:
        The total number of factors (divisors) of n
    """
    return 1 + 2 * sum([1 for i in range(2, int(n ** 0.5) + 1) if n % i == 0]) - (1 if n % int(n ** 0.5) == 0 else 0)


def solution(*, num_divisors: int) -> int:
    """Find the first triangle number with more than the specified number of divisors.

    A triangle number is the sum of natural numbers from 1 to n. The nth triangle number
    can be efficiently calculated using the formula: n*(n+1)/2. This function iteratively
    generates triangle numbers and checks each one until finding the first with more than
    the required number of divisors.

    Args:
        num_divisors: The minimum number of divisors required

    Returns:
        The first triangle number that has more than num_divisors divisors
    """
    i, triangle_number = 1, 1
    while num_factors(triangle_number) <= num_divisors:
        i += 1
        triangle_number = i * (i + 1) // 2

    return triangle_number


# Explicitly annotate that this function implements SolutionProtocol
solution: SolutionProtocol

solution.__doc__ = textwrap.dedent(r'''
solution to Project Euler problem 12
https://projecteuler.net/problem=12
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
1 : 1
3 : 1,3
6 : 1,2,3,6
10 : 1,2,5,10
15 : 1,3,5,15
21 : 1,3,7,21
28 : 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?

''').strip()

if __name__ == '__main__':
    # When run directly, evaluate the solution with test cases
    # Import required modules for evaluating the solution
    from euler.evaluator import evaluate_solution
    from euler.cli import parser
    from euler.logger import logger

    # Parse command-line arguments
    args = parser.parse_args()

    # Set the logging level based on command-line arguments
    logger.setLevel(args.log_level)

    # Extract timeout and maximum worker threads from arguments
    timeout, max_workers = args.timeout, args.max_workers

    # Run the solution with the specified test cases and parameters
    # This validates that our implementation gives the correct answers
    evaluate_solution(solution=solution, args_list=problem_args_list, timeout=timeout, max_workers=max_workers)
