#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# solution to Project Euler problem 44
# https://projecteuler.net/problem=44
# Answer: 5482660
# Notes: 
"""Solution to Project Euler problem 44: Pentagon numbers.

This module finds the pair of pentagonal numbers, P_j and P_k, for which:
1. Their sum (P_j + P_k) is also a pentagonal number
2. Their difference (P_k - P_j) is also a pentagonal number
3. The difference D = |P_k - P_j| is minimized

The solution uses mathematical properties of pentagonal numbers to efficiently
generate and test pairs, implementing an optimized search strategy that
examines pairs in order of increasing difference.

Key concepts:
- Pentagonal numbers: P_n = n(3n-1)/2
- Mathematical test for pentagonal numbers
- Optimized search algorithm
- Wallis' formula for testing if a number is pentagonal
"""
import textwrap

from euler.types import ProblemArgs, ProblemArgsList, SolutionProtocol

# List of test cases for this problem
# For this problem, no additional input parameters are needed
problem_args_list: ProblemArgsList = [
    ProblemArgs(
        kwargs={},  # No input parameters required for this problem
        answer=5482660,  # The expected minimum difference between pentagonal numbers
    ),
]


def pentagonal(n: int) -> int:
    """Calculate the nth pentagonal number.

    The pentagonal number sequence is given by the formula P_n = n(3n-1)/2.

    Args:
        n: The index of the pentagonal number to calculate (1-indexed)
           n must be a positive integer.

    Returns:
        The nth pentagonal number.

    Examples:
        >>> pentagonal(1)
        1
        >>> pentagonal(4)
        22
        >>> pentagonal(8)
        92
    """
    return n * (3 * n - 1) // 2


def is_pentagonal(p: int) -> bool:
    """Check if a number is a pentagonal number.

    This function uses a mathematical property derived from the pentagonal formula.
    A number p is pentagonal if and only if (1 + sqrt(24p + 1))/6 is an integer.

    This can be rewritten to check if sqrt(24p + 1) mod 6 equals 5.0.

    Args:
        p: The number to check

    Returns:
        True if p is a pentagonal number, False otherwise

    Examples:
        >>> is_pentagonal(22)
        True
        >>> is_pentagonal(48)
        False
    """
    return (1 + 24 * p) ** 0.5 % 6 == 5.0


def solution() -> int:
    """Find the minimum difference between pentagonal numbers with special properties.

    This function searches for a pair of pentagonal numbers P_j and P_k such that:
    1. Their sum (P_j + P_k) is also a pentagonal number
    2. Their difference (P_k - P_j) is also a pentagonal number
    3. The difference D = |P_k - P_j| is minimized

    The search strategy:
    - Generate pentagonal numbers in increasing order
    - For each new pentagonal number P_i, check all previous pentagonal numbers P_j
      in decreasing order (to find the minimum difference first)
    - Test if both the sum and difference are pentagonal
    - Return the first (minimum) difference that satisfies all conditions

    Returns:
        The minimum difference between pentagonal numbers that meet the criteria

    Raises:
        ValueError: If no solution is found (should not occur for this problem)
    """
    i = 0
    while i := i + 1:
        for j in range(i - 1, 0, -1):
            pi, pj = pentagonal(i), pentagonal(j)
            if is_pentagonal(pi - pj) and is_pentagonal(pi + pj):
                return pi - pj
    else:
        raise ValueError("No solution found")


# Explicitly annotate that this function implements SolutionProtocol
solution: SolutionProtocol

solution.__doc__ = textwrap.dedent(r'''
solution to Project Euler problem 44: Pentagon Numbers
https://projecteuler.net/problem=44

Problem Description:
Pentagonal numbers are generated by the formula, P_n=n(3n-1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their difference, 70 - 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, P_j and P_k,
for which their sum and difference are pentagonal and D = |P_k - P_j| is minimised; what is the value of D?

Approach:
1. Mathematical Foundation:
   - Pentagonal numbers follow the formula P_n = n(3n-1)/2.
   - A number p is pentagonal if and only if (1 + sqrt(24p + 1))/6 is an integer.
   - We use the equivalent test: sqrt(24p + 1) mod 6 == 5.0

2. Search Strategy:
   - Generate pentagonal numbers in order (P_1, P_2, P_3, ...).
   - For each new P_i, check all previous pentagonal numbers P_j (j < i).
   - Test if both (P_i + P_j) and (P_i - P_j) are pentagonal.
   - Return the first valid difference found (guaranteed to be minimal).

3. Optimization Techniques:
   - We search in decreasing order of j for each i to find the minimum difference first.
   - The algorithm uses the walrus operator (:=) in Python 3.8+ for concise iteration.
   - We leverage the mathematical test for pentagonal numbers rather than generating and searching
     through the entire sequence.
   - Early return ensures we stop as soon as we find the first valid pair.

Mathematical Insights:
- The formula for testing if a number is pentagonal comes from solving the equation
  n(3n-1)/2 = p for n, which gives n = (1 + sqrt(1 + 24p))/6.
- For n to be a positive integer (making p pentagonal), (1 + sqrt(1 + 24p)) must be
  divisible by 6, which is equivalent to sqrt(1 + 24p) mod 6 == 5.

Time Complexity: Theoretically unbounded as we don't know how far we need to search,
but in practice, the solution is found relatively quickly (at P_1020 and P_2167).

Space Complexity: O(1) - We only store a constant number of variables regardless of
how many pentagonal numbers we generate.
''').strip()

if __name__ == '__main__':
    # When run directly, evaluate the solution with test cases
    # Import required modules for evaluating the solution
    from euler.evaluator import evaluate_solution
    from euler.cli import parser
    from euler.logger import logger

    # Parse command-line arguments
    args = parser.parse_args()

    # Set the logging level based on command-line arguments
    logger.setLevel(args.log_level)

    # Extract timeout and maximum worker threads from arguments
    timeout, max_workers = args.timeout, args.max_workers

    # Run the solution with the specified test cases and parameters
    # This validates that our implementation gives the correct answers
    evaluate_solution(solution=solution, args_list=problem_args_list, timeout=timeout, max_workers=max_workers)
