#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# solution to Project Euler problem 2
# https://projecteuler.net/problem=2
# Answer: 
# Notes: 
import textwrap

from euler.types import ProblemArgs, ProblemArgsList, SolutionProtocol

problem_args_list: ProblemArgsList = [
    ProblemArgs(
        kwargs={'max_limit': 10},
        answer=10,
    ),
    ProblemArgs(
        kwargs={'max_limit': 100},
        answer=44,
    ),
    ProblemArgs(
        kwargs={'max_limit': 4000000},
        answer=4613732,
    ),
]


def solution(*, max_limit: int) -> int:
    def even_fibonacci_numbers():
        even_fib_a, even_fib_b = 2, 8
        while even_fib_a < max_limit:
            yield even_fib_a
            even_fib_a, even_fib_b = even_fib_b, 4 * even_fib_b + even_fib_a

    return sum(even_fibonacci_numbers())


# Explicitly annotate that this function implements SolutionProtocol
solution: SolutionProtocol

solution.__doc__ = textwrap.dedent('''
solution to Project Euler problem 2
https://projecteuler.net/problem=2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...$$
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


''').strip()

if __name__ == '__main__':
    from euler.evaluator import evaluate_solution
    from euler.cli import parser
    from euler.logger import logger

    args = parser.parse_args()
    logger.setLevel(args.log_level)
    timeout, max_workers = args.timeout, args.max_workers

    evaluate_solution(solution=solution, args_list=problem_args_list, timeout=timeout, max_workers=max_workers)
