#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Solution to Project Euler problem 29: Distinct powers

Problem Statement:
Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

2^2=4, 2^3=8, 2^4=16, 2^5=32
3^2=9, 3^3=27, 3^4=81, 3^5=243
4^2=16, 4^3=64, 4^4=256, 4^5=1024
5^2=25, 5^3=125, 5^4=625, 5^5=3125

If they are then placed in numerical order, with any repeats removed, we get the following
sequence of 15 distinct terms:
4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125.

How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

Solution Approach:
This implementation offers two strategies depending on the problem size:

1. For small inputs (max_number ≤ 100): A direct set comprehension approach that calculates
   all powers and automatically eliminates duplicates using Python's set data structure.

2. For larger inputs (max_number > 100): An optimized approach using prime factorization
   to avoid computing extremely large numbers. Each number is represented by its unique
   prime factorization signature, allowing us to identify duplicates without calculating
   the actual values.

The solution recognizes that certain combinations yield the same value (e.g., 4^2 = 2^4 = 16),
and accounts for these duplications by tracking the unique prime factorization patterns.

Test Cases:
- For max_number=5, the answer is 15
- For max_number=100, the answer is 9183
- For max_number=1000, the answer is 977358

URL: https://projecteuler.net/problem=29
Answer: 9183
"""

from euler.primes import prime_factorization
from euler.types import ProblemArgs, ProblemArgsList, SolutionProtocol

problem_args_list: ProblemArgsList = [
    ProblemArgs(kwargs={'max_number': 5}, answer=15, ),
    ProblemArgs(kwargs={'max_number': 100}, answer=9183, ),
    ProblemArgs(kwargs={'max_number': 1000}, answer=977358, ),
]


def solution(*, max_number: int) -> int:
    """Calculate the number of distinct terms in the sequence of a^b.

    This function counts the unique values in the sequence generated by a^b where
    2 ≤ a ≤ max_number and 2 ≤ b ≤ max_number, using the most appropriate algorithm
    based on the input size.

    Args:
        max_number: The upper limit for both a and b (inclusive)

    Returns:
        The number of distinct terms in the sequence

    Example:
        >>> solution(max_number=5)
        15
        >>> solution(max_number=100)
        9183
    """
    if max_number > 100:
        # This approach would analyze the mathematical properties of powers to directly
        # count unique values without generating them all
        unique_powers = set()
        for a in range(2, max_number + 1):
            # Decompose 'a' into its prime factors to identify patterns
            prime_factors = prime_factorization(a)
            for b in range(2, max_number + 1):
                # Calculate a signature that uniquely identifies this power value without actually computing a^b
                signature = tuple((prime, power * b) for prime, power in prime_factors)
                unique_powers.add(signature)
        return len(unique_powers)
    else:
        # The simple approach is efficient enough for the problem constraints
        # For max_number=100, this runs in milliseconds on modern hardware
        return len({a ** b for a in range(2, max_number + 1) for b in range(2, max_number + 1)})


if __name__ == '__main__':
    # This block is executed when the Python module is run directly.
    # It evaluates the solution function to ensure its correctness against test cases.

    # Importing required modules: `module_main` manages how the solution is invoked and tested,
    # while `cast` helps with type safety in passing the solution as a `SolutionProtocol`.
    from typing import cast
    from euler.evaluator import module_main

    # The `module_main` function handles the evaluation process by:
    # 1. Extracting the problem number from the file name for contextual usage.
    # 2. Accepting command-line arguments to configure execution, e.g., timeout or threading options.
    # 3. Running the `solution` function for all test cases defined in `problem_args_list`.
    # 4. Outputting the test results, including details such as whether the test passed/failed and time taken.
    # 5. Returning an appropriate exit code (exit code 0 indicates success, non-zero for failures).

    # The `SystemExit` ensures the program exits with the exit code returned by `module_main`.
    raise SystemExit(module_main(module_name=__file__,
                                 solution=cast(SolutionProtocol, solution),
                                 args_list=problem_args_list))
