#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Solution to Project Euler problem 2
# https://projecteuler.net/problem=2
# By considering the terms in the Fibonacci sequence whose values do not exceed a given limit, 
# this script computes the sum of the even-valued terms.
import textwrap

from euler.types import ProblemArgs, ProblemArgsList, SolutionProtocol

# Define problem arguments and expected solutions for testing purposes.
problem_args_list: ProblemArgsList = [
    ProblemArgs(
        kwargs={'max_limit': 10},
        answer=10,
    ),
    ProblemArgs(
        kwargs={'max_limit': 100},
        answer=44,
    ),
    ProblemArgs(
        kwargs={'max_limit': 4000000},
        answer=4613732,
    ),
]


def solution(*, max_limit: int) -> int:
    """
    Calculates the sum of all even Fibonacci numbers below a specified maximum limit.

    Args:
        max_limit (int): The upper limit for the Fibonacci sequence. Only terms less than this value are considered.

    Returns:
        int: The sum of the even Fibonacci numbers below the given max_limit.
    """

    def even_fibonacci_numbers():
        """
        Generates even Fibonacci numbers below the given max_limit using an optimized formula.

        This generator uses the fact that every third Fibonacci number 
        is even, starting from the second Fibonacci term. The series 
        of even Fibonacci numbers is: 2, 8, 34, ...

        Yields:
            int: The next even Fibonacci number below max_limit.
        """
        even_fib_a, even_fib_b = 2, 8  # Initialize the first two even Fibonacci numbers.
        while even_fib_a < max_limit:
            yield even_fib_a
            even_fib_a, even_fib_b = even_fib_b, 4 * even_fib_b + even_fib_a

    # Calculate and return the sum of all even Fibonacci numbers below max_limit.
    return sum(even_fibonacci_numbers())


# Explicitly annotate that this function implements SolutionProtocol
solution: SolutionProtocol

# Add detailed documentation to the solution function.
solution.__doc__ = textwrap.dedent('''
Solution to Project Euler problem 2
https://projecteuler.net/problem=2

Overview:
Each term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with the terms 1 and 2, the sequence begins as follows:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
This script calculates the sum of only those terms in the Fibonacci sequence 
that are even and do not exceed a given maximum value.

Explanation:
The even Fibonacci numbers appear in the sequence with a predictable pattern,
such that every third term is even. The even Fibonacci numbers below 100 are:
    2, 8, 34, ...
An efficient way to compute the sum involves skipping other Fibonacci terms 
and generating only the even ones.

Example Calculations:
1. For max_limit = 10, the even Fibonacci numbers are [2, 8]; their sum is 10.
2. For max_limit = 100, the even Fibonacci numbers are [2, 8, 34]; their sum is 44.

Hints:
- Use a generator to calculate the even Fibonacci numbers efficiently.
- The formula for even Fibonacci numbers is derived from their recurrence relation.
''').strip()

if __name__ == '__main__':
    # When run directly, evaluate the solution with test cases
    # Import required modules for evaluating the solution
    from euler.evaluator import evaluate_solution
    from euler.cli import parser
    from euler.logger import logger

    # Parse command-line arguments
    args = parser.parse_args()

    # Set the logging level based on command-line arguments
    logger.setLevel(args.log_level)

    # Extract timeout and maximum worker threads from arguments
    timeout, max_workers = args.timeout, args.max_workers

    # Run the solution with the specified test cases and parameters
    # This validates that our implementation gives the correct answers
    evaluate_solution(solution=solution, args_list=problem_args_list, timeout=timeout, max_workers=max_workers)
