#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# solution to Project Euler problem 45
# https://projecteuler.net/problem=45
# Answer: 1533776805
# Notes: 
"""Solution to Project Euler problem 45: Triangular, Pentagonal, and Hexagonal Numbers.

This module finds the next number (after T_285) that is simultaneously triangular,
pentagonal, and hexagonal. These special numbers belong to all three sequences:

- Triangular numbers: T_n = n(n+1)/2
- Pentagonal numbers: P_n = n(3n-1)/2
- Hexagonal numbers: H_n = n(2n-1)

The solution uses mathematical properties to efficiently test if a number belongs
to each sequence without having to generate the full sequences. It employs an
iterative approach to find the next such number after the known example (40,755).

Key concepts:
- Figurate numbers (triangular, pentagonal, hexagonal)
- Mathematical tests for sequence membership
- Iterative search with early termination
- Algebraic formulas for sequence testing
"""
import textwrap

from euler.types import ProblemArgs, ProblemArgsList, SolutionProtocol

# List of test cases for this problem
# The problem requires finding the next triangular number after T_285
# that is also pentagonal and hexagonal
problem_args_list: ProblemArgsList = [
    ProblemArgs(
        kwargs={'n': 285},  # Start the search from a triangular number T_285
        answer=1533776805,  # The expected result (the next triangular-pentagonal-hexagonal number)
    ),
]


def solution(n: int) -> int:
    """Find the next triangular number that is also pentagonal and hexagonal.

    This function iteratively generates triangular numbers starting from T_{n+1},
    tests each one to determine if it's also a pentagonal and hexagonal number,
    and returns the first such number found.

    The tests for pentagonal and hexagonal properties use mathematical formulas:
    - A number m is pentagonal if and only if (1 + sqrt(24m + 1))/6 is an integer
      (equivalent to checking if sqrt(24m + 1) mod 6 = 5.0)
    - A number m is hexagonal if and only if (1 + sqrt(8m + 1))/4 is an integer
      (equivalent to checking if sqrt(8m + 1) mod 4 = 3.0)

    Args:
        n: The index to start from (the function will find T_{n+1} and beyond)

    Returns:
        The next triangular number that is also pentagonal and hexagonal

    Raises:
        ValueError: If no solution is found (should not occur for this problem)
    """
    while n := n + 1:
        triangular_number = n * (n + 1) // 2  # triangular number
        if ((1 + 24 * triangular_number) ** 0.5) % 6 == 5.0:  # is a pentagonal number
            if ((1 + 8 * triangular_number) ** 0.5) % 4 == 3.0:  # is a hexagonal number
                return triangular_number
    else:
        raise ValueError('No solution found')


# Explicitly annotate that this function implements SolutionProtocol
solution: SolutionProtocol

solution.__doc__ = textwrap.dedent(r'''
solution to Project Euler problem 45: Triangular, Pentagonal, and Hexagonal
https://projecteuler.net/problem=45

Problem Description:
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle
T_n=n(n+1)/2
1, 3, 6, 10, 15, ...

Pentagonal
P_n=n(3n - 1)/2
1, 5, 12, 22, 35, ...

Hexagonal
H_n=n(2n - 1)
1, 6, 15, 28, 45, ...

It can be verified that T_{285} = P_{165} = H_{143} = 40755.
Find the next triangle number that is also pentagonal and hexagonal.

Approach:
1. Mathematical Foundation:
   - We use the fact that a number T is triangular if T = n(n+1)/2 for some integer n
   - A number P is pentagonal if and only if (1 + sqrt(24P + 1))/6 is an integer
   - A number H is hexagonal if and only if (1 + sqrt(8H + 1))/4 is an integer

2. Search Strategy:
   - Start generating triangular numbers from T_{286} onwards
   - For each triangular number, test if it is also pentagonal and hexagonal
   - Return the first number that satisfies all three conditions

3. Efficiency Considerations:
   - Rather than generating all three sequences and finding intersections,
     we generate one sequence (triangular) and test membership in the others
   - The tests for pentagonal and hexagonal properties are derived from solving
     the quadratic formulas for each sequence
   - These tests are much faster than naive checks against pre-generated lists

Mathematical Insights:
- All hexagonal numbers are also triangular (this can be proven algebraically)
- Therefore, we only need to check if a hexagonal number is also pentagonal
- However, this implementation checks both conditions explicitly for clarity
- The next number after 40755 that satisfies all conditions is 1533776805

Time Complexity: O(k) where k is the difference between consecutive triangular-pentagonal-hexagonal
numbers. The algorithm is linear in the number of triangular numbers we need to check.

Space Complexity: O(1) - We only store a constant number of variables regardless of input size.
''').strip()

if __name__ == '__main__':
    # When run directly, evaluate the solution with test cases
    # Import required modules for evaluating the solution
    from euler.evaluator import evaluate_solution
    from euler.cli import parser
    from euler.logger import logger

    # Parse command-line arguments
    args = parser.parse_args()

    # Set the logging level based on command-line arguments
    logger.setLevel(args.log_level)

    # Extract timeout and maximum worker threads from arguments
    timeout, max_workers = args.timeout, args.max_workers

    # Run the solution with the specified test cases and parameters
    # This validates that our implementation gives the correct answers
    evaluate_solution(solution=solution, args_list=problem_args_list, timeout=timeout, max_workers=max_workers)
