#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# solution to Project Euler problem 61
# https://projecteuler.net/problem=61
# Answer: 
# Notes: 
import textwrap
from typing import Any, Dict

from euler.types import ProblemArgs, ProblemArgsList, SolutionProtocol, SolutionResult

problem_args_list: ProblemArgsList = [
    ProblemArgs(kwargs={}, answer=None, ),
]


def solution(**kwarg: Dict[str, Any]) -> SolutionResult:
    # enter the solution here
    raise NotImplementedError


# Explicitly annotate that this function implements SolutionProtocol
solution: SolutionProtocol

solution.__doc__ = textwrap.dedent(r'''
solution to Project Euler problem 61
https://projecteuler.net/problem=61
Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
Triangle
 
$P_{3,n}=n(n+1)/2$
 
$1, 3, 6, 10, 15, ...$
Square
 
$P_{4,n}=n^2$
 
$1, 4, 9, 16, 25, ...$
Pentagonal
 
$P_{5,n}=n(3n-1)/2$
 
$1, 5, 12, 22, 35, ...$
Hexagonal
 
$P_{6,n}=n(2n-1)$
 
$1, 6, 15, 28, 45, ...$
Heptagonal
 
$P_{7,n}=n(5n-3)/2$
 
$1, 7, 18, 34, 55, ...$
Octagonal
 
$P_{8,n}=n(3n-2)$
 
$1, 8, 21, 40, 65, ...$
The ordered set of three $4$-digit numbers: $8128$, $2882$, $8281$, has three interesting properties.
The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
Each polygonal type: triangle ($P_{3,127}=8128$), square ($P_{4,91}=8281$), and pentagonal ($P_{5,44}=2882$), is represented by a different number in the set.
This is the only set of $4$-digit numbers with this property.
Find the sum of the only ordered set of six cyclic $4$-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.


''').strip()

if __name__ == '__main__':
    # When run directly, evaluate the solution with test cases
    # Import required modules for evaluating the solution
    from euler.evaluator import evaluate_solution
    from euler.cli import parser
    from euler.logger import logger

    # Parse command-line arguments
    args = parser.parse_args()

    # Set the logging level based on command-line arguments
    logger.setLevel(args.log_level)

    # Extract timeout and maximum worker threads from arguments
    timeout, max_workers = args.timeout, args.max_workers

    # Run the solution with the specified test cases and parameters
    # This validates that our implementation gives the correct answers
    evaluate_solution(solution=solution, args_list=problem_args_list, timeout=timeout, max_workers=max_workers)