repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/pycqa/flake8.git
    rev: 7.3.0
    hooks:
      - id: flake8
        language: python
        language_version: python3.12
        stages:
          - pre-commit
          - pre-push
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "mypy"
        language: python
        language_version: python3.12
        require_serial: true
        always_run: true
        verbose: true
        stages:
          - pre-commit
          - pre-push
        files: \.py$  # Restrict mypy to Python files only
        exclude: tests
      - id: unittest
        name: unittest
        entry: "coverage run -m unittest discover -s tests"
        language: python
        language_version: python3.12
        pass_filenames: false
        always_run: true
        stages:
          - pre-push