#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# solution to Project Euler problem 799
# https://projecteuler.net/problem=799
# Answer: 
# Notes: 
import textwrap
from typing import Any, Dict

from euler.types import ProblemArgs, ProblemArgsList, SolutionProtocol, SolutionResult

problem_args_list: ProblemArgsList = [
    ProblemArgs(kwargs={}, answer=None, ),
]


def solution(**kwarg: Dict[str, Any]) -> SolutionResult:
    # enter the solution here
    raise NotImplementedError


# Explicitly annotate that this function implements SolutionProtocol
solution: SolutionProtocol

solution.__doc__ = textwrap.dedent(r'''
solution to Project Euler problem 799
https://projecteuler.net/problem=799

Pentagonal numbers are generated by the formula: $P_n = \tfrac 12n(3n-1)$ giving the sequence:

$$1,5,12,22,35, 51,70,92,\ldots $$

Some pentagonal numbers can be expressed as the sum of two other pentagonal numbers.

For example:

$$P_8 = 92 = 22 + 70 = P_4 + P_7$$

3577 is the smallest pentagonal number that can be expressed as the sum of two pentagonal numbers in two different ways

$$
\begin{align}
P_{49} = 3577 & = 3432 + 145 = P_{48} + P_{10} \\
 & = 3290 + 287 = P_{47}+P_{14}
\end{align}
$$

107602 is the smallest pentagonal number that can be expressed as the sum of two pentagonal numbers in three different ways.


Find the smallest pentagonal number that can be expressed as the sum of two pentagonal numbers in over 100 different ways.



''').strip()

if __name__ == '__main__':
    # When run directly, evaluate the solution with test cases
    # Import required modules for evaluating the solution
    from euler.evaluator import evaluate_solution
    from euler.cli import parser
    from euler.logger import logger

    # Parse command-line arguments
    args = parser.parse_args()

    # Set the logging level based on command-line arguments
    logger.setLevel(args.log_level)

    # Extract timeout and maximum worker threads from arguments
    timeout, max_workers = args.timeout, args.max_workers

    # Run the solution with the specified test cases and parameters
    # This validates that our implementation gives the correct answers
    evaluate_solution(solution=solution, args_list=problem_args_list, timeout=timeout, max_workers=max_workers)