#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
  Project Euler Problem 2: Even Fibonacci Numbers.

  Problem Statement:
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.

  Solution Approach:
    To solve this problem efficiently, generate Fibonacci numbers starting
    from 1 and 2, maintaining the sequence by summing the previous two terms.
    Iterate while the terms remain less than or equal to four million. To find
    the sum of even-valued terms, check each term for evenness before adding
    it to a cumulative total. Consider leveraging the pattern that every third
    Fibonacci number is even, which can optimize the iteration by skipping
    odd terms. This approach requires only simple iteration and conditional
    accumulation without heavy computational resources.

  Test Cases:
    preliminary:
      max_limit=10,
      answer=10.

      max_limit=100,
      answer=44.

    main:
      max_limit=4000000,
      answer=4613732.


  Answer: 4613732
  URL: https://projecteuler.net/problem=2
"""
from __future__ import annotations

from typing import Generator

from euler.logger import logger
from euler.setup import TestCaseCategory, evaluate, register_solution


@register_solution(euler_problem=2, test_case_category=TestCaseCategory.EXTENDED)
def even_fibonacci_numbers(*, max_limit: int) -> int:
    def _even_fibonacci_numbers() -> Generator[int, None, None]:
        even_fib_a, even_fib_b = (2, 8)
        while even_fib_a < max_limit:
            yield even_fib_a
            even_fib_a, even_fib_b = (even_fib_b, 4 * even_fib_b + even_fib_a)

    return sum(_even_fibonacci_numbers())


if __name__ == '__main__':
    logger.setLevel('ERROR')
    raise SystemExit(evaluate(euler_problem=2, time_out_in_seconds=300, mode='evaluate'))
