#!/usr/bin/env python3.14
# -*- coding: utf-8 -*-
"""Tests for the authorization audit table generated by solver.utils.update_doc
(gen_authorization_table) — the generated `docs/authorizations.md` view of each
command's module and the rungs that may run it, distinct from the deployed
``authorizations.json`` policy."""
from __future__ import annotations

import unittest
import unittest.mock

from solver.auth import LADDER, Authorizations, Subject
from solver.config import ExitCodes, config
from solver.shell.command import registry
from solver.utils import update_doc
from solver.utils.loader import load_commands
from solver.utils.update_doc import (GENERATORS, _least_profile, _module_of,
                                     gen_authorization_table)

_AUTHZ = Authorizations.load()


def _admin_subject() -> Subject:
    return Subject(user='t', slug='t-000000', channel='terminal', auth_method='test',
                   profile='admin')


class AuthorizationTableTests(unittest.TestCase):
    def setUp(self) -> None:
        self._saved_subject = config.subject
        config.subject = _admin_subject()          # admin sees the whole registry
        self.addCleanup(self._restore)
        load_commands()                            # populate the registry

    def _restore(self) -> None:
        config.subject = self._saved_subject

    def test_registered_as_a_generator(self) -> None:
        self.assertIs(GENERATORS['authorization-table'], gen_authorization_table)

    def test_table_covers_every_command(self) -> None:
        table = gen_authorization_table()
        for cmd in registry.all():
            self.assertIn(f'`{cmd.name}`', table)                 # every command has a row

    def test_table_has_a_column_per_rung(self) -> None:
        table = gen_authorization_table()
        header = table.splitlines()[0]
        for profile in LADDER:
            self.assertIn(profile.capitalize(), header)           # one column per rung
        sample = registry.all()[0]
        self.assertIn(f'`{_module_of(sample)}`', table)           # module column

    def test_each_row_ticks_exactly_the_rungs_at_or_above_the_floor(self) -> None:
        """The tick grid must agree with the floor it is derived from: a run of ticks
        from the command's `requires` rightwards, and nothing below it."""
        rows = {}
        for line in gen_authorization_table().splitlines()[2:]:
            cells = [c.strip() for c in line.strip().strip('|').split('|')]
            rows[cells[1].strip('`')] = cells[2:]
        for cmd in registry.all():
            ticked = [p for p, cell in zip(LADDER, rows[cmd.name]) if cell == '✓']
            expected = [p for p in LADDER if LADDER.index(p) >= LADDER.index(cmd.requires)]
            self.assertEqual(ticked, expected, cmd.name)

    def test_least_profile_is_the_lowest_privilege_that_satisfies(self) -> None:
        # A read-only command is reachable by the base reader; a write-floored one
        # only from contributor up; the admin floor only by admin.
        ls = registry.resolve('ls')
        assert ls is not None
        self.assertEqual(_least_profile(ls), 'reader')
        update_docs = registry.resolve('update-docs')
        assert update_docs is not None
        self.assertEqual(_least_profile(update_docs), 'admin')
        update_tags = registry.resolve('update-tags')
        assert update_tags is not None
        self.assertEqual(_least_profile(update_tags), 'maintainer')


class RegistryCompletenessTests(unittest.TestCase):
    """Why `update-docs` is admin-floored: a lesser profile's registry is truncated.

    Registration is profile-filtered, so generating the audit table from a maintainer's
    registry would quietly delete every admin-floored row — from the one document whose
    worth is being complete. This pins the mechanism the floor exists to defend against."""

    def setUp(self) -> None:
        self._saved_subject = config.subject
        self.addCleanup(self._restore)

    def _restore(self) -> None:
        config.subject = self._saved_subject
        load_commands(refresh_modules=True)

    def test_a_maintainers_registry_cannot_see_the_admin_commands(self) -> None:
        config.subject = _admin_subject()
        load_commands(refresh_modules=True)
        admin_floored = {cmd.name for cmd in registry.all() if cmd.requires == 'admin'}
        self.assertIn('users', admin_floored)             # the set is non-empty…
        self.assertIn('git-publish', admin_floored)       # …and these are in it
        self.assertTrue(admin_floored <= {cmd.name for cmd in registry.all()})


if __name__ == '__main__':
    unittest.main()
