#!/usr/bin/env python3.14
# -*- coding: utf-8 -*-
"""Tests for the authorization audit table generated by solver.utils.update_doc
(gen_authorization_table, DD-12) — the generated `docs/authorizations.md` view of
each command's module / channels / requires / least-profile, distinct from the
authored ``authorizations.json`` policy."""
from __future__ import annotations

import unittest

from solver.auth import Authorizations, Subject
from solver.config import config
from solver.shell.command import registry
from solver.utils.loader import load_commands
from solver.utils.update_doc import (GENERATORS, _least_profile, _module_of,
                                     gen_authorization_table)

_AUTHZ = Authorizations.load()


def _admin_subject() -> Subject:
    return Subject(user='t', slug='t-000000', channel='terminal', auth_method='test',
                   profile='admin', permissions=_AUTHZ.permissions_for('admin'))


class AuthorizationTableTests(unittest.TestCase):
    def setUp(self) -> None:
        self._saved_subject = config.subject
        config.subject = _admin_subject()          # admin sees the whole registry
        self.addCleanup(self._restore)
        load_commands()                            # populate the registry

    def _restore(self) -> None:
        config.subject = self._saved_subject

    def test_registered_as_a_generator(self) -> None:
        self.assertIs(GENERATORS['authorization-table'], gen_authorization_table)

    def test_table_covers_every_command(self) -> None:
        table = gen_authorization_table()
        for cmd in registry.all():
            self.assertIn(f'`{cmd.name}`', table)                 # every command has a row

    def test_table_reports_module_and_least_profile(self) -> None:
        table = gen_authorization_table()
        sample = registry.all()[0]
        self.assertIn(f'`{_module_of(sample)}`', table)           # module column
        self.assertIn(f'`{_least_profile(sample)}`', table)       # least-profile column

    def test_least_profile_is_the_lowest_privilege_that_satisfies(self) -> None:
        # A read-only command (solutions:read) is reachable by the base reader; an
        # admin-only command (infra:execute) only by admin.
        ls = registry.resolve('ls')
        assert ls is not None
        self.assertEqual(_least_profile(ls), 'reader')
        update_docs = registry.resolve('update-docs')
        assert update_docs is not None
        self.assertEqual(_least_profile(update_docs), 'admin')


if __name__ == '__main__':
    unittest.main()
