#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Project Euler Problem 12: Highly Divisible Triangular Number.

Problem Statement:
    The sequence of triangle numbers is generated by adding the natural numbers.
    So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
    ten terms would be:
    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    Let us list the factors of the first seven triangle numbers:
    1: 1
    3: 1, 3
    6: 1, 2, 3, 6
    10: 1, 2, 5, 10
    15: 1, 3, 5, 15
    21: 1, 3, 7, 21
    28: 1, 2, 4, 7, 14, 28

    We can see that 28 is the first triangle number to have over five divisors.

    What is the value of the first triangle number to have over five hundred divisors?

Solution Approach:
    Use number theory and prime factorization to efficiently count divisors.
    Recognize that the nth triangle number is n*(n+1)/2. Factor n and n+1 separately,
    combine divisor counts, and check for the first exceeding 500 divisors. Use
    efficient trial division or a sieve for factoring. Aim for O(n log n) or better.

Answer: ...
URL: https://projecteuler.net/problem=12
"""
from __future__ import annotations

from typing import Any

from euler_solver.c_libs.py_wrappers.primes import num_factors
from euler_solver.logger import logger
from euler_solver.setup import evaluate, register_solution

euler_problem: int = 12
framework_version: str = '0.2.1'
test_cases: list[dict[str, Any]] = [
    {'category': 'dev', 'input': {'num_divisors': 5}},
    {'category': 'main', 'input': {'num_divisors': 500}}
]


@register_solution(euler_problem=euler_problem, max_test_case_index=None)
def solve_highly_divisible_triangular_number_p0012_s0(*, num_divisors: int) -> int: ...

@register_solution(euler_problem=euler_problem, max_test_case_index=None)
def solve_highly_divisible_triangular_number_p0012_s1(*, num_divisors: int) -> int: ...

if __name__ == '__main__':
    logger.setLevel('ERROR')
    raise SystemExit(evaluate(euler_problem=euler_problem, time_out_in_seconds=300, mode='evaluate'))
