#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Project Euler Problem 101: Optimum Polynomial.

Problem Statement:
    If we are presented with the first k terms of a sequence it is impossible to
    say with certainty the value of the next term, as there are infinitely many
    polynomial functions that can model the sequence.

    As an example, let us consider the sequence of cube numbers. This is defined
    by the generating function, u_n = n^3: 1, 8, 27, 64, 125, 216, ...

    Suppose we were only given the first two terms of this sequence. Working on
    the principle that "simple is best" we should assume a linear relationship
    and predict the next term to be 15 (common difference 7). Even if we were
    presented with the first three terms, by the same principle of simplicity,
    a quadratic relationship should be assumed.

    We shall define OP(k, n) to be the nth term of the optimum polynomial generating
    function for the first k terms of a sequence. It should be clear that OP(k, n)
    will accurately generate the terms of the sequence for n <= k, and potentially
    the first incorrect term (FIT) will be OP(k, k+1); in which case we shall call
    it a bad OP (BOP).

    As a basis, if we were only given the first term of sequence, it would be most
    sensible to assume constancy; that is, for n >= 2, OP(1, n) = u_1.

    Hence we obtain the following OPs for the cubic sequence:

        OP(1, n) = 1             -> 1, 1, 1, 1, ...
        OP(2, n) = 7n - 6        -> 1, 8, 15, ...
        OP(3, n) = 6n^2 - 11n + 6 -> 1, 8, 27, 58, ...
        OP(4, n) = n^3           -> 1, 8, 27, 64, 125, ...

    Clearly no BOPs exist for k >= 4.

    By considering the sum of FITs generated by the BOPs (indicated in red above),
    we obtain 1 + 15 + 58 = 74.

    Consider the following tenth degree polynomial generating function:
        u_n = 1 - n + n^2 - n^3 + n^4 - n^5 + n^6 - n^7 + n^8 - n^9 + n^10.

    Find the sum of FITs for the BOPs.

Solution Approach:
    Use polynomial interpolation (e.g. Lagrange interpolation) to find the unique
    polynomial of degree k-1 that fits the first k terms. Calculate OP(k, k+1)
    for each k from 1 to the degree, summing the FITs where OP(k, k+1) does not
    match the actual sequence term. This involves efficient polynomial math and
    summation. Expected complexity depends on degree (10), easily feasible with
    number theory and interpolation in polynomial rings.

Answer: ...
URL: https://projecteuler.net/problem=101
"""
from __future__ import annotations

from typing import Any

from euler_solver.logger import logger
from euler_solver.setup import evaluate, register_solution

euler_problem: int = 101
framework_version: str = '0.2.1'
test_cases: list[dict[str, Any]] = [
    {'category': 'preliminary', 'input': {'polynomial_coefficients': [0, 0, 0, 1]}},
    {'category': 'main', 'input': {'polynomial_coefficients': [1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1]}}
]


@register_solution(euler_problem=euler_problem, max_test_case=None)
def solve_optimum_polynomial_p0101_s0(*, polynomial_coefficients: list) -> int: ...

@register_solution(euler_problem=euler_problem, max_test_case=None)
def solve_optimum_polynomial_p0101_s1(*, polynomial_coefficients: list) -> int: ...

@register_solution(euler_problem=euler_problem, max_test_case=None)
def solve_optimum_polynomial_p0101_s2(*, polynomial_coefficients: list) -> int: ...

if __name__ == '__main__':
    logger.setLevel('ERROR')
    raise SystemExit(evaluate(euler_problem=euler_problem, time_out_in_seconds=300, mode='evaluate'))
