#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Project Euler Problem 288: An Enormous Factorial.

Problem Statement:
    For any prime p the number N(p, q) is defined by
    N(p, q) = sum_{n = 0}^q T_n * p^n
    with T_n generated by the following random number generator:

    S_0 = 290797
    S_{n + 1} = S_n^2 mod 50515093
    T_n = S_n mod p

    Let Nfac(p, q) be the factorial of N(p, q).
    Let NF(p, q) be the number of factors p in Nfac(p, q).

    You are given that NF(3,10000) mod 3^20 = 624955285.

    Find NF(61, 10^7) mod 61^10.

URL: https://projecteuler.net/problem=288
"""
from typing import Any

euler_problem: int = 288
framework_version: str = "0.0.1"
test_cases: list[dict[str, Any]] = [
    {'category': 'dev', 'input': {'p': 3, 'q': 10000}, 'answer': None},
    {'category': 'main', 'input': {'p': 61, 'q': 10000000}, 'answer': None},
]
encrypted: str = (
    'uWCIIWEsehuIOZcmFiI+7PUxDgJugU9CBm2prFw/1ofRCpRMHL8r6LnYZ3IG97pK8/3j3EiQ/dL5tH+/'
    'A2baVuTn0iC+7wCX7i2n7OXZW69ArWrz3pHedSs/U6Z8jvE+4Ffy2l4BMntQebBXVj8Isd/zuny4YMHz'
    'ZAyWpu3zD/PID44CNDi+gYTv9gBF+QK2jYhZZrm8SkEegiGZAptebdTegas5TtKCGPOvaPzD7BhsdAA0'
    'xsCs9W5/9l/1/lCxNc5o2IcvQOnpxhZtKcXC9qloeq2+vdqxhcA1Bnoz+pj97gWp3wzeJ551SLVvoQvX'
    'f93lqhoS6LHjN3FrL+2pyFsCF/PX2zB02V9wnlm3JKTW5Kr+Y2eVfMXdMTUCOgcfqRhHXHjf1K8fk/it'
    'Ewz7pzCZFW56zwnx/bhhg8bf1jtpPQu6TYjFKiPtFzOe2D9ZAQxP5jeuVHZoVAOs5SuhEF5UKsq+YuSF'
    'n/NCg6d17oPHEY4lUh6CoDmU9vWlyn1Aj1aC/8HGVo/E3tVJnZgk0+xW2zsQ4izTGPsBoiF0yvvTuZFV'
    'tFhfMM0Q0ziYCdcexy+8y+cyT+AH4pHa0SuPKh2IeKljF432cCyUix+y28+d9NQ+aZf7XYkv5jH9Z9sZ'
    'EHq0c2EFzMKzX3jwoCaJ3V4McglWWjNigw2tlG5pDEb+yCbaHJVYvKuJGDHwdz62TYAytaUFC1f45FcH'
    'd9s0uw3MDJlhgSSFnyvpm+IoS+8NKigESc/GJ0WRDV/6vABuI1snLQn//DTbuIbTADQ5eBNJ6E6SOD/8'
    'rmHNbbEBd1bFku73dRRprZYUHYfCHWKXMcYXtXt8ImL+UZOgowYWSc1kmWhXPBs5kFNFm6zG2XfrjtIV'
    'EVsuyxoTCwqcTZSHAojSH7JDvgRUbywtr6YvX9huTxy+3jKt1AXxAtIobFEI7YPxtFKJPoDfSmH39Vvh'
    'ehqdUl8jfO5p5Hu9kupzddfnbGk6n0422F7MSzDedlUlTi/LPJ4z5RgkFWIC/YG0OuiFdAZWKCjqXs/y'
    'DutHhqXpkGFZNY3AS2aY8JufPbsQEe+FOFWUiddp+nTsN0lvYssW4643OwtrQoQLieGwm6AubTsb+w0Z'
    'qXxr1qKDm+aVSfsdsBPau8Da3pHUa8chk1HL8MSLjEOOZKzpU6JXtR6k4UCP490+lSwI0dRVwIRe5pBf'
    '30goDtPUdC2RblL2vfF/4CY3hXETeUnkEH/EykCcvIQ1V/GrPEIhyTOWoZg1M/XEz0bY7tXPgZFcCOc4'
    'dMJshLu3AKfO7KLZLprXwPZAVmkk1JuRJa/ws47eROyPg3V/ztPTxZvrx17lqWsc0nfS9P++HOEThux+'
    'c2O71NjDww1Ow+TOQwbveDKqyBcc21e/OQtgogeswMukQC93wHt2jNtwAnzi5z23gPfEIrXw69namP+K'
    'Tum+A7oqGBEc+3pCx+2gH88blBnF0ubNwrA3ls3SBEEr/vku9sSQgVo0TfCY+PYpcFA0R14FUwYjWcb4'
    'ypo+nYyRHGA+yE09cu2ZQ3jYuBfpAui7kA9i6n0Sh7gENLsfn2FmQfVg/4ljxsrZ7Ro66RkchaJPap5u'
    'kSD0lmtzAdoJBqsuU6vdTJDpJ8yqJ2GM+rD1p53eU+XnAEA66babFqlPCF1Glm7zgmp7QREwSIBIOkEh'
    'CEPUZFE0jQBZxRojW7fnobtC/XFuDMIx9mjPvAg80iiTd/NWz62FQ0JmSVAX2vm5Cn49IFqT+ymC49rI'
    'nF0vazxz7rd9CcOfB2rTyHsVQD9p41jz36EGuEComhT/5EZnci1af5o6OzdYkDUuU2U9gsIVg72D24nL'
    'Szalbju1IiIH5xToPEFzqoD0DfCHjO4c6WaIxB06gj8mKjM2Z8kBUDkdyWDM96VIf9cbMM74yH56Akec'
    'D979c0S/KVTCSj7eQYeatRMGyEyDte8fHywGMRVSl6Vy7GBm6dt+EP1zfJAoG65GqVptW9+6u8+EM0Zc'
    'l6rkL4R6AlaykWo+IJA2Oi4Mb8QYLefnBQkhbabyd1Kpp1wXC2VRiLMVPQukhYVjX+K8PPnp/4U8e2uI'
    'GiJ1MGPLS2JksVHcDxv/XmUNVHwqcfHuHfjn46X6kz1nbLkwlcMkhrxn4zwKh7wQiqArQRoHmOnYSkYW'
    'R3Q668yrfxnhEcYLePTXVoKZTpoYk2vRZIU8G4vi80tg4k6cm7pzM7dDhkSscjQ1/efH1givE3rXrkdD'
    'j530cj4U0GHQ+uwxfM99zGayHZjSghm5DkKcde65RastMKJxEMFFEOF/ntFrcY+7Fev+Jj9ETQSbvjDd'
    'UJqWiD1S3sh4Cb4pAZWxBNdgSTZuRcdHu9At0SKPkK6PvoNZSntGJXId+xmGh+zh9UOIHqlExe8irJjG'
    'm+8/uTSDlMyQODwiE1bAyZ7/MAwVCKe3OgdAEHjd3GHnHoEh1Kjb+oIo8prVdmelTjMDKRXpxwLk7KnV'
    'j2GO+2nICJH4G4jDlaqe/9jt8bqvfkKZbJXGEOUB9LHAqTGKfoZepIP83c2AeOsnD1tVM42Wp0JOtQ7p'
    'W/w717NhzhkeZAKx+y/pBI0o0nNeiTPREquHqC20mN2Fo9hOSrKklSAkcBrz3XwLeegUFlEgnTf9aUE1'
    'xRrj3WiHyMQ7s3uca2/bPw/SyzzMVxOYwVozPqNBByVcyo5IfW76DrsrR5n8hqhFIS7rJy/uyTFizgmf'
    'kQmXKDv3DMA='
)

if __name__ == '__main__':
    from euler_solver.framework import evaluate, logger
    logger.setLevel('ERROR')
    raise SystemExit(evaluate(euler_problem=euler_problem, time_out_in_seconds=300))
