#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Project Euler Problem 288: An Enormous Factorial.

Problem Statement:
    For any prime p the number N(p, q) is defined by
    N(p, q) = sum_{n = 0}^q T_n * p^n
    with T_n generated by the following random number generator:

    S_0 = 290797
    S_{n + 1} = S_n^2 mod 50515093
    T_n = S_n mod p

    Let Nfac(p, q) be the factorial of N(p, q).
    Let NF(p, q) be the number of factors p in Nfac(p, q).

    You are given that NF(3,10000) mod 3^20 = 624955285.

    Find NF(61, 10^7) mod 61^10.

Solution Approach:
    Use Legendre's formula and the base-p digit representation:
    v_p(N!) = (N - s_p(N)) / (p - 1), where s_p(N) is the sum of base-p digits.
    Here the base-p digits of N are exactly the sequence T_n for n = 0..q.
    Compute N mod p^{10} from the first 10 digits T_0..T_9 (higher terms vanish).
    Compute S = sum_{n=0}^q T_n by exploiting the periodicity of T_n via S_n.
    Accumulate full-cycle contributions to sum T_n instead of iterating to q.
    Finally compute (N - S) * inv(p-1) mod p^{10} (inv is modular inverse).
    Time: O(period + log q) expected; Space: O(1).

Answer: ...
URL: https://projecteuler.net/problem=288
"""
from __future__ import annotations

from typing import Any

from euler_solver.logger import logger
from euler_solver.setup import evaluate, register_solution

euler_problem: int = 288
framework_version: str = '0.2.1'
test_cases: list[dict[str, Any]] = [
    {'category': 'dev', 'input': {'p': 3, 'q': 10000}},
    {'category': 'main', 'input': {'p': 61, 'q': 10000000}}
]


@register_solution(euler_problem=euler_problem, max_test_case_index=None)
def solve_an_enormous_factorial_p0288_s0(*, p: int, q: int) -> int: ...

if __name__ == '__main__':
    logger.setLevel('ERROR')
    raise SystemExit(evaluate(euler_problem=euler_problem, time_out_in_seconds=300, mode='evaluate'))