#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Project Euler Problem 525: Rolling Ellipse.

Problem Statement:
    An ellipse E(a, b) is given at its initial position by equation:
    x^2 / a^2 + (y - b)^2 / b^2 = 1

    The ellipse rolls without slipping along the x axis for one complete turn.
    Interestingly, the length of the curve generated by a focus is independent
    from the size of the minor axis:
    F(a,b) = 2 π max(a,b)

    This is not true for the curve generated by the ellipse center. Let C(a, b) be
    the length of the curve generated by the center of the ellipse as it rolls
    without slipping for one turn.

    You are given C(2, 4) ≈ 21.38816906.

    Find C(1, 4) + C(3, 4). Give your answer rounded to 8 digits behind the decimal
    point in the form ab.cdefghij.

URL: https://projecteuler.net/problem=525
"""
from typing import Any

euler_problem: int = 525
framework_version: str = "0.0.1"
test_cases: list[dict[str, Any]] = [
    {'category': 'main', 'input': {}, 'answer': None},
]
encrypted: str = (
    'DrZc1ItjJ9M+3OGKI78t+PBO3MCyq0QPKKCVir8bJn5GaPNCAo0gkcAoCm+tpziILXn7Wbp1cYs0hYp4'
    '+nC8jOMGXYjbu4nVftpN1l7YDCmwYODTSczC154dx2URDIohsvOe5lNKUwP+O/ngaap2npzAXoBHaSda'
    'BaXYb4ukGDjpLj8T+m6axWoPtmUyCzs1QVoUQ4PMOCOvA6QJQxuYszXWrl+JOCT7GPwJNmRtLyIfuJL0'
    'dSHWICxIwLDnffo6posKnEJTYhwvdRCSNmXId0KY+UpyQHrBL8/1+A+79ekPBDyzkI8vWA99yu4PUrL2'
    'zdfUE9mwEUu4GYZmnvwJwS7co6VBHhcoCTR70P1Mt/g3t4mtYGfX2WLMM4UzSW9h/dxXdSp+jndF+niy'
    'u6w9qUgVkmlb6h7h+v559UAGeg+E4xcQGhWWEqBf7yrqfx87BuIhGCTFWzzJ1JH8ooWAAoXY8iPiIMf9'
    '10JyEmn+tW5dXFZ+bYVBgxXp3vxoqaV8Sa/huVJZix09Zr161n/SMGd47GfDDIf44zhLyvVSyL777wEq'
    '6qEw20adZATAJbb3N4I3AR0A5uHEu86gjWHNUY/k0dQieMZykuaLTdswXTMZnY1UyDp0S/bd49l21AQ+'
    '4475qA2VjW32yuJhHw60s8fJhAwDmM2L56VK2txzhwDuynUdxrjZFaMjn4X/Z9YHZmLlpBUija2nnqyu'
    'ie/GPs6CKCs2iL1AwvmRCZNlNusnj8JEJW7fsnQ5X+P0PI66RURsXojz8z0Sn8zPZQJ1c8/76+AePGS1'
    'mbnha07cqSamWvoNxStiiy1+ajmP7J2Zxp9Ht8/HE6rhypw7g00BsZLNIA7hacrrY9kZ/tERUHzpA79L'
    'MIlCTqSICMv8c8Gs0TE5ujQEcoIicPzJOLoEafV4PZ1kwARRgwd+HjgaoseDdN558bhnJv4hEa2dBu/e'
    '5JvGZI2jyHyDgkNUvoolav/FC4ampCxCaZuy2Zodwc0JYSvHp5gvvwgbP8d+pzUYncwqSjmnWyICH80A'
    'aKwcOLuvz/1zbc2Nh7coTyQWOqc/2c5UiJg9B+RofCqBylpnBYrx178mIulz408iONlnbpeetFpS46ZA'
    '68uOWPJOVdjhiFHkPKy/5sH75448IUMqfzJfafxW2Z8nnKqCmpFUDwA2yprvLptkIjl585cpGp41p6nJ'
    '43NKE9Ncf7pZUECSIh4F2YVdVPrUUhfY4CjHHfkhb2wsNY73TKlmKfOhfcW7HCmADT/9tc3nFEkUjrRt'
    'qxmDUbagpyNNMWTvHStHngCi95anQLWF6JU8VetvMyyUMAi3EjDBBhBfWqYDQMWF7h+V0dvVUhTOh95p'
    'IkWQVBSj7bSzRN/vhVFW7p0l8AGj7UqeXG4H4XyfUvzN0CvIXnqSww9rxP1gSTjG0HTKrC3Iwrz9CoqQ'
    '2jfIGw4cnbYHj9ozwQxdVwtxr2WfKfS/RO3g4sB2++yhuHGPC266Tw1KYcZ73maD8b4aq3VecFfndoz1'
    'immLCxNsoT3iHIMt0s6u/8zqB8TdQLaVCfUpcXONFixuqfyP8IJhNKwKVXq2YQkDjDCLJOvbQx1wi5dd'
    'tejh6PZ3qUGTfhINfdSYaMLw/FMp+jHifPwSpEhQz4pL5WvfziGQy2Ijx1AywviNLLhSWnKaCGjWIveh'
    'g0B1BcS5t4gK/CLklzyO2r1vJ4hC3tK4ykUiUy7/pbrAE22GAVQBhYmtna53KOLXC0ODTmZ8pzmjP7zB'
    'ZNGohV24UEEIvjRS5bshU0h2pzR8qcAODLGbDf+oMyqdJULsl+C6NBN5KIYTdDtdKWgUL92VZ6qPC7kp'
    '+/xMvXF6OzdRcEIRnPmlFjVE18BhFyMOXv4PvyVesN6TIAtyy2f9c6Sa9ae3lSZe/z9e1AfO7R2S6EN0'
    'CPS0SFuVD0apagHLGEI5JmDq1AUYH4fHMh5drGux5j5qMvNzcnuWVsVfRxNu372zdufml8PvI+d4wCw5'
    '/5lUEA2xWTWQCe88i42nj0SPNBPacE5PcSRUgyEb5K7GGGvFsWxbWW8x1MOd1g5I51oQv+r900HlT6nv'
    'AVx05E34gDGpHCQM+JIc2nQkxIq2g6rMBZxuV0rUQTfXz8dI0guyX2ZOU6mdBolb0bHTx0Sdfqm4yuvN'
    'yXXxOUafMAA12sDbbB3Gg8IaS9EEOfoZ94yHuk38kJK8FJabokyemM6XF1fQr+iFvMUONDoGt9aG1yLu'
    '2f5EO+PEt4CySC7SvwtE4eSnEA1twc9xtnzEOZ+lqm/W8SqUjiwZflakdz0SLEG85juD7rW+wyfxnbGH'
    'S9FO6aOKnOPlFDKZTphLA4tTgC4vD5Ffur5Ti5Va82Uf813H3ifiAPwNrm0FJRjXgjgMsz4fncB/Gtsu'
    'JsR1P52riRzEnpd4s90NV4wXwlzER7K3mQO0ttq6OMYhXVzHJTCG/XG+heDrpZFcoUWlM0JEN8Z9BDj6'
    '3nB3VYAOi9FVrCh83zXvX9qRYQzceBoRIbMLT6JtVuCeu2VBC32hIPos2rObnWOLmne8x8PmayagzA/G'
    'qu/l6i9wSEWdooShQhH90w=='
)

if __name__ == '__main__':
    from euler_solver.framework import evaluate, logger
    logger.setLevel('ERROR')
    raise SystemExit(evaluate(euler_problem=euler_problem, time_out_in_seconds=300))
