#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Project Euler Problem 61: Cyclical Figurate Numbers.

Problem Statement:
    Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all
    figurate (polygonal) numbers and are generated by the following formulae:

    Triangle: P_3,n = n(n+1)/2        1, 3, 6, 10, 15, ...
    Square:   P_4,n = n^2             1, 4, 9, 16, 25, ...
    Pentagonal: P_5,n = n(3n-1)/2     1, 5, 12, 22, 35, ...
    Hexagonal:  P_6,n = n(2n-1)       1, 6, 15, 28, 45, ...
    Heptagonal: P_7,n = n(5n-3)/2     1, 7, 18, 34, 55, ...
    Octagonal:  P_8,n = n(3n-2)       1, 8, 21, 40, 65, ...

    The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting
    properties.

    1. The set is cyclic, in that the last two digits of each number is the first two digits
       of the next number (including the last number with the first).
    2. Each polygonal type: triangle (P_3,127=8128), square (P_4,91=8281), and pentagonal
       (P_5,44=2882), is represented by a different number in the set.
    3. This is the only set of 4-digit numbers with this property.

    Find the sum of the only ordered set of six cyclic 4-digit numbers for which each
    polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is
    represented by a different number in the set.

Solution Approach:
    Use combinatorial search with backtracking over sets of 4-digit polygonal numbers.
    Generate all 4-digit polygonal numbers for each type. Then search cyclic sequences of
    length six covering all polygonal types once. Use last two digits to first two digits
    matching property as a graph linking condition. Efficient pruning and caching will be
    important. The problem is a finite search with manageable complexity.

Answer: ...
URL: https://projecteuler.net/problem=61
"""
from __future__ import annotations

from typing import Any, Dict, Generator, List, Set, Tuple

from euler_solver.logger import logger
from euler_solver.maths.polynomial_numbers import FigurateNumber, p_gen
from euler_solver.setup import evaluate, register_solution, show_solution

euler_problem: int = 61
framework_version: str = '0.2.1'
test_cases: list[dict[str, Any]] = [
    {'category': 'preliminary', 'input': {'length': 2}},
    {'category': 'preliminary', 'input': {'length': 3}},
    {'category': 'preliminary', 'input': {'length': 4}},
    {'category': 'preliminary', 'input': {'length': 5}},
    {'category': 'main', 'input': {'length': 6}}
]


@register_solution(euler_problem=euler_problem, max_test_case=None)
def solve_cyclical_figurate_numbers_p0061_s0(*, length: int) -> list:
    ...

def find_cyclic_paths(start: int, current: int, path: List[int], visited: Set[int],
    ...

def verify_polygon_types(chain: Tuple[int, ...], p_numbers: Dict[FigurateNumber, Set[int]]) -> bool:
    ...

if __name__ == '__main__':
    logger.setLevel('ERROR')
    raise SystemExit(evaluate(euler_problem=euler_problem, time_out_in_seconds=300, mode='evaluate'))
