#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Project Euler Problem 61: Cyclical Figurate Numbers.

Problem Statement:
    Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all
    figurate (polygonal) numbers and are generated by the following formulae:

    Triangle: P_3,n = n(n+1)/2        1, 3, 6, 10, 15, ...
    Square:   P_4,n = n^2             1, 4, 9, 16, 25, ...
    Pentagonal: P_5,n = n(3n-1)/2     1, 5, 12, 22, 35, ...
    Hexagonal:  P_6,n = n(2n-1)       1, 6, 15, 28, 45, ...
    Heptagonal: P_7,n = n(5n-3)/2     1, 7, 18, 34, 55, ...
    Octagonal:  P_8,n = n(3n-2)       1, 8, 21, 40, 65, ...

    The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting
    properties.

    1. The set is cyclic, in that the last two digits of each number is the first two digits
       of the next number (including the last number with the first).
    2. Each polygonal type: triangle (P_3,127=8128), square (P_4,91=8281), and pentagonal
       (P_5,44=2882), is represented by a different number in the set.
    3. This is the only set of 4-digit numbers with this property.

    Find the sum of the only ordered set of six cyclic 4-digit numbers for which each
    polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is
    represented by a different number in the set.

Solution Approach:
    Use combinatorial search with backtracking over sets of 4-digit polygonal numbers.
    Generate all 4-digit polygonal numbers for each type. Then search cyclic sequences of
    length six covering all polygonal types once. Use last two digits to first two digits
    matching property as a graph linking condition. Efficient pruning and caching will be
    important. The problem is a finite search with manageable complexity.

Answer: ...
URL: https://projecteuler.net/problem=61
"""
from __future__ import annotations

from enum import Enum
from functools import wraps
from math import ceil, floor, sqrt
from typing import Any, Callable, Generator

from euler_solver.logger import logger
from euler_solver.setup import evaluate, register_solution, show_solution

euler_problem: int = 61
framework_version: str = '0.2.1'
test_cases: list[dict[str, Any]] = [
    {'category': 'dev', 'input': {'length': 2}},
    {'category': 'dev', 'input': {'length': 3}},
    {'category': 'dev', 'input': {'length': 4}},
    {'category': 'dev', 'input': {'length': 5}},
    {'category': 'main', 'input': {'length': 6}}
]


def n_is_positive_integer[T](func: Callable[[int], T]) -> Callable[[int], T]: ...

@n_is_positive_integer
def nth_triangle_number(n: int) -> int: ...

@n_is_positive_integer
def is_triangle_number(n: int) -> bool: ...

@n_is_positive_integer
def closest_triangle_number(n: int) -> tuple[float, int, int]: ...

@n_is_positive_integer
def nth_square_number(n: int) -> int: ...

@n_is_positive_integer
def is_square_number(n: int) -> bool: ...

@n_is_positive_integer
def closest_square_number(n: int) -> tuple[float, int, int]: ...

@n_is_positive_integer
def nth_pentagonal_number(n: int) -> int: ...

@n_is_positive_integer
def is_pentagonal_number(n: int) -> bool: ...

@n_is_positive_integer
def closest_pentagonal_number(n: int) -> tuple[float, int, int]: ...

@n_is_positive_integer
def nth_hexagonal_number(n: int) -> int: ...

@n_is_positive_integer
def is_hexagonal_number(n: int) -> bool: ...

@n_is_positive_integer
def closest_hexagonal_number(n: int) -> tuple[float, int, int]: ...

@n_is_positive_integer
def nth_heptagonal_number(n: int) -> int: ...

@n_is_positive_integer
def is_heptagonal_number(n: int) -> bool: ...

@n_is_positive_integer
def closest_heptagonal_number(n: int) -> tuple[float, int, int]: ...

@n_is_positive_integer
def nth_octagonal_number(n: int) -> int: ...

@n_is_positive_integer
def is_octagonal_number(n: int) -> bool: ...

@n_is_positive_integer
def closest_octagonal_number(n: int) -> tuple[float, int, int]: ...

class FigurateNumber(Enum):
    """Enumeration of all figurate (polygonal) numbers.

    Each enum value represents a specific polygonal number type,
    with the value indicating the number of sides in the polygon.
    For example, TRIANGLE=3 for 3-sided polygons, SQUARE=4 for 4-sided, etc.

    This enum provides a type-safe way to reference different figurate number types
    and is used as keys in the function mapping dictionaries (p_funcs, v_funcs, c_funcs).
    """
    TRIANGLE = 3
    SQUARE = 4
    PENTAGONAL = 5
    HEXAGONAL = 6
    HEPTAGONAL = 7
    OCTAGONAL = 8

    def __str__(self) -> str: ...

# dictionary mapping figurate number types to their nth calculation functions
p_funcs: dict[FigurateNumber, Callable[[int], int]] = {
    FigurateNumber.TRIANGLE: nth_triangle_number,
    FigurateNumber.SQUARE: nth_square_number,
    FigurateNumber.PENTAGONAL: nth_pentagonal_number,
    FigurateNumber.HEXAGONAL: nth_hexagonal_number,
    FigurateNumber.HEPTAGONAL: nth_heptagonal_number,
    FigurateNumber.OCTAGONAL: nth_octagonal_number,
}
# dictionary mapping figurate number types to their validation functions
v_funcs: dict[FigurateNumber, Callable[[int], bool]] = {
    FigurateNumber.TRIANGLE: is_triangle_number,
    FigurateNumber.SQUARE: is_square_number,
    FigurateNumber.PENTAGONAL: is_pentagonal_number,
    FigurateNumber.HEXAGONAL: is_hexagonal_number,
    FigurateNumber.HEPTAGONAL: is_heptagonal_number,
    FigurateNumber.OCTAGONAL: is_octagonal_number,
}
# dictionary mapping figurate number types to their closest-finding functions
c_funcs: dict[FigurateNumber, Callable[[int], tuple[float, int, int]]] = {
    FigurateNumber.TRIANGLE: closest_triangle_number,
    FigurateNumber.SQUARE: closest_square_number,
    FigurateNumber.PENTAGONAL: closest_pentagonal_number,
    FigurateNumber.HEXAGONAL: closest_hexagonal_number,
    FigurateNumber.HEPTAGONAL: closest_heptagonal_number,
    FigurateNumber.OCTAGONAL: closest_octagonal_number,
}


def p_gen(p_num: FigurateNumber, min_value: int = 0, max_value: int = 2 ** 32) -> Generator[int, None, None]: ...

@register_solution(euler_problem=euler_problem, max_test_case_index=None)
def solve_cyclical_figurate_numbers_p0061_s0(*, length: int) -> list: ...

def find_cyclic_paths(start: int, current: int, path: list[int], visited: set[int],
                      number_mapping: dict[int, list[int]], target_length: int) -> list[tuple[int, ...]]: ...

def verify_polygon_types(chain: tuple[int, ...], p_numbers: dict[FigurateNumber, set[int]]) -> bool: ...

if __name__ == '__main__':
    logger.setLevel('ERROR')
    raise SystemExit(evaluate(euler_problem=euler_problem, time_out_in_seconds=300, mode='evaluate'))
