#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# solution to Project Euler problem 288
# https://projecteuler.net/problem=288
# Answer: 
# Notes: 
import textwrap
from typing import Any, Dict

from euler.types import ProblemArgs, ProblemArgsList, SolutionProtocol, SolutionResult

problem_args_list: ProblemArgsList = [
    ProblemArgs(kwargs={}, answer=None, ),
]


def solution(**kwarg: Dict[str, Any]) -> SolutionResult:
    # enter the solution here
    raise NotImplementedError


# Explicitly annotate that this function implements SolutionProtocol
solution: SolutionProtocol

solution.__doc__ = textwrap.dedent(r'''
solution to Project Euler problem 288
https://projecteuler.net/problem=288

For any prime $p$ the number $N(p, q)$ is defined by
$N(p, q) = \sum_{n = 0}^q T_n \cdot p^n$

with $T_n$ generated by the following random number generator:

$S_0 = 290797$

$S_{n + 1} = S_n^2 \bmod 50515093$

$T_n = S_n \bmod p$


Let $\operatorname{Nfac}(p, q)$ be the factorial of $N(p, q)$.

Let $\operatorname{NF}(p, q)$ be the number of factors $p$ in $\operatorname{Nfac}(p, q)$.


You are given that $\operatorname{NF}(3,10000) \bmod 3^{20} = 624955285$.


Find $\operatorname{NF}(61, 10^7) \bmod 61^{10}$.

''').strip()

if __name__ == '__main__':
    # When run directly, evaluate the solution with test cases
    # Import required modules for evaluating the solution
    from euler.evaluator import evaluate_solution
    from euler.cli import parser
    from euler.logger import logger

    # Parse command-line arguments
    args = parser.parse_args()

    # Set the logging level based on command-line arguments
    logger.setLevel(args.log_level)

    # Extract timeout and maximum worker threads from arguments
    timeout, max_workers = args.timeout, args.max_workers

    # Run the solution with the specified test cases and parameters
    # This validates that our implementation gives the correct answers
    evaluate_solution(solution=solution, args_list=problem_args_list, timeout=timeout, max_workers=max_workers)