#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
  Project Euler Problem 61: Cyclical Figurate Numbers.

  Problem Statement:
    Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers
    are all figurate (polygonal) numbers and are generated by the following
    formulae:

    Triangle: P_3,n = n(n+1)/2      1, 3, 6, 10, 15, ...
    Square:   P_4,n = n^2            1, 4, 9, 16, 25, ...
    Pentagonal: P_5,n = n(3n-1)/2    1, 5, 12, 22, 35, ...
    Hexagonal: P_6,n = n(2n-1)       1, 6, 15, 28, 45, ...
    Heptagonal: P_7,n = n(5n-3)/2    1, 7, 18, 34, 55, ...
    Octagonal: P_8,n = n(3n-2)       1, 8, 21, 40, 65, ...

    The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three
    interesting properties.

    1. The set is cyclic, in that the last two digits of each number is the
       first two digits of the next number (including the last number with the
       first).
    2. Each polygonal type: triangle (P_3,127=8128), square (P_4,91=8281), and
       pentagonal (P_5,44=2882), is represented by a different number in the
       set.
    3. This is the only set of 4-digit numbers with this property.

    Find the sum of the only ordered set of six cyclic 4-digit numbers for which
    each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal,
    and octagonal, is represented by a different number in the set.

  Solution Approach:
    To solve this problem, consider each figurate number type and generate
    all 4-digit numbers for that type. Then, create a graph where each node
    represents a 4-digit figurate number, and edges connect nodes whose last two
    digits match the first two digits of another number. The task is to find a
    cycle of length six in this graph where each node corresponds to a unique
    figurate type. Use backtracking or search algorithms like depth-first search
    to explore these paths. Pay attention to uniqueness constraints on polygonal
    types and ensure all six types are included in the cycle.

  Test Cases:
    preliminary:
      length=2,
      answer=[1, 8181].

      length=3,
      answer=[1, 19291].

      length=4,
      answer=[2, [12524, 16160]].

      length=5,
      answer=[5, [12019, 15857, 18685, 19493, 26058]].

    main:
      length=6,
      answer=[1, 28684].


  Answer: [1, 28684]
  URL: https://projecteuler.net/problem=61
"""
from __future__ import annotations

from typing import Dict, Generator, List, Set, Tuple

from euler.logger import logger
from euler.maths.polynomial_numbers import FigurateNumber, p_gen
from euler.setup import TestCaseCategory, evaluate, register_solution, show_solution


@register_solution(euler_problem=61, test_case_category=TestCaseCategory.EXTENDED)
def cyclical_figurate_numbers(*, length: int) -> list:
    min_value: int = 10 ** 3
    max_value: int = 10 ** 4 - 1
    generator_funcs: Dict[FigurateNumber, Generator[int, None, None]] = {
        (p_num := FigurateNumber(n)): p_gen(p_num=FigurateNumber(p_num), min_value=min_value, max_value=max_value) for n
        in range(3, length + 3)}
    p_numbers: Dict[FigurateNumber, Set[int]] = {p_num: set(gen) for p_num, gen in generator_funcs.items()}
    number_to_next_graph: Dict[int, List[int]] = {n: list() for vals in p_numbers.values() for n in vals}
    for next_number in number_to_next_graph.keys():
        first_two_digits = next_number // 100
        for previous_number, successor_list in number_to_next_graph.items():
            if first_two_digits == previous_number % 100:
                successor_list.append(next_number)
    cyclic_paths: Set[Tuple[int, ...]] = set()
    for start_num in (k for k, v in number_to_next_graph.items() if v):
        for path in find_cyclic_paths(start_num, start_num, [start_num], {start_num}, number_to_next_graph, length):
            cyclic_paths.add(tuple(sorted(path)))
    valid_cyclic_paths: List[Tuple[int, ...]] = sorted(
            (path for path in cyclic_paths if verify_polygon_types(path, p_numbers)), key=sum)
    if show_solution():
        from pprint import pprint
        for valid_cyclic_path in valid_cyclic_paths:
            figurates = {n: tuple((str(k) for k, v in p_numbers.items() if n in v)) for n in valid_cyclic_path}
            print(f'length={length!r} {figurates}')
            pprint(figurates)
    return [(len_paths := len(valid_cyclic_paths)),
            sum(valid_cyclic_paths[0]) if len_paths == 1 else [sum(path) for path in valid_cyclic_paths]]


def find_cyclic_paths(start: int, current: int, path: List[int], visited: Set[int],
                      number_mapping: Dict[int, List[int]], target_length: int) -> List[tuple[int, ...]]:
    if len(path) == target_length:
        if current % 100 == start // 100:
            return [tuple(path[:])]
        return []
    result: List[tuple[int, ...]] = []
    for next_num in number_mapping.get(current, []):
        if next_num not in visited:
            path.append(next_num)
            visited.add(next_num)
            result.extend(find_cyclic_paths(start, next_num, path, visited, number_mapping, target_length))
            path.pop()
            visited.remove(next_num)
    return [tuple(r) for r in result]


def verify_polygon_types(chain: Tuple[int, ...], p_numbers: Dict[FigurateNumber, Set[int]]) -> bool:
    figurate_in_chain: Dict[FigurateNumber, List[int]] = {k: [n for n in chain if n in v] for k, v in p_numbers.items()}
    if any((len(n) == 0 for n in figurate_in_chain.values())):
        return False
    figurate_in_chain_rev: Dict[int, List[FigurateNumber]] = {}
    for k_f, v_f in figurate_in_chain.items():
        for n_f in v_f:
            figurate_in_chain_rev.setdefault(n_f, []).append(k_f)
    for k_r, v_r in figurate_in_chain_rev.items():
        if len(v_r) > 1:
            if all((len(f) == 1 for n_r in v_r if (f := figurate_in_chain[n_r]))):
                return False
    return True


if __name__ == '__main__':
    logger.setLevel('ERROR')
    raise SystemExit(evaluate(euler_problem=61, time_out_in_seconds=300, mode='evaluate'))
