#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
  Project Euler Problem 12: Highly Divisible Triangular Number.

  Problem Statement:
    The sequence of triangle numbers is generated by adding the natural numbers. So the 7th
    triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    Let us list the factors of the first seven triangle numbers:
    1: 1
    3: 1, 3
    6: 1, 2, 3, 6
    10: 1, 2, 5, 10
    15: 1, 3, 5, 15
    21: 1, 3, 7, 21
    28: 1, 2, 4, 7, 14, 28

    We can see that 28 is the first triangle number to have over five divisors.

    What is the value of the first triangle number to have over five hundred divisors?

  Solution Approach:
    To solve this problem, start by generating triangle numbers using the formula
    n x (n + 1) / 2, where n is a natural number.

    For each triangle number, compute the number of its divisors efficiently. Instead of
    checking all numbers up to the triangle number itself, use prime factorization to find
    the divisor count. Recall that the number of divisors of a number can be calculated
    from its prime factorization exponents.

    Increase n incrementally, generate the triangle number, and count its divisors until
    finding the first triangle number whose number of divisors exceeds 500.

    Implementing an efficient divisor count and avoiding redundant computations will be
    key to solving the problem within reasonable time.

  Test Cases:
    preliminary:
      num_divisors=5,
      answer=28.

    main:
      num_divisors=500,
      answer=76576500.


  Answer: 76576500
  URL: https://projecteuler.net/problem=12
"""
from __future__ import annotations

from euler.logger import logger
from euler.setup import TestCaseCategory, evaluate, register_solution


def num_factors(n: int) -> int:
    return 1 + 2 * sum([1 for i in range(2, int(n ** 0.5) + 1) if n % i == 0]) - (1 if n % int(n ** 0.5) == 0 else 0)


@register_solution(euler_problem=12, test_case_category=TestCaseCategory.EXTENDED)
def highly_divisible_triangular_number(*, num_divisors: int) -> int:
    i, triangle_number = (1, 1)
    while num_factors(triangle_number) < num_divisors:
        i += 1
        triangle_number = i * (i + 1) // 2
    return triangle_number


if __name__ == '__main__':
    logger.setLevel('ERROR')
    raise SystemExit(evaluate(euler_problem=12, time_out_in_seconds=300, mode='evaluate'))
