#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Polygonal (Figurate) Number Functions

This module provides functions for working with different types of polygonal (figurate) numbers,
including calculating the nth number in each sequence, validating if a number belongs to a sequence,
and finding the closest polygonal number to a given value.

Mathematical Background:

1. Triangle Numbers: Represent the number of dots that can form an equilateral triangle.
   - Formula: n(n+1)/2
   - Sequence: 1, 3, 6, 10, 15, 21, 28, ...
   - Inverse: n is triangular if (-1 + sqrt(1 + 8n))/2 is an integer

2. Square Numbers: Represent the number of dots that form a square.
   - Formula: n²
   - Sequence: 1, 4, 9, 16, 25, 36, 49, ...
   - Inverse: n is a square if sqrt(n) is an integer

3. Pentagonal Numbers: Represent the number of dots that form a regular pentagon.
   - Formula: n(3n-1)/2
   - Sequence: 1, 5, 12, 22, 35, 51, 70, ...
   - Inverse: n is pentagonal if (1 + sqrt(1 + 24n))/6 is an integer

4. Hexagonal Numbers: Represent the number of dots that form a regular hexagon.
   - Formula: n(2n-1)
   - Sequence: 1, 6, 15, 28, 45, 66, 91, ...
   - Inverse: n is hexagonal if (1 + sqrt(1 + 8n))/4 is an integer

5. Heptagonal Numbers: Represent the number of dots that form a regular heptagon.
   - Formula: n(5n-3)/2
   - Sequence: 1, 7, 18, 34, 55, 81, 112, ...
   - Inverse: n is heptagonal if (3 + sqrt(9 + 40n))/10 is an integer

6. Octagonal Numbers: Represent the number of dots that form a regular octagon.
   - Formula: n(3n-2)
   - Sequence: 1, 8, 21, 40, 65, 96, 133, ...
   - Inverse: n is octagonal if (2 + sqrt(4 + 12n))/6 is an integer

For each figurate number type, this module provides three utils functions:
- nth_*_number: Calculate the nth number in the sequence (e.g., nth_triangle_number)
- is_*_number: Check if a number belongs to the sequence (e.g., is_square_number)
- closest_*_number: Find the closest numbers in the sequence to a given value (e.g., closest_pentagonal_number)

Additionally, the module provides:
- A FigurateNumber enum for type-safe references to different figurate number types
- Dictionary mappings (p_funcs, v_funcs, c_funcs) from figurate number types to their respective functions
- A p_gen generator function to efficiently generate figurate numbers within a range
- A comprehensive test suite in the main() function

All functions that require positive integer inputs include validation through the n_is_positive_integer decorator.
"""
from enum import Enum
from functools import wraps
from math import ceil, floor, sqrt
from typing import Callable, Dict, Generator, Tuple

from euler_solver.logger import logger

__all__ = [
    'nth_triangle_number', 'is_triangle_number', 'closest_triangle_number',
    'nth_square_number', 'is_square_number', 'closest_square_number',
    'nth_pentagonal_number', 'is_pentagonal_number', 'closest_pentagonal_number',
    'nth_hexagonal_number', 'is_hexagonal_number', 'closest_hexagonal_number',
    'nth_heptagonal_number', 'is_heptagonal_number', 'closest_heptagonal_number',
    'nth_octagonal_number', 'is_octagonal_number', 'closest_octagonal_number',
    'p_funcs', 'v_funcs', 'c_funcs', 'p_gen', 'FigurateNumber', 'NumberError'
]


class NumberError(ValueError):
    """Exception raised when an invalid number is encountered."""
    pass


def n_is_positive_integer[T](func: Callable[[int], T]) -> Callable[[int], T]:
    """Decorator to ensure 'n' parameter is a positive integer.

    Raises AssertionError if n is not a positive integer.
    """

    @wraps(func)
    def wrapper(n: int) -> T:
        if isinstance(n, int) and n > 0:
            return func(n)
        else:
            raise NumberError(f"'n' must be a positive integer, got {n}")

    return wrapper


@n_is_positive_integer
def nth_triangle_number(n: int) -> int:
    """Calculate the nth triangle number.

    Formula: n * (n + 1) / 2

    Args:
        n: A positive integer

    Returns:
        The nth triangle number
    """
    return (n * (n + 1)) // 2


@n_is_positive_integer
def is_triangle_number(n: int) -> bool:
    """Check if a given number is a triangle number.

    Uses the formula: x = (-1 + sqrt(1 + 8n))/2
    If x is an integer, n is a triangle number.

    Args:
        n: A positive integer to check

    Returns:
        True if n is a triangle number, False otherwise
    """
    return ((-1 + sqrt(1 + 8 * n)) / 2).is_integer()


@n_is_positive_integer
def closest_triangle_number(n: int) -> Tuple[float, int, int]:
    """Find the closest triangle numbers to a given value.

    Uses the inverse formula: x = (-1 + sqrt(1 + 8n))/2
    to find the index that would generate the given number if it were triangular,
    then returns that index and the triangle numbers generated by its floor and ceiling.

    Args:
        n: A positive integer to find closest triangle numbers to

    Returns:
        A tuple containing:
        - The float index that would generate n if it were a triangle number
        - The largest triangle number less than or equal to n
        - The smallest triangle number greater than or equal to n
    """
    return (i := (-1 + sqrt(1 + 8 * n)) / 2), nth_triangle_number(floor(i)), nth_triangle_number(ceil(i))


@n_is_positive_integer
def nth_square_number(n: int) -> int:
    """Calculate the nth square number.

    Formula: n²

    Args:
        n: A positive integer

    Returns:
        The nth square number
    """
    return n ** 2


@n_is_positive_integer
def is_square_number(n: int) -> bool:
    """Check if a given number is a square number.

    A number is a square number if its square root is an integer.

    Args:
        n: A positive integer to check

    Returns:
        True if n is a square number, False otherwise
    """
    return sqrt(n).is_integer()


@n_is_positive_integer
def closest_square_number(n: int) -> Tuple[float, int, int]:
    """Find the closest square numbers to a given value.

    Uses the inverse formula: x = sqrt(n)
    to find the index that would generate the given number if it were square,
    then returns that index and the square numbers generated by its floor and ceiling.

    Args:
        n: A positive integer to find closest square numbers to

    Returns:
        A tuple containing:
        - The float index that would generate n if it were a square number
        - The largest square number less than or equal to n
        - The smallest square number greater than or equal to n
    """
    return (i := sqrt(n)), nth_square_number(floor(i)), nth_square_number(ceil(i))


@n_is_positive_integer
def nth_pentagonal_number(n: int) -> int:
    """Calculate the nth pentagonal number.

    Formula: n * (3n - 1) / 2

    Args:
        n: A positive integer

    Returns:
        The nth pentagonal number
    """
    return (n * (3 * n - 1)) // 2


@n_is_positive_integer
def is_pentagonal_number(n: int) -> bool:
    """Check if a given number is a pentagonal number.

    Uses the formula: x = (1 + sqrt(1 + 24n))/6
    If x is an integer, n is a pentagonal number.

    Args:
        n: A positive integer to check

    Returns:
        True if n is a pentagonal number, False otherwise
    """
    return ((1 + sqrt(1 + 24 * n)) / 6).is_integer()


@n_is_positive_integer
def closest_pentagonal_number(n: int) -> Tuple[float, int, int]:
    """Find the closest pentagonal numbers to a given value.

    Uses the inverse formula: x = (1 + sqrt(1 + 24n))/6
    to find the index that would generate the given number if it were pentagonal,
    then returns that index and the pentagonal numbers generated by its floor and ceiling.

    Args:
        n: A positive integer to find closest pentagonal numbers to

    Returns:
        A tuple containing:
        - The float index that would generate n if it were a pentagonal number
        - The largest pentagonal number less than or equal to n
        - The smallest pentagonal number greater than or equal to n
    """
    return (i := (1 + sqrt(1 + 24 * n)) / 6), nth_pentagonal_number(floor(i)), nth_pentagonal_number(ceil(i))


@n_is_positive_integer
def nth_hexagonal_number(n: int) -> int:
    """Calculate the nth hexagonal number.

    Formula: n * (2n - 1)

    Args:
        n: A positive integer

    Returns:
        The nth hexagonal number
    """
    return n * (2 * n - 1)


@n_is_positive_integer
def is_hexagonal_number(n: int) -> bool:
    """Check if a given number is a hexagonal number.

    Uses the formula: x = (1 + sqrt(1 + 8n))/4
    If x is an integer, n is a hexagonal number.

    Args:
        n: A positive integer to check

    Returns:
        True if n is a hexagonal number, False otherwise
    """
    return ((1 + sqrt(1 + 8 * n)) / 4).is_integer()


@n_is_positive_integer
def closest_hexagonal_number(n: int) -> Tuple[float, int, int]:
    """Find the closest hexagonal numbers to a given value.

    Uses the inverse formula: x = (1 + sqrt(1 + 8n))/4
    to find the index that would generate the given number if it were hexagonal,
    then returns that index and the hexagonal numbers generated by its floor and ceiling.

    Args:
        n: A positive integer to find closest hexagonal numbers to

    Returns:
        A tuple containing:
        - The float index that would generate n if it were a hexagonal number
        - The largest hexagonal number less than or equal to n
        - The smallest hexagonal number greater than or equal to n
    """
    return (i := (1 + sqrt(1 + 8 * n)) / 4), nth_hexagonal_number(floor(i)), nth_hexagonal_number(ceil(i))


@n_is_positive_integer
def nth_heptagonal_number(n: int) -> int:
    """Calculate the nth heptagonal number.

    Formula: n * (5n - 3) / 2

    Args:
        n: A positive integer

    Returns:
        The nth heptagonal number
    """
    return (n * (5 * n - 3)) // 2


@n_is_positive_integer
def is_heptagonal_number(n: int) -> bool:
    """Check if a given number is a heptagonal number.

    Uses the formula: x = (3 + sqrt(9 + 40n))/10
    If x is an integer, n is a heptagonal number.

    Args:
        n: A positive integer to check

    Returns:
        True if n is a heptagonal number, False otherwise
    """
    return ((3 + sqrt(9 + 40 * n)) / 10).is_integer()


@n_is_positive_integer
def closest_heptagonal_number(n: int) -> Tuple[float, int, int]:
    """Find the closest heptagonal numbers to a given value.

    Uses the inverse formula: x = (3 + sqrt(9 + 40n))/10
    to find the index that would generate the given number if it were heptagonal,
    then returns that index and the heptagonal numbers generated by its floor and ceiling.

    Args:
        n: A positive integer to find closest heptagonal numbers to

    Returns:
        A tuple containing:
        - The float index that would generate n if it were a heptagonal number
        - The largest heptagonal number less than or equal to n
        - The smallest heptagonal number greater than or equal to n
    """
    return (i := (3 + sqrt(9 + 40 * n)) / 10), nth_heptagonal_number(floor(i)), nth_heptagonal_number(ceil(i))


@n_is_positive_integer
def nth_octagonal_number(n: int) -> int:
    """Calculate the nth octagonal number.

    Formula: n * (3n - 2)

    Args:
        n: A positive integer

    Returns:
        The nth octagonal number
    """
    return n * (3 * n - 2)


@n_is_positive_integer
def is_octagonal_number(n: int) -> bool:
    """Check if a given number is an octagonal number.

    Uses the formula: x = (2 + sqrt(4 + 12n))/6
    If x is an integer, n is an octagonal number.

    Args:
        n: A positive integer to check

    Returns:
        True if n is an octagonal number, False otherwise
    """
    return ((2 + sqrt(4 + 12 * n)) / 6).is_integer()


@n_is_positive_integer
def closest_octagonal_number(n: int) -> Tuple[float, int, int]:
    """Find the closest octagonal numbers to a given value.

    Uses the inverse formula: x = (2 + sqrt(4 + 12n))/6
    to find the index that would generate the given number if it were octagonal,
    then returns that index and the octagonal numbers generated by its floor and ceiling.

    Args:
        n: A positive integer to find closest octagonal numbers to

    Returns:
        A tuple containing:
        - The float index that would generate n if it were an octagonal number
        - The largest octagonal number less than or equal to n
        - The smallest octagonal number greater than or equal to n
    """
    return (i := (2 + sqrt(4 + 12 * n)) / 6), nth_octagonal_number(floor(i)), nth_octagonal_number(ceil(i))


class FigurateNumber(Enum):
    """Enumeration of all figurate (polygonal) numbers.

    Each enum value represents a specific polygonal number type,
    with the value indicating the number of sides in the polygon.
    For example, TRIANGLE=3 for 3-sided polygons, SQUARE=4 for 4-sided, etc.

    This enum provides a type-safe way to reference different figurate number types
    and is used as keys in the function mapping dictionaries (p_funcs, v_funcs, c_funcs).
    """
    TRIANGLE = 3
    SQUARE = 4
    PENTAGONAL = 5
    HEXAGONAL = 6
    HEPTAGONAL = 7
    OCTAGONAL = 8

    def __str__(self) -> str:
        """Return the enum member as a title-cased string."""
        return self.name.title()


# Dictionary mapping figurate number types to their nth calculation functions
p_funcs: Dict[FigurateNumber, Callable[[int], int]] = {
    FigurateNumber.TRIANGLE: nth_triangle_number,
    FigurateNumber.SQUARE: nth_square_number,
    FigurateNumber.PENTAGONAL: nth_pentagonal_number,
    FigurateNumber.HEXAGONAL: nth_hexagonal_number,
    FigurateNumber.HEPTAGONAL: nth_heptagonal_number,
    FigurateNumber.OCTAGONAL: nth_octagonal_number,
}
# Dictionary mapping figurate number types to their validation functions
v_funcs: Dict[FigurateNumber, Callable[[int], bool]] = {
    FigurateNumber.TRIANGLE: is_triangle_number,
    FigurateNumber.SQUARE: is_square_number,
    FigurateNumber.PENTAGONAL: is_pentagonal_number,
    FigurateNumber.HEXAGONAL: is_hexagonal_number,
    FigurateNumber.HEPTAGONAL: is_heptagonal_number,
    FigurateNumber.OCTAGONAL: is_octagonal_number,
}
# Dictionary mapping figurate number types to their closest-finding functions
c_funcs: Dict[FigurateNumber, Callable[[int], Tuple[float, int, int]]] = {
    FigurateNumber.TRIANGLE: closest_triangle_number,
    FigurateNumber.SQUARE: closest_square_number,
    FigurateNumber.PENTAGONAL: closest_pentagonal_number,
    FigurateNumber.HEXAGONAL: closest_hexagonal_number,
    FigurateNumber.HEPTAGONAL: closest_heptagonal_number,
    FigurateNumber.OCTAGONAL: closest_octagonal_number,
}


def p_gen(p_num: FigurateNumber, min_value: int = 0, max_value: int = 2 ** 32) -> Generator[int, None, None]:
    """Generate polynomial numbers of a specific type within a range.

    Efficiently generates polynomial numbers by using the closest_*_number functions
    to determine the appropriate range of indices to check.

    Args:
        p_num: Type of polynomial (3=triangle, 4=square, 5=pentagonal, etc.)
        min_value: Minimum value to include in the sequence
        max_value: Maximum value to include in the sequence

    Yields:
        Each polynomial number within the specified range
    """
    p_func: Callable[[int], int] = p_funcs[p_num]
    c_func: Callable[[int], Tuple[float, int, int]] = c_funcs[p_num]
    start_num: int = floor(c_func(min_value)[0])
    stop_num: int = ceil(c_func(max_value)[0]) + 1
    for i in range(start_num, stop_num):
        if min_value <= (p := p_func(i)) <= max_value:
            yield p


def main() -> int:
    """Test and validate the figurate (polygonal) number calculations.

    This comprehensive validation function tests all aspects of the figurate number implementation:

    1. Calculating numbers using nth_*_number functions and verifying their correctness
    2. Validating numbers with is_*_number functions to ensure they properly identify figurate numbers
    3. Checking that integers between consecutive figurate numbers aren't incorrectly
       identified as figurate numbers (false positives)
    4. Testing the closest_*_number functions for accuracy with non-figurate numbers
    5. Verifying the p_gen generator function produces numbers within specified ranges

    The function outputs detailed diagnostic information during testing and
    maintains a count of failures encountered.

    Returns:
        int: The total number of validation failures encountered (0 if all tests pass)
    """
    failed: int = 0
    previous_p_number: int = 0
    for p_num, p_func, v_func, c_func in (
            (FigurateNumber.TRIANGLE, nth_triangle_number, is_triangle_number, closest_triangle_number),
            (FigurateNumber.SQUARE, nth_square_number, is_square_number, closest_square_number),
            (FigurateNumber.PENTAGONAL, nth_pentagonal_number, is_pentagonal_number, closest_pentagonal_number),
            (FigurateNumber.HEXAGONAL, nth_hexagonal_number, is_hexagonal_number, closest_hexagonal_number),
            (FigurateNumber.HEPTAGONAL, nth_heptagonal_number, is_heptagonal_number, closest_heptagonal_number),
            (FigurateNumber.OCTAGONAL, nth_octagonal_number, is_octagonal_number, closest_octagonal_number),
    ):
        for n in range(1, 121):
            p_number = p_func(n)
            if not (validated := v_func(p_number)):
                logger.error(f'calculated {p_func.__name__}({n})={p_number}, does not validate.')
                failed += 1
            logger.info(f'{p_func.__name__}({n})={p_number}; {v_func.__name__}({p_number})={validated}')
            if previous_p_number != 0:
                for not_a_p_number in range(previous_p_number + 1, p_number):
                    if v_func(not_a_p_number):
                        logger.error(f'{not_a_p_number=} also validates as {v_func.__name__}.')
                        failed += 1
                    i, previous_p, current_p = c_func(not_a_p_number)
                    if i > n or previous_p != previous_p_number or current_p != p_number:
                        logger.error(f'{c_func.__name__}({not_a_p_number})=({i:.2f}, {previous_p}, {current_p})')
                        failed += 1
            previous_p_number = p_number
        min_value: int = 1000
        max_value: int = 10000
        vals = list(p_gen(p_num, min_value=min_value, max_value=max_value))
        logger.info(f'{p_num} numbers: {vals}')
        if vals[0] < min_value or vals[-1] > max_value:
            logger.error(f'p_nums out of range: {vals}')
            failed += 1
    return failed


if __name__ == '__main__':
    """Entry point for figurate (polygonal) number validation script.

    When this module is run directly, it executes the comprehensive validation tests
    in the main() function and reports the results. The script exits with a status code
    equal to the number of test failures (0 indicates complete success).

    This allows the module to be used both as a library and as a standalone validation tool.
    """
    logger.setLevel('ERROR')
    print('Validating polynomial number calculations...')
    if (result := main()) != 0:
        print('Validation failed: Some polynomial number tests did not pass.')
    else:
        print('Validation passed: All polynomial number tests passed.')
    raise SystemExit(result)
