#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
  Project Euler Problem 101: Optimum Polynomial.

  Problem Statement:
    If we are presented with the first k terms of a sequence it is impossible to say
    with certainty the value of the next term, as there are infinitely many polynomial
    functions that can model the sequence.

    As an example, let us consider the sequence of cube numbers. This is defined by the
    generating function, u_n = n^3: 1, 8, 27, 64, 125, 216, ...

    Suppose we were only given the first two terms of this sequence. Working on the
    principle that "simple is best" we should assume a linear relationship and
    predict the next term to be 15 (common difference 7). Even if we were presented
    with the first three terms, by the same principle of simplicity, a quadratic
    relationship should be assumed.

    We shall define OP(k, n) to be the n-th term of the optimum polynomial generating
    function for the first k terms of a sequence. It should be clear that OP(k, n)
    will accurately generate the terms of the sequence for n <= k, and potentially
    the first incorrect term (FIT) will be OP(k, k+1); in which case we shall call it
    a bad OP (BOP).

    As a basis, if we were only given the first term of sequence, it would be most
    sensible to assume constancy; that is, for n >= 2, OP(1, n) = u_1.

    Hence we obtain the following OPs for the cubic sequence:

    OP(1, n) = 1  1, 1, 1, ...
    OP(2, n) = 7n - 6  1, 8, 15, ...
    OP(3, n) = 6n^2 - 11n + 6   1, 8, 27, 58, ...
    OP(4, n) = n^3  1, 8, 27, 64, 125, ...

    Clearly no BOPs exist for k >= 4.

    By considering the sum of FITs generated by the BOPs (indicated in red above), we
    obtain 1 + 15 + 58 = 74.

    Consider the following tenth degree polynomial generating function:
    u_n = 1 - n + n^2 - n^3 + n^4 - n^5 + n^6 - n^7 + n^8 - n^9 + n^{10}.

    Find the sum of FITs for the BOPs.

  Solution Approach:
    To solve this problem, begin by understanding the definition and behavior of
    optimum polynomials (OPs) for a given sequence.

    1. Define the sequence u_n using the given 10th degree polynomial.

    2. For each k from 1 to 10, extract the first k terms of the sequence generated
    by u_n.

    3. For each k, find the unique polynomial of degree k-1 that fits these k points
    exactly. This polynomial is the optimum polynomial OP(k, n).

    4. Compute the next term OP(k, k+1) predicted by this polynomial. If this value
    does not match u_{k+1}, it is the first incorrect term (FIT) and the polynomial
    is a bad OP (BOP).

    5. Sum all such FIT values across all k from 1 to 10.

    Use polynomial interpolation techniques, such as Lagrange interpolation or
    Newton's divided differences, to find the OP(k, n) for each k efficiently.

    Carefully handle the algebraic and numerical computations to avoid rounding
    errors or approximation issues.

    This approach leverages polynomial interpolation and sequence analysis to
    determine the FITs and their sum as required.

  Test Cases:
    preliminary:
      polynomial_coefficients=[0, 0, 0, 1],
      answer=74.

    main:
      polynomial_coefficients=[1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1],
      answer=None.


  Answer: None
  URL: https://projecteuler.net/problem=101
"""
from __future__ import annotations

from euler.logger import logger
from euler.setup import TestCaseCategory, evaluate, register_solution


@register_solution(euler_problem=101, test_case_category=TestCaseCategory.EXTENDED)
def optimum_polynomial(*, polynomial_coefficients: list) -> int:
    raise NotImplementedError()


if __name__ == '__main__':
    logger.setLevel('ERROR')
    raise SystemExit(evaluate(euler_problem=101, time_out_in_seconds=300, mode='evaluate'))
