#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Solution to Project Euler problem 29: Distinct powers

Problem Statement:
Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

2^2=4, 2^3=8, 2^4=16, 2^5=32
3^2=9, 3^3=27, 3^4=81, 3^5=243
4^2=16, 4^3=64, 4^4=256, 4^5=1024
5^2=25, 5^3=125, 5^4=625, 5^5=3125

If they are then placed in numerical order, with any repeats removed, we get the following
sequence of 15 distinct terms:
4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125.

How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

Solution Approach:
This implementation offers two strategies depending on the problem size:

1. For small inputs (max_number ≤ 100): A direct set comprehension approach that calculates
   all powers and automatically eliminates duplicates using Python's set data structure.

2. For larger inputs (max_number > 100): An optimized approach using prime factorization
   to avoid computing extremely large numbers. Each number is represented by its unique
   prime factorization signature, allowing us to identify duplicates without calculating
   the actual values.

The solution recognizes that certain combinations yield the same value (e.g., 4^2 = 2^4 = 16),
and accounts for these duplications by tracking the unique prime factorization patterns.

Test Cases:
- For max_number=5, the answer is 15
- For max_number=100, the answer is 9183
- For max_number=1000, the answer is 977358

URL: https://projecteuler.net/problem=29
Answer: 9183
"""
from euler.evaluator import evaluate_solutions, register_solution
from euler.types import ProblemArgs, ProblemArgsList
from euler.utils.primes import prime_factorization

# The problem number from Project Euler (https://projecteuler.net/problem=29)
problem_number: int = 29

# Define the test cases for validating the solution
problem_args_list: ProblemArgsList = [
    ProblemArgs(kwargs={'max_number': 5}, answer=15, ),
    ProblemArgs(kwargs={'max_number': 100}, answer=9183, ),
    ProblemArgs(kwargs={'max_number': 1000}, answer=977358, ),
]


@register_solution(problem_number=problem_number, args_list=problem_args_list)
def num_distinct_terms(*, max_number: int) -> int:
    """Calculate the number of distinct terms in the sequence of a^b.

    This function counts the unique values in the sequence generated by a^b where
    2 ≤ a ≤ max_number and 2 ≤ b ≤ max_number, using the most appropriate algorithm
    based on the input size.

    Args:
        max_number: The upper limit for both a and b (inclusive)

    Returns:
        The number of distinct terms in the sequence

    Example:
        >>> num_distinct_terms(max_number=5)
        15
        >>> num_distinct_terms(max_number=100)
        9183
    """
    if max_number > 100:
        # This approach would analyze the mathematical properties of powers to directly
        # count unique values without generating them all
        unique_powers = set()
        for a in range(2, max_number + 1):
            # Decompose 'a' into its prime factors to identify patterns
            prime_factors = prime_factorization(a)
            for b in range(2, max_number + 1):
                # Calculate a signature that uniquely identifies this power value without actually computing a^b
                signature = tuple((prime, power * b) for prime, power in prime_factors)
                unique_powers.add(signature)
        return len(unique_powers)
    else:
        # The simple approach is efficient enough for the problem constraints
        # For max_number=100, this runs in milliseconds on modern hardware
        return len({a ** b for a in range(2, max_number + 1) for b in range(2, max_number + 1)})


if __name__ == '__main__':
    # Run solution tests and exit with success (0) or failure (>0) status code
    raise SystemExit(evaluate_solutions(problem_number))
