#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Solution to Project Euler problem 45: Triangular, pentagonal, and hexagonal

Problem Statement:
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle: Tn = n(n+1)/2
1, 3, 6, 10, 15, ...

Pentagonal: Pn = n(3n-1)/2
1, 5, 12, 22, 35, ...

Hexagonal: Hn = n(2n-1)
1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

Solution Approach:
This solution uses mathematical properties to efficiently identify numbers that are
simultaneously triangular, pentagonal, and hexagonal:

1. We start by generating triangular numbers in sequence, beginning after T285
2. For each triangular number, we check if it's pentagonal using the formula:
   - A number is pentagonal if (1 + sqrt(24n + 1))/6 is an integer
3. Similarly, we check if it's hexagonal using the formula:
   - A number is hexagonal if (1 + sqrt(8n + 1))/4 is an integer
4. The first number that satisfies all three conditions is our answer

Rather than generating all three sequences, we use these mathematical shortcuts
to efficiently test if a number belongs to each sequence.

Test Cases:
- T285 = P165 = H143 = 40755 (known example from the problem)
- The next such number is 1533776805

URL: https://projecteuler.net/problem=45
Answer: 1533776805
"""

from euler.evaluator import evaluate_solutions, register_solution
from euler.types import ProblemArgs, ProblemArgsList

# The problem number from Project Euler (https://projecteuler.net/problem=45)
problem_number: int = 45

problem_args_list: ProblemArgsList = [
    ProblemArgs(
        kwargs={'n': 285},  # Start the search from a triangular number T_285
        answer=1533776805,  # The expected result (the next triangular-pentagonal-hexagonal number)
    ),
]


@register_solution(problem_number=problem_number, args_list=problem_args_list)
def next_triangular_pentagonal_hexagonal_number(n: int) -> int:
    """
    Find the next triangular number that is also pentagonal and hexagonal.

    This solution finds the next number after T_n that belongs to all three sequences:
    triangular, pentagonal, and hexagonal. It uses mathematical properties to efficiently
    test sequence membership rather than generating all three sequences.

    Args:
        n: The triangular index to start from (the function will find the next solution after T_n)
           The problem uses n=285 as the starting point

    Returns:
        The next triangular number that is also pentagonal and hexagonal

    Example:
        >>> next_triangular_pentagonal_hexagonal_number(285)
        1533776805

    Note:
        The problem statement confirms that T_285 = P_165 = H_143 = 40755, and we need to find
        the next such number that appears in all three sequences.
    """
    while n := n + 1:
        triangular_number = n * (n + 1) // 2  # triangular number
        if ((1 + 24 * triangular_number) ** 0.5) % 6 == 5.0:  # is a pentagonal number
            if ((1 + 8 * triangular_number) ** 0.5) % 4 == 3.0:  # is a hexagonal number
                return triangular_number
    else:
        raise ValueError('No solution found')


if __name__ == '__main__':
    # Run solution tests and exit with success (0) or failure (>0) status code
    raise SystemExit(evaluate_solutions(problem_number))
