#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Solution to Project Euler problem 44: Pentagon numbers

Problem Statement:
Pentagonal numbers are generated by the formula, Pn = n(3n-1)/2.
The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference
are pentagonal and D = |Pk - Pj| is minimized; what is the value of D?

Solution Approach:
This solution methodically searches for pairs of pentagonal numbers that satisfy the required conditions:
1. Generate pentagonal numbers in increasing order
2. For each new pentagonal number Pk, check all previous pentagonal numbers Pj
3. Test if both the sum (Pk + Pj) and difference (Pk - Pj) are pentagonal
4. Return the first (minimum) difference that satisfies all conditions

We use the mathematical property that a number p is pentagonal if and only if
(1 + sqrt(24p + 1))/6 is an integer, which allows us to efficiently check if
a number is pentagonal without generating the entire sequence.

Test Cases:
- The example in the problem shows that P4 + P7 = P8, but their difference is not pentagonal
- The answer is 5482660

URL: https://projecteuler.net/problem=44
Answer: 5482660
"""
from euler.evaluator import evaluate_solutions, register_solution
from euler.types import ProblemArgs, ProblemArgsList
from euler.utils.polynomial_numbers import is_pentagonal_number, nth_pentagonal_number

# The problem number from Project Euler (https://projecteuler.net/problem=44)
problem_number: int = 44

problem_args_list: ProblemArgsList = [
    ProblemArgs(
        kwargs={},  # No input parameters required for this problem
        answer=5482660,  # The expected minimum difference between pentagonal numbers
    ),
]


@register_solution(problem_number=problem_number, args_list=problem_args_list)
def min_difference_special_pentagonal_pairs() -> int:
    """
    Find the minimum difference between pentagonal numbers with special properties.

    This solution searches for the pair of pentagonal numbers (Pj, Pk) where:
    1. Their sum (Pj + Pk) is also a pentagonal number
    2. Their difference (Pk - Pj) is also a pentagonal number
    3. The difference D = |Pk - Pj| is minimized

    The algorithm works as follows:
    1. Incrementally generate pentagonal numbers P_i in ascending order
    2. For each new pentagonal number P_i, compare it with all previous pentagonal numbers P_j
    3. For each pair (P_i, P_j), check if both their sum (P_i + P_j) and difference (P_i - P_j)
       are pentagonal numbers using the efficient is_pentagonal_number() function
    4. Return the first difference found, which is guaranteed to be minimal since we
       generate pentagonal numbers in ascending order

    Returns:
        The minimum difference D between the pentagonal number pair that satisfies all conditions

    Time Complexity:
        O(n²) where n is the position of the pentagonal number in the solution pair,
        as we must check each new pentagonal number against all previous ones

    Example:
        >>> min_difference_special_pentagonal_pairs()
        5482660
    """
    i = 0
    while i := i + 1:
        pi = nth_pentagonal_number(i)
        for j in range(i - 1, 0, -1):
            pj = nth_pentagonal_number(j)
            if is_pentagonal_number(pi - pj) and is_pentagonal_number(pi + pj):
                return pi - pj
    else:
        raise ValueError('No solution found')


if __name__ == '__main__':
    # Run solution tests and exit with success (0) or failure (>0) status code
    raise SystemExit(evaluate_solutions(problem_number))
