#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r""" Solution to Project Euler problem 12: highly_divisible_triangular_number

Problem Statement:
  The sequence of triangle numbers is generated by adding the natural numbers. So
  the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten
  terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ... Let us list the factors
  of the first seven triangle numbers: \begin{align} \mathbf 1 &\colon 1\\ \mathbf
  3 &\colon 1,3\\ \mathbf 6 &\colon 1,2,3,6\\ \mathbf{10} &\colon 1,2,5,10\\
  \mathbf{15} &\colon 1,3,5,15\\ \mathbf{21} &\colon 1,3,7,21\\ \mathbf{28}
  &\colon 1,2,4,7,14,28 \end{align} We can see that 28 is the first triangle
  number to have over five divisors. What is the value of the first triangle
  number to have over five hundred divisors?

Solution Approach:
  Document the mathematical approach here.

URL: https://projecteuler.net/problem=12
Answer: None
"""
from __future__ import annotations

from euler.evaluator import evaluate_solutions, register_solution
from euler.setup import TestCase


def num_factors(n: int) -> int:
    """Calculate the number of factors (divisors) for a given integer.

    This function uses an optimized approach that only checks divisors up to the square root of n.
    For each divisor 'i' found below sqrt(n), we count both i and n/i as factors.
    This gives us a 2x speedup compared to checking all numbers from 1 to n.
    The 1 is added at the beginning (to count 1 as a factor), and n is counted implicitly.
    We handle perfect-squares specially by subtracting 1 when sqrt(n) is a divisor to avoid counting it twice.

    Args:
        n: A positive integer

    Returns:
        The total number of factors (divisors) of n
    """
    return 1 + 2 * sum([1 for i in range(2, int(n ** 0.5) + 1) if n % i == 0]) - (1 if n % int(n ** 0.5) == 0 else 0)


test_cases: list[TestCase] = [
    TestCase(
        answer=28,
        is_main_case=False,
        kwargs={'num_divisors': 5},
        solution_execution_time=None,
        solved=False
    ),
    TestCase(
        answer=76576500,
        is_main_case=False,
        kwargs={'num_divisors': 500},
        solution_execution_time=None,
        solved=False
    ),
]


# Register this function as a solution for problem #12
@register_solution(problem_number=12, test_cases=test_cases)
def highly_divisible_triangular_number(*, num_divisors: int) -> int:
    """
    Find the first triangle number with more than the specified number of divisors.

    This function iteratively generates triangle numbers and checks each one until
    finding the first that has more than the required number of divisors.

    Args:
        num_divisors: The minimum number of divisors required

    Returns:
        The first triangle number that has more than num_divisors divisors

    Algorithm:
        1. Start with the first triangle number (1)
        2. For each triangle number, count its divisors using the optimized num_factors function
        3. If the count exceeds num_divisors, return the current triangle number
        4. Otherwise, generate the next triangle number using the formula n(n+1)/2
        5. Repeat until a triangle number with sufficient divisors is found

    Examples:
        >>> highly_divisible_triangular_number(num_divisors=5)
        28  # First triangle number with over 5 divisors
        >>> highly_divisible_triangular_number(num_divisors=500)
        76576500  # First triangle number with over 500 divisors
    """
    i, triangle_number = 1, 1
    while num_factors(triangle_number) < num_divisors:
        i += 1
        triangle_number = i * (i + 1) // 2

    return triangle_number


if __name__ == '__main__':
    # Run solution tests and exit with success (0) or failure (>0) status code
    raise SystemExit(evaluate_solutions(12))
