#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r""" Solution to Project Euler problem 44: pentagon_numbers

Problem Statement:
  Pentagonal numbers are generated by the formula, P_n=n(3n-1)/2. The first ten
  pentagonal numbers are: 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ... It can be
  seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their difference, 70 - 22 =
  48, is not pentagonal. Find the pair of pentagonal numbers, P_j and P_k, for
  which their sum and difference are pentagonal and D = |P_k - P_j| is minimised;
  what is the value of D?

Solution Approach:
  Document the mathematical approach here.

URL: https://projecteuler.net/problem=44
Answer: None
"""
from __future__ import annotations

from euler.evaluator import evaluate_solutions, register_solution
from euler.maths.polynomial_numbers import is_pentagonal_number, nth_pentagonal_number
from euler.setup import TestCase

test_cases: list[TestCase] = [
    TestCase(
        answer=5482660,
        is_main_case=False,
        kwargs={},
        solution_execution_time=None,
        solved=False
    ),
]


# Register this function as a solution for problem #44
@register_solution(problem_number=44, test_cases=test_cases)
def pentagon_numbers() -> int:
    """
    Find the minimum difference between pentagonal numbers with special properties.

    This solution searches for the pair of pentagonal numbers (Pj, Pk) where:
    1. Their sum (Pj + Pk) is also a pentagonal number
    2. Their difference (Pk - Pj) is also a pentagonal number
    3. The difference D = |Pk - Pj| is minimized

    The algorithm works as follows:
    1. Incrementally generate pentagonal numbers P_i in ascending order
    2. For each new pentagonal number P_i, compare it with all previous pentagonal numbers P_j
    3. For each pair (P_i, P_j), check if both their sum (P_i + P_j) and difference (P_i - P_j)
       are pentagonal numbers using the efficient is_pentagonal_number() function
    4. Return the first difference found, which is guaranteed to be minimal since we
       generate pentagonal numbers in ascending order

    Returns:
        The minimum difference D between the pentagonal number pair that satisfies all conditions

    Time Complexity:
        O(n²) where n is the position of the pentagonal number in the solution pair,
        as we must check each new pentagonal number against all previous ones

    Example:
        >>> pentagon_numbers()
        5482660
    """
    i = 0
    while i := i + 1:
        pi = nth_pentagonal_number(i)
        for j in range(i - 1, 0, -1):
            pj = nth_pentagonal_number(j)
            if is_pentagonal_number(pi - pj) and is_pentagonal_number(pi + pj):
                return pi - pj
    else:
        raise ValueError('No solution found')


if __name__ == '__main__':
    # Run solution tests and exit with success (0) or failure (>0) status code
    raise SystemExit(evaluate_solutions(44))
