#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r""" Solution to Project Euler problem 2: even_fibonacci_numbers

Problem Statement:
  Each new term in the Fibonacci sequence is generated by adding the previous two
  terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13,
  21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose
  values do not exceed four million, find the sum of the even-valued terms.

Solution Approach:
  Document the mathematical approach here.

URL: https://projecteuler.net/problem=2
Answer: 4613732
"""
from __future__ import annotations

from typing import Generator

from euler.evaluator import evaluate_solutions, register_solution
from euler.setup import TestCase

test_cases: list[TestCase] = [
    TestCase(
        answer=10,
        is_main_case=False,
        kwargs={'max_limit': 10},
        solution_execution_time=None,
        solved=False
    ),
    TestCase(
        answer=44,
        is_main_case=False,
        kwargs={'max_limit': 100},
        solution_execution_time=None,
        solved=False
    ),
    TestCase(
        answer=4613732,
        is_main_case=True,
        kwargs={'max_limit': 4000000},
        solution_execution_time=None,
        solved=False
    ),
]


# Register this function as a solution for problem #2
@register_solution(problem_number=2, test_cases=test_cases)
def even_fibonacci_numbers(*, max_limit: int) -> int:
    """
    Calculates the sum of all even Fibonacci numbers below a specified maximum limit.

    Args:
        max_limit (int): The upper limit for the Fibonacci sequence. Only terms less than this value are considered.

    Returns:
        int: The sum of the even Fibonacci numbers below the given max_limit.
    """

    def even_fibonacci_numbers() -> Generator[int, None, None]:
        """
        Generates even Fibonacci numbers below the given max_limit using an optimized formula.

        This generator uses the fact that every third Fibonacci number
        is even, starting from the second Fibonacci term. The series
        of even Fibonacci numbers is: 2, 8, 34, ...

        Yields:
            int: The next even Fibonacci number below max_limit.
        """
        even_fib_a, even_fib_b = 2, 8  # Initialize the first two even Fibonacci numbers.
        while even_fib_a < max_limit:
            yield even_fib_a
            even_fib_a, even_fib_b = even_fib_b, 4 * even_fib_b + even_fib_a

    # Calculate and return the sum of all even Fibonacci numbers below max_limit.
    return sum(even_fibonacci_numbers())


if __name__ == '__main__':
    # Run solution tests and exit with success (0) or failure (>0) status code
    raise SystemExit(evaluate_solutions(2))
