#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r""" Solution to Project Euler problem 45: triangular_pentagonal_and_hexagonal

Problem Statement:
  Triangle, pentagonal, and hexagonal numbers are generated by the following
  formulae: Triangle   T_n=n(n+1)/2   1, 3, 6, 10, 15, ... Pentagonal   P_n=n(3n -
  1)/2   1, 5, 12, 22, 35, ... Hexagonal   H_n=n(2n - 1)   1, 6, 15, 28, 45, ...
  It can be verified that T_{285} = P_{165} = H_{143} = 40755. Find the next
  triangle number that is also pentagonal and hexagonal.

Solution Approach:
  Document the mathematical approach here.

URL: https://projecteuler.net/problem=45
Answer: None
"""
from __future__ import annotations

from euler.evaluator import evaluate_solutions, register_solution
from euler.setup import TestCase

test_cases: list[TestCase] = [
    TestCase(
        answer=1533776805,
        is_main_case=False,
        kwargs={'n': 285},
        solution_execution_time=None,
        solved=False
    ),
]


# Register this function as a solution for problem #45
@register_solution(problem_number=45, test_cases=test_cases)
def triangular_pentagonal_and_hexagonal(*, n: int) -> int:
    """
    Find the next triangular number that is also pentagonal and hexagonal.

    This solution finds the next number after T_n that belongs to all three sequences:
    triangular, pentagonal, and hexagonal. It uses mathematical properties to efficiently
    test sequence membership rather than generating all three sequences.

    Args:
        n: The triangular index to start from (the function will find the next solution after T_n)
           The problem uses n=285 as the starting point

    Returns:
        The next triangular number that is also pentagonal and hexagonal

    Example:
        >>> triangular_pentagonal_and_hexagonal(285)
        1533776805

    Note:
        The problem statement confirms that T_285 = P_165 = H_143 = 40755, and we need to find
        the next such number that appears in all three sequences.
    """
    while n := n + 1:
        triangular_number = n * (n + 1) // 2  # triangular number
        if ((1 + 24 * triangular_number) ** 0.5) % 6 == 5.0:  # is a pentagonal number
            if ((1 + 8 * triangular_number) ** 0.5) % 4 == 3.0:  # is a hexagonal number
                return triangular_number
    else:
        raise ValueError('No solution found')


if __name__ == '__main__':
    # Run solution tests and exit with success (0) or failure (>0) status code
    raise SystemExit(evaluate_solutions(45))
