#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r""" Solution to Project Euler problem 29: distinct_powers

Problem Statement:
  Consider all integer combinations of a^b for 2 \le a \le 5 and 2 \le b \le 5:
  \begin{matrix} 2^2=4, &2^3=8, &2^4=16, &2^5=32\\ 3^2=9, &3^3=27, &3^4=81,
  &3^5=243\\ 4^2=16, &4^3=64, &4^4=256, &4^5=1024\\ 5^2=25, &5^3=125, &5^4=625,
  &5^5=3125 \end{matrix} If they are then placed in numerical order, with any
  repeats removed, we get the following sequence of 15 distinct terms: 4, 8, 9,
  16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125. How many distinct terms
  are in the sequence generated by a^b for 2 \le a \le 100 and 2 \le b \le 100?

Solution Approach:
  Document the mathematical approach here.

URL: https://projecteuler.net/problem=29
Answer: None
"""
from __future__ import annotations

from euler.evaluator import evaluate_solutions, register_solution
from euler.maths.primes import prime_factorization
from euler.setup import TestCase

test_cases: list[TestCase] = [
    TestCase(
        answer=15,
        is_main_case=False,
        kwargs={'max_number': 5},
        solution_execution_time=None,
        solved=False
    ),
    TestCase(
        answer=9183,
        is_main_case=False,
        kwargs={'max_number': 100},
        solution_execution_time=None,
        solved=False
    ),
    TestCase(
        answer=977358,
        is_main_case=False,
        kwargs={'max_number': 1000},
        solution_execution_time=None,
        solved=False
    ),
]


# Register this function as a solution for problem #29
@register_solution(problem_number=29, test_cases=test_cases)
def distinct_powers(*, max_number: int) -> int:
    """Calculate the number of distinct terms in the sequence of a^b.

    This function counts the unique values in the sequence generated by a^b where
    2 ≤ a ≤ max_number and 2 ≤ b ≤ max_number, using the most appropriate algorithm
    based on the input size.

    Args:
        max_number: The upper limit for both a and b (inclusive)

    Returns:
        The number of distinct terms in the sequence

    Example:
        >>> distinct_powers(max_number=5)
        15
        >>> distinct_powers(max_number=100)
        9183
    """
    if max_number > 100:
        # This approach would analyze the mathematical properties of powers to directly
        # count unique values without generating them all
        unique_powers = set()
        for a in range(2, max_number + 1):
            # Decompose 'a' into its prime factors to identify patterns
            prime_factors = prime_factorization(a)
            for b in range(2, max_number + 1):
                # Calculate a signature that uniquely identifies this power value without actually computing a^b
                signature = tuple((prime, power * b) for prime, power in prime_factors)
                unique_powers.add(signature)
        return len(unique_powers)
    else:
        # The simple approach is efficient enough for the problem constraints
        # For max_number=100, this runs in milliseconds on modern hardware
        return len({a ** b for a in range(2, max_number + 1) for b in range(2, max_number + 1)})


if __name__ == '__main__':
    # Run solution tests and exit with success (0) or failure (>0) status code
    raise SystemExit(evaluate_solutions(29))
