#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r""" Solution to Project Euler problem 61: cyclical_figurate_numbers

Problem Statement:
  Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are
  all figurate (polygonal) numbers and are generated by the following formulae:
  Triangle   P_{3,n}=n(n+1)/2   1, 3, 6, 10, 15, ... Square   P_{4,n}=n^2   1, 4,
  9, 16, 25, ... Pentagonal   P_{5,n}=n(3n-1)/2   1, 5, 12, 22, 35, ... Hexagonal
   P_{6,n}=n(2n-1)   1, 6, 15, 28, 45, ... Heptagonal   P_{7,n}=n(5n-3)/2   1, 7,
  18, 34, 55, ... Octagonal   P_{8,n}=n(3n-2)   1, 8, 21, 40, 65, ... The ordered
  set of three 4-digit numbers: 8128, 2882, 8281, has three interesting
  properties. The set is cyclic, in that the last two digits of each number is the
  first two digits of the next number (including the last number with the first).
  Each polygonal type: triangle (P_{3,127}=8128), square (P_{4,91}=8281), and
  pentagonal (P_{5,44}=2882), is represented by a different number in the set.
  This is the only set of 4-digit numbers with this property. Find the sum of the
  only ordered set of six cyclic 4-digit numbers for which each polygonal type:
  triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is
  represented by a different number in the set.

Solution Approach:
  Document the mathematical approach here.

URL: https://projecteuler.net/problem=61
Answer: None
"""
from __future__ import annotations

from typing import Dict, Generator, List, Set, Tuple

from euler.evaluator import evaluate_solutions, register_solution, show_solution
from euler.maths.polynomial_numbers import FigurateNumber, p_gen
from euler.setup import TestCase

test_cases: list[TestCase] = [
    TestCase(
        answer=[1, 8181],
        is_main_case=False,
        kwargs={'length': 2},
        solution_execution_time=None,
        solved=False
    ),
    TestCase(
        answer=[1, 19291],
        is_main_case=False,
        kwargs={'length': 3},
        solution_execution_time=None,
        solved=False
    ),
    TestCase(
        answer=[2, [12524, 16160]],
        is_main_case=False,
        kwargs={'length': 4},
        solution_execution_time=None,
        solved=False
    ),
    TestCase(
        answer=[5, [12019, 15857, 18685, 19493, 26058]],
        is_main_case=False,
        kwargs={'length': 5},
        solution_execution_time=None,
        solved=False
    ),
    TestCase(
        answer=[1, 28684],
        is_main_case=False,
        kwargs={'length': 6},
        solution_execution_time=None,
        solved=False
    ),
]


# Register this function as a solution for problem #61
@register_solution(problem_number=61, test_cases=test_cases)
def cyclical_figurate_numbers(*, length: int) -> list:
    """
    Find cyclic sets of figurate numbers satisfying the problem constraints.

    This function implements the main solution algorithm to find cyclic sets of 4-digit
    figurate numbers where each figurate type is represented by a different number in the set.
    The function supports variable numbers of figurate types and returns both the count of
    valid sets found and either the sum of the single valid set or a list of sums for multiple sets.

    Args:
        length: The number of figurate types to include (also the length of the cyclic path)

    Returns:
        A tuple containing:
            - The number of valid cyclic sets found
            - Either an integer (the sum of the single valid set) or a list of integers (sums of multiple valid sets)

    Algorithm:
        1. Generate all 4-digit figurate numbers for each relevant type (triangle through octagonal)
        2. Construct a directed graph where edges connect numbers whose digits match the problem's
           cyclic condition (last two digits of one number = first two digits of the next)
        3. Use DFS with backtracking to find all possible cyclic paths of the required length
        4. Filter paths to ensure each figurate type is represented by a different number
        5. Return the count of valid paths and their sums

    Example:
        >>> cyclical_figurate_numbers(length=3)  # For 3 figurate types (triangle, square, pentagonal)
        (1, 19291)
        >>> cyclical_figurate_numbers(length=6)  # For all 6 figurate types (the main problem)
        (1, 28684)
    """
    min_value: int = 10 ** 3
    max_value: int = 10 ** 4 - 1
    generator_funcs: Dict[FigurateNumber, Generator[int, None, None]] = {
        (p_num := FigurateNumber(n)): p_gen(p_num=FigurateNumber(p_num), min_value=min_value, max_value=max_value)
        for n in range(3, length + 3)}
    p_numbers: Dict[FigurateNumber, Set[int]] = {p_num: set(gen) for p_num, gen in generator_funcs.items()}
    number_to_next_graph: Dict[int, List[int]] = {n: list() for vals in p_numbers.values() for n in vals}
    for next_number in number_to_next_graph.keys():
        first_two_digits = next_number // 100
        for previous_number, successor_list in number_to_next_graph.items():
            if first_two_digits == previous_number % 100:
                successor_list.append(next_number)
    cyclic_paths: Set[Tuple[int, ...]] = set()
    for start_num in (k for k, v in number_to_next_graph.items() if v):
        for path in find_cyclic_paths(start_num, start_num, [start_num], {start_num}, number_to_next_graph, length):
            cyclic_paths.add(tuple(sorted(path)))
    valid_cyclic_paths: List[Tuple[int, ...]] = sorted((path for path in cyclic_paths
                                                        if verify_polygon_types(path, p_numbers)), key=sum)
    if show_solution():
        from pprint import pprint
        for valid_cyclic_path in valid_cyclic_paths:
            figurates = {n: tuple(str(k) for k, v in p_numbers.items() if n in v) for n in valid_cyclic_path}
            print(f'{length=} {figurates}')
            pprint(figurates)
    return [len_paths := len(valid_cyclic_paths),
            sum(valid_cyclic_paths[0]) if len_paths == 1 else [sum(path) for path in valid_cyclic_paths]]


def find_cyclic_paths(start: int, current: int, path: List[int], visited: Set[int],
                      number_mapping: Dict[int, List[int]], target_length: int) -> List[tuple[int, ...]]:
    """
    Recursively find all cyclic paths of the specified length in the number graph.

    This function uses depth-first search with backtracking to find all possible cyclic
    paths that meet the following conditions:
    1. The path contains exactly target_length numbers
    2. Each number in the path connects to the next (last two digits match first two digits)
    3. The last number in the path connects back to the first number

    Args:
        start: The starting number in the cycle (needed to check if the last number connects back)
        current: The current number being processed
        path: The current path being built (list of numbers included so far)
        visited: Set of numbers already included in the current path
        number_mapping: A graph represented as an adjacency list, mapping each number to its possible successors
        target_length: The required length of valid paths

    Returns:
        A list of tuples, where each tuple is a valid cyclic path of the specified length

    Algorithm:
        1. Base case: If path length equals target_length, check if it forms a cycle
        2. Recursive case: For each unvisited successor of the current number:
           - Add it to the path and mark as visited
           - Recursively find paths from this new position
           - Backtrack by removing it from path and marking as unvisited
        3. Return all valid cyclic paths found
    """
    if len(path) == target_length:
        if current % 100 == start // 100:  # Check if last number connects to first
            return [tuple(path[:])]
        return []
    result: List[tuple[int, ...]] = []
    for next_num in number_mapping.get(current, []):
        if next_num not in visited:
            path.append(next_num)
            visited.add(next_num)
            result.extend(find_cyclic_paths(start, next_num, path, visited, number_mapping, target_length))
            path.pop()
            visited.remove(next_num)
    return [tuple(r) for r in result]


def verify_polygon_types(chain: Tuple[int, ...], p_numbers: Dict[FigurateNumber, Set[int]]) -> bool:
    """
    Verify that each figurate type is represented by a different number in the chain.

    This function checks if a cyclic chain of numbers satisfies the requirement that each
    figurate type (triangle, square, pentagonal, etc.) is represented by exactly one number
    in the chain, and that each number represents exactly one figurate type.

    Args:
        chain: A tuple of integers representing a potential solution
        p_numbers: A dictionary mapping figurate number types to a set of numbers for efficient membership testing

    Returns:
        True if the chain satisfies the polygon type requirements, False otherwise

    Algorithm:
        1. For each figurate type, identify which numbers in the chain belong to that type
        2. Verify that each figurate type is represented at least once
        3. Build a reverse mapping from numbers to their figurate types
        4. Check that each number belongs to at least one figurate type and that when a number
           belongs to multiple types, we can still assign each type to a different number

    Note:
        The problem requires each figurate type to be represented by a different number in the set,
        and this function ensures that this assignment is possible given the chain of numbers.
    """
    figurate_in_chain: Dict[FigurateNumber, List[int]] = {k: [n for n in chain if n in v] for k, v in p_numbers.items()}
    # Each figurate type must have one or more number
    if any(len(n) == 0 for n in figurate_in_chain.values()):
        return False

    # Build reverse mapping from numbers to figurate types
    figurate_in_chain_rev: Dict[int, List[FigurateNumber]] = {}
    for k_f, v_f in figurate_in_chain.items():
        for n_f in v_f:
            figurate_in_chain_rev.setdefault(n_f, []).append(k_f)
    # is represented by a different number in the set
    for k_r, v_r in figurate_in_chain_rev.items():
        if len(v_r) > 1:
            if all(len(f) == 1 for n_r in v_r if (f := figurate_in_chain[n_r])):
                return False
    return True


if __name__ == '__main__':
    # Run solution tests and exit with success (0) or failure (>0) status code
    raise SystemExit(evaluate_solutions(61))
