#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
  Project Euler Problem 29: Distinct Powers.

  Problem Statement:
    Consider all integer combinations of a^b for 2 \u2264 a \u2264 5 and
    2 \u2264 b \u2264 5:

    2^2=4, 2^3=8, 2^4=16, 2^5=32
    3^2=9, 3^3=27, 3^4=81, 3^5=243
    4^2=16, 4^3=64, 4^4=256, 4^5=1024
    5^2=25, 5^3=125, 5^4=625, 5^5=3125

    If they are then placed in numerical order, with any repeats removed, we get
    the following sequence of 15 distinct terms:
    4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125.

    How many distinct terms are in the sequence generated by a^b for
    2 <= a <= 100 and 2 <= b <= 100?

  Solution Approach:
    To solve this problem, consider using a computational approach that generates
    all possible powers a^b for the given ranges of a and b. Store these values
    in a set or another data structure that automatically removes duplicates.

    Start by iterating through each integer a from 2 to 100 and for each a,
    iterate through each integer b from 2 to 100. Compute a raised to the power
    b and insert the result into the set.

    The size of the set at the end of the iterations will be the number of
    distinct terms.

    This approach leverages the properties of sets for uniqueness and uses
    nested loops for systematic generation. It avoids the need for advanced
    factorization or number theory, making it straightforward and efficient for
    modern computers.

  Test Cases:
    preliminary:
      max_number=5,
      answer=15.

    main:
      max_number=100,
      answer=9183.

    extended:
      max_number=1000,
      answer=977358.


  Answer: 9183
  URL: https://projecteuler.net/problem=29
"""
from __future__ import annotations

from euler.logger import logger
from euler.maths.primes import prime_factorization
from euler.setup import TestCaseCategory, evaluate, register_solution


@register_solution(euler_problem=29, test_case_category=TestCaseCategory.EXTENDED)
def distinct_powers(*, max_number: int) -> int:
    if max_number > 100:
        unique_powers = set()
        for a in range(2, max_number + 1):
            prime_factors = prime_factorization(a)
            for b in range(2, max_number + 1):
                signature = tuple(((prime, power * b) for prime, power in prime_factors))
                unique_powers.add(signature)
        return len(unique_powers)
    else:
        return len({a ** b for a in range(2, max_number + 1) for b in range(2, max_number + 1)})


if __name__ == '__main__':
    logger.setLevel('ERROR')
    raise SystemExit(evaluate(euler_problem=29, time_out_in_seconds=300, mode='evaluate'))
