#!/usr/bin/env bash
# Bash Completions Installer
# ==========================
#
# Installs or removes bash tab-completions for all project development scripts.
#
# Scripts covered:
#   scripts/git/publish.sh            --dry-run, -h/--help, <dir>...
#   scripts/git/status.sh             --summary
#   scripts/git/sync.sh               --dry-run
#   scripts/setup/frontend.sh         install, uninstall, upgrade, status, renew, reload, help
#   scripts/setup/egress.sh           install, uninstall, upgrade, status, reload, help
#   scripts/setup/ddns.sh             install, update, status, uninstall, help
#   scripts/setup/chrome.sh           install, install-script, uninstall, help
#   scripts/setup/dev_env.sh          [--dry-run] [install|uninstall|status] [all|c|lua|primesieve|ruby|python]...
#   scripts/setup/upgrade_service.sh  install, uninstall, --help
#
# Author: Vikas Munshi <vikas.munshi@gmail.com>
# Copyright (c) 2024. All rights reserved.
# Licensed under the MIT License.

set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
PROJECT_ROOT="$(dirname "${SCRIPT_DIR}")"
COMPLETION_FILE="/etc/bash_completion.d/euler-scripts"

usage() {
    echo "Usage: $0 [install|uninstall]"
    echo
    echo "  install    Install bash completions for all project scripts (default)"
    echo "  uninstall  Remove bash completions"
}

check_can_sudo() {
    if ! command -v sudo &>/dev/null; then
        echo "Error: sudo is not installed or not found in PATH" >&2
        return 1
    fi
    if ! sudo -v 2>/dev/null; then
        echo "Error: current user does not have sudo privileges" >&2
        return 1
    fi
}

install() {
    check_can_sudo || return 1

    if [ -f "${COMPLETION_FILE}" ]; then
        echo "Bash completions are already installed at ${COMPLETION_FILE}"
        return 0
    fi

    # Write static completion functions (single-quoted heredoc: no variable expansion needed)
    sudo tee "${COMPLETION_FILE}" <<'STATIC_EOF' > /dev/null
# Bash completions for euler project scripts
# Generated by scripts/bash_completions.sh

_euler_publish_completions() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  if [[ "${cur}" == -* ]]; then
    COMPREPLY=($(compgen -W "--dry-run --help -h" -- "${cur}"))
  else
    COMPREPLY=($(compgen -d -- "${cur}"))
  fi
}

_euler_status_completions() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=($(compgen -W "--summary" -- "${cur}"))
}

_euler_sync_completions() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=($(compgen -W "--dry-run" -- "${cur}"))
}

_euler_chrome_completions() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=($(compgen -W "install install-script uninstall help --help -h" -- "${cur}"))
}

_euler_frontend_completions() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=($(compgen -W "install uninstall upgrade status renew reload help --help -h" -- "${cur}"))
}

_euler_egress_completions() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=($(compgen -W "install uninstall upgrade status reload help --help -h" -- "${cur}"))
}

_euler_ddns_completions() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=($(compgen -W "install update status uninstall help --help -h" -- "${cur}"))
}

_euler_dev_env_completions() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  local commands="install uninstall status"
  local options="--help --dry-run"
  local targets="all c lua primesieve ruby python"

  # Check whether a command word already appears in the line
  local has_command=""
  local word
  for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
    case "${word}" in
      install|uninstall|status) has_command="${word}" ;;
    esac
  done

  if [[ "${cur}" == -* ]]; then
    COMPREPLY=($(compgen -W "${options}" -- "${cur}"))
  elif [[ -n "${has_command}" ]]; then
    COMPREPLY=($(compgen -W "${targets}" -- "${cur}"))
  elif [[ "${prev}" == "--dry-run" ]]; then
    COMPREPLY=($(compgen -W "${commands}" -- "${cur}"))
  else
    COMPREPLY=($(compgen -W "${commands} ${options}" -- "${cur}"))
  fi
}

_euler_upgrade_service_completions() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=($(compgen -W "install uninstall --help -h" -- "${cur}"))
}
STATIC_EOF

    # Append complete registrations with the actual project root embedded
    {
        echo ""
        echo "# Absolute paths (work from any directory)"
        echo "complete -F _euler_publish_completions         '${PROJECT_ROOT}/scripts/git/publish.sh'"
        echo "complete -F _euler_status_completions          '${PROJECT_ROOT}/scripts/git/status.sh'"
        echo "complete -F _euler_sync_completions            '${PROJECT_ROOT}/scripts/git/sync.sh'"
        echo "complete -F _euler_frontend_completions        '${PROJECT_ROOT}/scripts/setup/frontend.sh'"
        echo "complete -F _euler_egress_completions          '${PROJECT_ROOT}/scripts/setup/egress.sh'"
        echo "complete -F _euler_ddns_completions            '${PROJECT_ROOT}/scripts/setup/ddns.sh'"
        echo "complete -F _euler_chrome_completions          '${PROJECT_ROOT}/scripts/setup/chrome.sh'"
        echo "complete -F _euler_dev_env_completions         '${PROJECT_ROOT}/scripts/setup/dev_env.sh'"
        echo "complete -F _euler_upgrade_service_completions '${PROJECT_ROOT}/scripts/setup/upgrade_service.sh'"
        echo ""
        echo "# Relative paths (work when run from the project root)"
        echo "complete -F _euler_publish_completions         'scripts/git/publish.sh'"
        echo "complete -F _euler_status_completions          'scripts/git/status.sh'"
        echo "complete -F _euler_sync_completions            'scripts/git/sync.sh'"
        echo "complete -F _euler_frontend_completions        'scripts/setup/frontend.sh'"
        echo "complete -F _euler_egress_completions          'scripts/setup/egress.sh'"
        echo "complete -F _euler_ddns_completions            'scripts/setup/ddns.sh'"
        echo "complete -F _euler_chrome_completions          'scripts/setup/chrome.sh'"
        echo "complete -F _euler_dev_env_completions         'scripts/setup/dev_env.sh'"
        echo "complete -F _euler_upgrade_service_completions 'scripts/setup/upgrade_service.sh'"
        echo ""
        echo "# ./-prefixed relative paths"
        echo "complete -F _euler_publish_completions         './scripts/git/publish.sh'"
        echo "complete -F _euler_status_completions          './scripts/git/status.sh'"
        echo "complete -F _euler_sync_completions            './scripts/git/sync.sh'"
        echo "complete -F _euler_frontend_completions        './scripts/setup/frontend.sh'"
        echo "complete -F _euler_egress_completions          './scripts/setup/egress.sh'"
        echo "complete -F _euler_ddns_completions            './scripts/setup/ddns.sh'"
        echo "complete -F _euler_chrome_completions          './scripts/setup/chrome.sh'"
        echo "complete -F _euler_dev_env_completions         './scripts/setup/dev_env.sh'"
        echo "complete -F _euler_upgrade_service_completions './scripts/setup/upgrade_service.sh'"
    } | sudo tee -a "${COMPLETION_FILE}" > /dev/null

    echo "Bash completions installed at ${COMPLETION_FILE}"
    echo "Run 'source ${COMPLETION_FILE}' to activate in the current shell"
}

uninstall() {
    check_can_sudo || return 1

    if [ -f "${COMPLETION_FILE}" ]; then
        sudo rm -f "${COMPLETION_FILE}"
        echo "Bash completions removed from ${COMPLETION_FILE}"
    else
        echo "Bash completions are not installed at ${COMPLETION_FILE}"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    ACTION="${1:-install}"
    case "${ACTION}" in
        install)
            install
            ;;
        uninstall)
            uninstall
            ;;
        -h|--help|help)
            usage
            ;;
        *)
            echo "Unknown action: ${ACTION}"
            usage
            exit 1
            ;;
    esac
fi
