#!/usr/bin/env python3.8
# -*- coding: utf-8 -*-
"""
https://projecteuler.net/problem=2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
Answer: 4613732
"""


def sum_even_fibonacci_numbers(max_limit: int) -> int:
    def even_fibonacci_numbers():
        even_fib_a, even_fib_b = 2, 8
        while even_fib_a < max_limit:
            yield even_fib_a
            even_fib_a, even_fib_b = even_fib_b, 4 * even_fib_b + even_fib_a

    return sum(even_fibonacci_numbers())


if __name__ == '__main__':
    from .evaluate import Watchdog

    with Watchdog() as wd:
        result = wd.evaluate_range(sum_even_fibonacci_numbers, answers={10: 10, 100: 44, 4000000: 4613732})
