#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
  Project Euler Problem 45: Triangular Pentagonal And Hexagonal.

  Problem Statement:
    Triangle, pentagonal, and hexagonal numbers are generated by the following
    formulae:

    Triangle numbers: T_n = n(n + 1) / 2
    Sequence: 1, 3, 6, 10, 15, ...

    Pentagonal numbers: P_n = n(3n - 1) / 2
    Sequence: 1, 5, 12, 22, 35, ...

    Hexagonal numbers: H_n = n(2n - 1)
    Sequence: 1, 6, 15, 28, 45, ...

    It can be verified that T_285 = P_165 = H_143 = 40755.

    Find the next triangle number that is also pentagonal and hexagonal.

  Solution Approach:
    To solve this problem, understand the mathematical definitions of triangle,
    pentagonal, and hexagonal numbers. Since each has a specific formula, you can
    use these to generate sequences efficiently. The key is to find a number that
    simultaneously satisfies all three forms.

    One approach is to iterate through hexagonal numbers (since they grow the
    fastest) starting just beyond the known common number 40755. For each hexagonal
    number, check if it is pentagonal and triangular by rearranging their formulas
    and solving the corresponding quadratic equations. The conditions for a number
    being pentagonal or triangular involve checking if certain expressions derived
    from the formulas result in integers.

    Utilize integer arithmetic and properties of these polygonal numbers to avoid
    floating-point inaccuracies. Efficiently checking these conditions can greatly
    reduce computation time. This method avoids generating all triangle and
    pentagonal numbers, focusing only on candidate hexagonal numbers.

  Test Cases:
    main:
      n=285,
      answer=1533776805.


  Answer: 1533776805
  URL: https://projecteuler.net/problem=45
"""
from __future__ import annotations

from euler.logger import logger
from euler.setup import TestCaseCategory, evaluate, register_solution


@register_solution(euler_problem=45, test_case_category=TestCaseCategory.EXTENDED)
def triangular_pentagonal_and_hexagonal(*, n: int) -> int:
    while (n := (n + 1)):
        triangular_number = n * (n + 1) // 2
        if (1 + 24 * triangular_number) ** 0.5 % 6 == 5.0:
            if (1 + 8 * triangular_number) ** 0.5 % 4 == 3.0:
                return triangular_number
    else:
        raise ValueError('No solution found')


if __name__ == '__main__':
    logger.setLevel('ERROR')
    raise SystemExit(evaluate(euler_problem=45, time_out_in_seconds=300, mode='evaluate'))
