#!/usr/bin/env python3.14
# -*- coding: utf-8 -*-
"""Tag/topic glue: the `topics`, `topic` and `update-tags` commands.

The tag system is a double-entry graph. Each problem's ``solution_dir/tags.json``
(Layer 2) lists the tags it carries; the central ``topics/tags.json`` (Layer 1)
lists, per tag, the problems/solutions that carry it (its ``refs`` leg). The two
legs hold the same information at the same granularity — ``pNNNN`` for problem-level
facets (domain, takeaway) and ``pNNNN_sN`` for per-solution techniques.

``update-tags`` is the reconciler that keeps them consistent and feeds the topic
articles under ``topics/``, and it maintains ``topics/articles.json`` — the article
index: one row per *writable* topic (every tag in the vocabulary, plus the curated
pages that are not a tag), carrying the page's title, its declared tags, the number
of problems behind it, and its **status**:

``missing``
    No page on disk yet — the tag is vocabulary only.
``draft``
    A page exists and is still open for writing (the skeleton stubs start here).
``final``
    The page is done: ``claude-blog`` refuses to rewrite it without ``--force``.

The status of record lives in the article itself, as a ``<!-- status: … -->``
comment next to its ``<!-- tags: … -->`` one — the index only reflects it.
``update-tags`` stamps a missing comment as ``draft``; the blogger skill promotes
its page to ``final`` when it finishes writing.
"""
from __future__ import annotations

__all__ = ['tags', 'topics', 'topic', 'update_tags', 'create_topic', 'format_vocabulary',
           'facet_map', 'STATUSES', 'article_status']

import json
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

from solver.config import ExitCodes, config
from solver.core.problems import Problem, problems, solution_dir
from solver.shell import console, register

FACETS = ('domain', 'technique', 'takeaway')
_TAGS_RE = re.compile(r'<!--\s*tags:\s*\[(.*?)\]\s*-->', re.DOTALL)
#: The generated **Problems** section: a visible, machine-owned region update-tags rewrites on
#: every run. Unlike the tags/status comments it renders - it is the list a reader wants, each
#: problem linked with its title and a solved/unsolved marker baked in at reconcile time. The two
#: sentinel comments delimit it so the region can be regenerated in place and the save-gate can
#: refuse edits to it. The article carries problems at ``pNNNN`` granularity (a reader wants the
#: problem, not the solution index); the ``pNNNN_sN`` detail lives in the central legs and the
#: article index.
_GEN_OPEN = 'problems (generated by update-tags)'
_GEN_CLOSE = '/problems'
_GEN_RE = re.compile(r'<!--\s*' + re.escape(_GEN_OPEN) + r'\s*-->.*?<!--\s*'
                     + re.escape(_GEN_CLOSE) + r'\s*-->', re.DOTALL)
#: The article statuses, in writing order. There is no ``missing``: update-tags creates a page for
#: every tag, so a topic always has a file and the only question is whether it has been written.
STATUSES = ('draft', 'final')
_STATUS_RE = re.compile(r'<!--\s*status:\s*(\w+)\s*-->', re.IGNORECASE)


# ── compact JSON (scalar lists inline, object lists multi-line) ─────────────────────────

def dumps_compact(obj: Any, level: int = 0) -> str:
    """json.dumps-alike: a list of scalars renders on one line; dicts and lists of
    objects stay multi-line at 2-space indent. Keeps big ``refs`` legs to one line."""
    pad, pad2 = '  ' * level, '  ' * (level + 1)
    if isinstance(obj, dict):
        if not obj:
            return '{}'
        body = ',\n'.join(f'{pad2}{json.dumps(k)}: {dumps_compact(v, level + 1)}' for k, v in obj.items())
        return f'{{\n{body}\n{pad}}}'
    if isinstance(obj, list):
        if all(not isinstance(x, (dict, list)) for x in obj):
            return json.dumps(obj)
        if not obj:
            return '[]'
        body = ',\n'.join(f'{pad2}{dumps_compact(x, level + 1)}' for x in obj)
        return f'[\n{body}\n{pad}]'
    return json.dumps(obj)


def _write_central(obj: Any) -> None:
    """The central vocabulary: compact (scalar lists inline) so big refs legs stay one line."""
    config.central_tags_file.write_text(dumps_compact(obj) + '\n')


def _write_problem_tags(path: Path, obj: Any) -> None:
    """A per-problem tags.json: plain, human-diffable json.dumps(indent=2)."""
    path.write_text(json.dumps(obj, indent=2) + '\n')


# ── central vocabulary ──────────────────────────────────────────────────────────────────

def _load_central() -> dict[str, Any]:
    data: dict[str, Any] = json.loads(config.central_tags_file.read_text())
    return data


def _facet_of(central: dict[str, Any]) -> dict[str, str]:
    return {tag['slug']: tag['facet'] for tag in central['tags']}


def facet_map() -> dict[str, str]:
    """Every known slug mapped to its facet - the authority a generated tags.json is checked
    against before it is written (see `solver.ai.docs.enforce_facets`)."""
    return _facet_of(_load_central())


def format_vocabulary(facets: tuple[str, ...] = FACETS) -> str:
    """The current tag vocabulary as compact markdown, grouped by facet, for a generation prompt.
    Lists each tag as ``- slug — name`` (takeaways append the summary).

    ``facets`` narrows the listing: a domain-only prompt (an unsolved problem, which has no
    solutions to carry techniques or takeaways) passes ``('domain',)`` so the model is not shown
    - and cannot pick from - vocabulary it has no business assigning.

    When more than one facet is listed, each entry repeats its facet inline (``- slug [technique]
    — name``). Section grouping alone is not enough: a generator recalling a slug loses which
    ``###`` block it came from and files it under the wrong facet, which `update-tags --check`
    then rejects. The marker travels with the slug, so it cannot be lost.
    """
    tags = _load_central()['tags']
    lines: list[str] = []
    mark = len(facets) > 1
    for facet in facets:
        entries = sorted((t for t in tags if t['facet'] == facet), key=lambda t: t['slug'])
        lines.append(f'\n### {facet} ({len(entries)})')
        for t in entries:
            extra = f": {t['summary']}" if facet == 'takeaway' and t.get('summary') else ''
            tag = f" [{facet}]" if mark else ''
            lines.append(f"- {t['slug']}{tag} — {t['name']}{extra}")
    return '\n'.join(lines)


def _ref_key(ref: str) -> tuple[int, int]:
    """Natural sort for pNNNN / pNNNN_sN (problem-level sorts before its solutions)."""
    m = re.fullmatch(r'p(\d+)(?:_s(\d+))?', ref)
    if not m:
        return (0, 0)
    return (int(m.group(1)), int(m.group(2)) if m.group(2) is not None else -1)


# ── per-problem tags.json (Layer 2) ─────────────────────────────────────────────────────

def _problem_tags_path(num: int) -> Path:
    return solution_dir(num) / config.tags_filename


def _load_problem_tags(num: int) -> dict[str, Any] | None:
    path = _problem_tags_path(num)
    return json.loads(path.read_text()) if path.exists() else None


def _solution_indices(num: int) -> list[int]:
    """Solution indices present on disk for a problem (from pNNNN_sK.py/.c)."""
    d = solution_dir(num)
    idx = {int(m.group(1)) for f in d.glob(f'p{num:04d}_s*.py')
           if (m := re.fullmatch(rf'p{num:04d}_s(\d+)\.py', f.name))}
    idx |= {int(m.group(1)) for f in d.glob(f'p{num:04d}_s*.c')
            if (m := re.fullmatch(rf'p{num:04d}_s(\d+)\.c', f.name))}
    return sorted(idx)


def _all_problem_numbers() -> list[int]:
    """Every problem the reconciler must consider - those that have a ``tags.json``.

    This used to key on ``notes.html``, which only a *solved* problem has. Once the unsolved
    problems were tagged too, that made 705 of 1007 files invisible here: their tags built no
    refs, their ``new-tags`` were never promoted (so slugs they used dangled), and ``--check``
    silently skipped them. The file the reconciler reconciles is the one to look for.
    """
    nums: list[int] = []
    for pattern in (f'public/p*/{config.tags_filename}', f'private/p*/p*/{config.tags_filename}'):
        for f in config.solutions_dir.glob(pattern):
            if m := re.search(r'p(\d+)', f.parent.name):
                nums.append(int(m.group(1)))
    return sorted(nums)


# ── topic articles ──────────────────────────────────────────────────────────────────────

def _iter_articles() -> list[Path]:
    return sorted(p for p in config.topics_dir.rglob('*.md'))


def _article_tags(text: str) -> list[str]:
    m = _TAGS_RE.search(text)
    if not m:
        return []
    return [s.strip() for s in m.group(1).split(',') if s.strip()]


def article_status(text: str) -> str:
    """An existing article's status: ``final`` only when it says so, else ``draft``.

    A page on disk is never ``missing`` however its comment reads — the file is the
    fact, the comment only distinguishes finished from still-being-written."""
    m = _STATUS_RE.search(text)
    return 'final' if m and m.group(1).lower() == 'final' else 'draft'


def _stamp_status(text: str) -> str:
    """Give an article that carries no status comment a ``draft`` one, under its tags
    comment (or at the top when it has none). Text that already declares one is left alone."""
    if _STATUS_RE.search(text):
        return text
    marker = '<!-- status: draft -->'
    if m := _TAGS_RE.search(text):
        return f'{text[:m.end()]}\n{marker}{text[m.end():]}'
    return f'{marker}\n{text}'


def _article_title(text: str, fallback: str) -> str:
    """The article's own title — its leading ``# H1`` — falling back to *fallback*."""
    for line in text.splitlines():
        if line.startswith('# '):
            return line[2:].strip()
    return fallback


def _find_article(name: str) -> Path | None:
    name = name.removesuffix('.md')
    for path in _iter_articles():
        rel = path.relative_to(config.topics_dir).with_suffix('')
        if str(rel) == name or path.stem == name:
            return path
    return None


# ══ commands ════════════════════════════════════════════════════════════════════════════

#: Histogram bins for problems-per-tag: (upper bound inclusive, label). Last bin is open-ended.
_BINS: tuple[tuple[int, str], ...] = (
    (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'),
    (9, '6-9'), (19, '10-19'), (49, '20-49'), (10 ** 9, '50+'))


def _problem_count(tag: dict[str, Any]) -> int:
    """Distinct problems a tag maps to (collapse pNNNN_sN solution refs to pNNNN)."""
    return len({r.split('_')[0] for r in tag.get('refs', [])})


@register(requires='reader',
          help_text='Summary (tags per facet) or a problems-per-tag histogram of the vocabulary.')
def tags(details: bool = False) -> int:
    """Report over the central tag vocabulary (`topics/tags.json`).

    `summary` (default) prints the number of tags in each facet; `details` adds, per facet, a
    histogram of how many problems each tag maps to (min / median / max, then binned counts).
    """
    facet_tags = {f: [t for t in _load_central()['tags'] if t['facet'] == f] for f in FACETS}
    total = sum(len(v) for v in facet_tags.values())
    console.print(f'[accent]Tag vocabulary[/accent] — {total} tags')
    for facet in FACETS:
        entries = facet_tags[facet]
        console.print(f'  [muted]{facet:9}[/muted] {len(entries):4d}')
    if not details:
        return ExitCodes.EXIT_OK

    console.print('\n[accent]Problems per tag[/accent]')
    for facet in FACETS:
        entries = facet_tags[facet]
        console.print(f'\n[primary]{facet}[/primary] [muted]({len(entries)} tags)[/muted]')
        if not entries:
            continue
        counts = sorted(_problem_count(t) for t in entries)
        median = counts[len(counts) // 2]
        console.print(f'  [muted]problems/tag: min {counts[0]} · median {median} · max {counts[-1]}[/muted]')
        bins = [0] * len(_BINS)
        for c in counts:
            bins[next(i for i, (hi, _) in enumerate(_BINS) if c <= hi)] += 1
        scale = max(bins) or 1
        for (_, label), n in zip(_BINS, bins):
            bar = '█' * round(n / scale * 32)
            console.print(f'  [muted]{label:>6}[/muted] [accent.dim]{bar}[/accent.dim] {n}')
    return ExitCodes.EXIT_OK


@register(requires='reader', help_text='Show the tags on a problem and the topics that cover them.')
def topics(problem: Problem) -> int:
    """List a problem's tags (grouped by facet) and the topic articles that cover any of them."""
    data = _load_problem_tags(problem.number)
    if data is None:
        console.print(f'[error]error:[/error] no {config.tags_filename} for problem {problem.number} '
                      f'(run [accent]update-tags[/accent])')
        return ExitCodes.EXIT_ERROR
    console.print(f'[accent]Problem {problem.number}[/accent] — {problem.title}')
    own: set[str] = set(data.get('domain', [])) | set(data.get('takeaways', []))
    if data.get('domain'):
        console.print(f'  [muted]domain   [/muted] {", ".join(data["domain"])}')
    for sidx, slugs in sorted(data.get('techniques', {}).items()):
        if slugs:
            own |= set(slugs)
            console.print(f'  [muted]technique[/muted] [accent.dim]{sidx}[/accent.dim] {", ".join(slugs)}')
    if data.get('takeaways'):
        console.print(f'  [muted]takeaway [/muted] {", ".join(data["takeaways"])}')
    covering = [str(p.relative_to(config.topics_dir).with_suffix(''))
                for p in _iter_articles() if own & set(_article_tags(p.read_text()))]
    console.print(f'  [muted]topics   [/muted] {", ".join(covering) if covering else "(none)"}')
    return ExitCodes.EXIT_OK


@register(requires='reader', help_text='Show a topic article\'s tags and the problems/solutions they map to.')
def topic(name: str) -> int:
    """List a topic article's declared tags and, per tag, the problems/solutions on its central leg."""
    path = _find_article(name)
    if path is None:
        console.print(f'[error]error:[/error] no topic article {name!r} under topics/')
        return ExitCodes.EXIT_ERROR
    tags = _article_tags(path.read_text())
    if not tags:
        console.print(f'[warning]{path.name}[/warning] declares no tags (add a <!-- tags: [...] --> comment)')
        return ExitCodes.EXIT_OK
    central = {t['slug']: t for t in _load_central()['tags']}
    console.print(f'[accent]{path.relative_to(config.topics_dir).with_suffix("")}[/accent] — tags: {", ".join(tags)}')
    seen: set[str] = set()
    for slug in tags:
        tag = central.get(slug)
        if tag is None:
            console.print(f'  [error]{slug}[/error] — not in vocabulary')
            continue
        refs = tag.get('refs', [])
        seen.update(refs)
        console.print(f'  [muted]{tag["facet"]:9}[/muted] [accent.dim]{slug}[/accent.dim] '
                      f'({len(refs)}) {", ".join(refs) if refs else "(unmapped)"}')
    problems = sorted({r.split('_')[0] for r in seen}, key=_ref_key)
    console.print(f'  [muted]→ {len(problems)} problem(s):[/muted] {", ".join(problems)}')
    return ExitCodes.EXIT_OK


# ── the reconciler ──────────────────────────────────────────────────────────────────────

def _head_central() -> dict[str, Any] | None:
    """The committed ``topics/tags.json`` at HEAD, for the maintainer-intent diff."""
    try:
        proc = subprocess.run(['git', '-C', str(config.root_dir), 'show', f'HEAD:topics/{config.tags_filename}'],
                              capture_output=True, text=True, timeout=5, check=False)
    except (OSError, subprocess.SubprocessError):
        return None
    return json.loads(proc.stdout) if proc.returncode == 0 and proc.stdout.strip() else None


def _apply_membership(ptags: dict[int, dict[str, Any]], slug: str, facet: str, ref: str, present: bool) -> None:
    """Add or remove a tag from the per-problem file implied by *ref* (pNNNN / pNNNN_sN)."""
    m = re.fullmatch(r'p(\d+)(?:_s(\d+))?', ref)
    if not m:
        return
    num = int(m.group(1))
    data = ptags.setdefault(num, {'domain': [], 'takeaways': [], 'techniques': {}, 'new-tags': []})
    if facet == 'technique':
        idx = f's{m.group(2)}' if m.group(2) is not None else (f's{_solution_indices(num)[0]}'
                                                               if _solution_indices(num) else 's0')
        bucket = data['techniques'].setdefault(idx, [])
    else:
        bucket = data['domain'] if facet == 'domain' else data['takeaways']
    if present and slug not in bucket:
        bucket.append(slug)
    elif not present and slug in bucket:
        bucket.remove(slug)


def _delete_slug_everywhere(ptags: dict[int, dict[str, Any]], slug: str) -> int:
    """Strip *slug* from every per-problem file's facet buckets. Returns how many were removed."""
    removed = 0
    for data in ptags.values():
        for key in ('domain', 'takeaways'):
            if slug in data.get(key, []):
                data[key].remove(slug)
                removed += 1
        for slugs in data.get('techniques', {}).values():
            if slug in slugs:
                slugs.remove(slug)
                removed += 1
    return removed


def _maintainer_diff(current: dict[str, Any], ptags: dict[int, dict[str, Any]]) -> int:
    """Apply maintainer edits to the central vocabulary (vs HEAD) into the per-problem files first,
    so the maintainer wins over solver/contributor on the subsequent reconcile. Two edits: a tag
    deleted from the vocabulary cascades to remove that slug everywhere; a ref added to / removed
    from a surviving tag's `refs` adds / removes that tag on the implied problem's file."""
    head = _head_central()
    if head is None:
        return 0
    facet = _facet_of(current)
    current_slugs = {t['slug'] for t in current['tags']}
    changes = 0
    for tag in head['tags']:  # tags deleted from the vocabulary → cascade-delete
        if tag['slug'] not in current_slugs:
            changes += _delete_slug_everywhere(ptags, tag['slug'])
    head_refs = {t['slug']: set(t.get('refs', [])) for t in head['tags']}
    for tag in current['tags']:
        slug, cur = tag['slug'], set(tag.get('refs', []))
        was = head_refs.get(slug)
        if was is None:
            continue  # brand-new tag in central; its refs will be built from per-problem files
        for ref in cur - was:
            _apply_membership(ptags, slug, facet[slug], ref, present=True)
            changes += 1
        for ref in was - cur:
            _apply_membership(ptags, slug, facet[slug], ref, present=False)
            changes += 1
    return changes


def _promote_new_tags(central: dict[str, Any], ptags: dict[int, dict[str, Any]]) -> tuple[int, list[str]]:
    """Move each per-problem `new-tags` proposal into the central vocabulary (bookmark rule),
    then into the file's proper facet bucket. Returns (count, warnings)."""
    known = {t['slug'] for t in central['tags']}
    known_refs = {t['reference'] for t in central['tags'] if t['reference']}
    warnings: list[str] = []
    added = 0
    for num, data in ptags.items():
        for prop in list(data.get('new-tags', [])):
            slug, facet = prop.get('slug'), prop.get('facet')
            if not slug or facet not in FACETS:
                warnings.append(f'p{num:04d}: malformed new-tag {prop!r}')
                continue
            if slug not in known:
                # Bookmark rule: strip the #anchor for the reference, unless the base URL is
                # already another tag's reference (the anchor is load-bearing identity — keep it).
                ref = prop.get('reference') or ''
                if '#' in ref and ref.split('#', 1)[0] not in known_refs:
                    reference, extra = ref.split('#', 1)[0], [ref]
                elif '#' in ref:
                    reference, extra = ref, []
                else:
                    reference, extra = (ref or None), []
                central['tags'].append({'slug': slug, 'facet': facet, 'name': prop.get('name', slug),
                                        'reference': reference, 'additional-references': extra,
                                        'summary': prop.get('summary', ''), 'refs': []})
                known.add(slug)
                if reference:
                    known_refs.add(reference)
                added += 1
            # file the promoted slug into the correct bucket
            if facet == 'technique':
                for idx in prop.get('applies-to') or [f's{k}' for k in _solution_indices(num)] or ['s0']:
                    data['techniques'].setdefault(idx, [])
                    if slug not in data['techniques'][idx]:
                        data['techniques'][idx].append(slug)
            else:
                bucket = data['domain'] if facet == 'domain' else data['takeaways']
                if slug not in bucket:
                    bucket.append(slug)
        data['new-tags'] = []
    return added, warnings


def _rebuild_refs(central: dict[str, Any], ptags: dict[int, dict[str, Any]]) -> None:
    """Rebuild every tag's central `refs` leg from the per-problem files."""
    refs: dict[str, set[str]] = defaultdict(set)
    for num, data in ptags.items():
        for slug in data.get('domain', []):
            refs[slug].add(f'p{num:04d}')
        for slug in data.get('takeaways', []):
            refs[slug].add(f'p{num:04d}')
        for idx, slugs in data.get('techniques', {}).items():
            for slug in slugs:
                refs[slug].add(f'p{num:04d}_{idx}')
    for tag in central['tags']:
        tag['refs'] = sorted(refs.get(tag['slug'], set()), key=_ref_key)


def _validate(central: dict[str, Any], ptags: dict[int, dict[str, Any]]) -> list[str]:
    """Unknown slugs, facet violations, and unpromoted new-tags across the per-problem files."""
    facet = _facet_of(central)
    problems: list[str] = []
    for num, data in ptags.items():
        tag = f'p{num:04d}'
        for slug in data.get('domain', []):
            if slug not in facet:
                problems.append(f'{tag}: unknown domain tag {slug!r}')
            elif facet[slug] != 'domain':
                problems.append(f'{tag}: {slug!r} is {facet[slug]}, filed under domain')
        for slug in data.get('takeaways', []):
            if slug not in facet:
                problems.append(f'{tag}: unknown takeaway tag {slug!r}')
            elif facet[slug] != 'takeaway':
                problems.append(f'{tag}: {slug!r} is {facet[slug]}, filed under takeaways')
        for idx, slugs in data.get('techniques', {}).items():
            for slug in slugs:
                if slug not in facet:
                    problems.append(f'{tag}: unknown technique tag {slug!r} ({idx})')
                elif facet[slug] != 'technique':
                    problems.append(f'{tag}: {slug!r} is {facet[slug]}, filed under techniques')
        if data.get('new-tags'):
            problems.append(f'{tag}: {len(data["new-tags"])} unpromoted new-tag(s)')
    return problems


def _article_refs(declared: list[str], by_slug: dict[str, Any]) -> list[str]:
    """The union of the declared tags' central ``refs``, at the legs' own granularity.

    Not collapsed to ``pNNNN``: a technique leg names the solution index it applies to, and an
    article about a technique wants that precision. A curated page declaring tags across facets
    therefore carries a mix, which is correct - the two granularities mean different things.
    """
    return sorted({r for slug in declared for r in by_slug.get(slug, {}).get('refs', [])},
                  key=_ref_key)


def _problem_meta() -> tuple[dict[int, str], set[int]]:
    """``(number → title, {solved numbers})`` for the generated Problems lists.

    Solved here means *we have a solution* — the same line the tagging drew (a solved problem
    gets the full prompt, an unsolved one the domain-only prompt), so the marker on an article
    agrees with why the problem is tagged the way it is. Read once per update-tags run.
    """
    titles = {p.number: p.title for p in problems.problems_list}
    solved = {p.number for p in problems.solved_problems}
    return titles, solved


def _problems_block(declared: list[str], by_slug: dict[str, Any],
                    titles: dict[int, str], solved: set[int]) -> str:
    """The visible, machine-owned Problems section for an article: the distinct problems its tags
    cover, sorted by number, each linked with its title and a baked-in solved/unsolved marker."""
    nums = sorted({int(r.split('_')[0][1:]) for slug in declared
                   for r in by_slug.get(slug, {}).get('refs', [])})
    lines = [f'<!-- {_GEN_OPEN} -->', '## Problems', '']
    if nums:
        for n in nums:
            title = titles.get(n, '')
            mark = 'solved' if n in solved else 'unsolved'
            dash = f' — {title}' if title else ''
            lines.append(f'- [{n:04d}](/solutions/{n:04d}/){dash} · {mark}')
    else:
        lines.append('_No problems carry this tag yet._')
    lines += ['', f'<!-- {_GEN_CLOSE} -->']
    return '\n'.join(lines)


def _create_article(path: Path, tag: dict[str, Any]) -> None:
    """Write a skeleton page for a tag that has none, from ``templates/article.md``.

    The Problems block is left empty here — the ``_regen_articles`` pass fills it in the same run,
    so there is one code path that builds it.
    """
    from solver.templates.engine import Templates, get_template
    reference = tag.get('reference') or ''
    body = get_template(Templates.ARTICLE).substitute(
        slug=tag['slug'], title=tag['name'], gen_open=_GEN_OPEN, gen_close=_GEN_CLOSE,
        reference=f'Start from <{reference}>.' if reference else 'No reference on the tag.')
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body)


def _regen_articles(central: dict[str, Any], write: bool) -> list[str]:
    """Create a page for every tag that lacks one, then rewrite each page's Problems section.

    Creation is what removes ``missing`` from the status vocabulary: every tag has a file, so the
    only question a status answers is whether the page has been *written*. Returns issues.
    """
    by_slug = {t['slug']: t for t in central['tags']}
    titles, solved = _problem_meta()
    issues: list[str] = []
    if write:
        for tag in central['tags']:
            path = config.topics_dir / tag['facet'] / f"{tag['slug']}.md"
            if not path.exists():
                _create_article(path, tag)
    for path in _iter_articles():
        text = path.read_text()
        declared = _article_tags(text)
        for slug in declared:
            if slug not in by_slug:
                issues.append(f'{path.name}: declares unknown tag {slug!r}')
        replacement = _problems_block(declared, by_slug, titles, solved)
        new_text = _GEN_RE.sub(lambda m: replacement, text) if _GEN_RE.search(text) else text
        new_text = _stamp_status(new_text)
        if write and new_text != text:
            path.write_text(new_text)
    return issues


def _build_index(central: dict[str, Any]) -> dict[str, Any]:
    """The article index (``topics/articles.json``): one row per page on disk.

    Every tag has a page (``_regen_articles`` creates it), so the index is built from the files
    rather than from the vocabulary — a row exists because a page does. Curated pages that are not
    a tag (``number-theory/primes``) join on the same footing. Each row carries the page's own
    ``refs``, the same list the page's generated comment holds, so a consumer can rank or filter
    without re-deriving it from the vocabulary.
    """
    by_slug = {t['slug']: t for t in central['tags']}
    rows: dict[str, dict[str, Any]] = {}
    for file in _iter_articles():
        text = file.read_text()
        path = file.relative_to(config.topics_dir).with_suffix('').as_posix()
        declared = _article_tags(text)
        rows[path] = {'path': path, 'title': _article_title(text, file.stem),
                      'status': article_status(text), 'tags': declared,
                      'refs': _article_refs(declared, by_slug)}
    return {'articles': [rows[path] for path in sorted(rows)]}


def _write_index(index: dict[str, Any]) -> None:
    """The article index: compact (each row's tag list inline), one row per line."""
    config.topics_index_file.write_text(dumps_compact(index) + '\n')


def _load_index() -> dict[str, Any] | None:
    try:
        data: dict[str, Any] = json.loads(config.topics_index_file.read_text())
        return data
    except (OSError, json.JSONDecodeError):
        return None


@register(requires='maintainer',
          help_text='Reconcile the tag graph: per-problem tags.json <-> central topics/tags.json -> articles.')
def update_tags(check: bool = False) -> int:
    """The glue for the double-entry tag graph.

    Order (maintainer beats solver/contributor): apply maintainer edits to the central
    vocabulary (vs HEAD) into the per-problem files first; promote ``new-tags`` proposals into
    the vocabulary; rebuild every central ``refs`` leg from the per-problem files; regenerate the
    topic articles' problem lists and rewrite the article index ``topics/articles.json`` (one
    row per writable topic: title, tags, problem count and status). A problem with notes but no
    ``tags.json`` is reported, not created here — the ``claude-api tags`` target (or the skill)
    authors it.

    With ``--check`` nothing is written: report unknown slugs, facet violations, unpromoted
    proposals, missing files and a stale article index, and exit non-zero if the graph is
    inconsistent.
    """
    central = _load_central()

    # Load every per-problem file; note which problems have notes but no tags.json.
    ptags: dict[int, dict[str, Any]] = {}
    missing: list[int] = []
    for num in _all_problem_numbers():
        data = _load_problem_tags(num)
        if data is None:
            missing.append(num)
        else:
            data.setdefault('domain', [])
            data.setdefault('takeaways', [])
            data.setdefault('techniques', {})
            data.setdefault('new-tags', [])
            ptags[num] = data

    if check:
        issues = _validate(central, ptags)
        issues += _regen_articles(central, write=False)
        if _load_index() != _build_index(central):
            issues.append(f'{config.topics_index_file.name} is out of date (run update-tags)')
        if missing:
            issues.append(f'{len(missing)} problem(s) have no {config.tags_filename} (run update-tags)')
        for msg in issues:
            console.print(f'  [error]•[/error] {msg}')
        console.print(f'[{"error" if issues else "accent"}]update-tags --check: '
                      f'{len(issues) or "no"} issue(s)[/]')
        return ExitCodes.EXIT_ERROR if issues else ExitCodes.EXIT_OK

    diff_changes = _maintainer_diff(central, ptags)
    promoted, warnings = _promote_new_tags(central, ptags)
    _rebuild_refs(central, ptags)
    art_issues = _regen_articles(central, write=True)
    index = _build_index(central)          # after the stamping above, so statuses are current

    # Re-sort vocabulary (domain, technique, takeaway; by slug) and persist everything.
    order = {'domain': 0, 'technique': 1, 'takeaway': 2}
    central['tags'].sort(key=lambda t: (order.get(t['facet'], 9), t['slug']))
    _write_central(central)
    _write_index(index)
    for num, data in ptags.items():
        _write_problem_tags(_problem_tags_path(num), data)

    if missing:
        warnings.append(f'{len(missing)} problem(s) have no {config.tags_filename} '
                        f'(author with [accent]claude-api tags[/accent] or the skill)')
    for msg in warnings + art_issues:
        console.print(f'  [warning]•[/warning] {msg}')
    written = {status: sum(1 for a in index['articles'] if a['status'] == status) for status in STATUSES}
    console.print(f'[accent]update-tags:[/accent] {len(ptags)} problem file(s), '
                  f'{promoted} tag(s) promoted, {diff_changes} maintainer edit(s) applied')
    console.print('[accent]articles:[/accent] ' + ' · '.join(f'{written[s]} {s}' for s in STATUSES))
    return ExitCodes.EXIT_OK


# ── curated topics ──────────────────────────────────────────────────────────────────────

#: A curated-topic path segment: lowercase words and hyphens, matching the web nested-page route
#: (`solver.web.site.content._NAME_RE`), so a topic that is creatable here is also servable there.
_TOPIC_SEG_RE = re.compile(r'[a-z0-9][a-z0-9-]*')


def _select_tags_interactively(vocab: list[dict[str, Any]]) -> list[str] | None:
    """A line-based search-and-select over the tag vocabulary; the chosen slugs, or None to abort.

    Line-based rather than a full-screen picker on purpose: it works identically in a terminal and
    in the web PTY (both feed `console.input` over stdin), where a curses UI would not. Type a term
    to search, a result's number to toggle it, ``sel`` to review, ``done`` to finish, ``quit`` to
    abort.
    """
    selected: list[str] = []
    results: list[str] = []
    console.print('[muted]search a term · number toggles it · [accent]sel[/accent] review · '
                  '[accent]done[/accent] · [accent]quit[/accent][/muted]')
    while True:
        line = console.input('[accent]tag>[/accent] ').strip()
        if not line:
            continue
        if line == 'quit':
            return None
        if line == 'done':
            if not selected:
                console.print('[warning]pick at least one tag, or [accent]quit[/accent][/warning]')
                continue
            return selected
        if line == 'sel':
            console.print('[accent]selected:[/accent] ' + (', '.join(selected) or '[muted]none[/muted]'))
            continue
        if line.isdigit():
            i = int(line)
            if not 0 <= i < len(results):
                console.print('[warning]no result with that number — search first[/warning]')
                continue
            slug = results[i]
            if slug in selected:
                selected.remove(slug)
                console.print(f'  [muted]removed[/muted] {slug}')
            else:
                selected.append(slug)
                console.print(f'  [accent]added[/accent] {slug}')
            continue
        term = line.lower()
        matches = [t for t in vocab if term in t['slug'] or term in t['name'].lower()]
        results = [t['slug'] for t in matches[:20]]
        if not matches:
            console.print('[muted]no tags match[/muted]')
            continue
        for i, t in enumerate(matches[:20]):
            mark = '[accent]✓[/accent]' if t['slug'] in selected else ' '
            console.print(f'  [muted]{i:2}[/muted] {mark} {t["slug"]} '
                          f'[muted]{t["facet"]} — {t["name"]}[/muted]')
        if len(matches) > 20:
            console.print(f'  [muted]… {len(matches) - 20} more — refine the search[/muted]')


@register(requires='maintainer',
          help_text='Create a curated topic page, choosing its tags interactively.')
def create_topic(path: str, *tags: str) -> int:
    """Seed a curated cross-cutting topic (e.g. ``number-theory/primes``) — a page that gathers
    several tags under one idea, unlike a tag's own auto-generated page.

    *path* is the ``folder/leaf`` the page lives at under ``topics/``. Give the tag slugs as
    arguments to create non-interactively; give none and, in an interactive shell, pick them with
    a search-and-select prompt. Every slug must exist in the vocabulary. The page is seeded from
    the same template a tag page uses (its title is the leaf, title-cased — edit it when you
    write the page) and reconciled straight away, so it appears in the draft index and its
    Problems section is filled. Write it with ``claude-blog <path>``.

    Args:
        path: The ``folder/leaf`` location under ``topics/`` (lowercase words and hyphens).
        tags: The tag slugs the page covers; omit to choose interactively.
    """
    segments = path.removesuffix('.md').strip('/').split('/')
    if len(segments) < 2 or not all(_TOPIC_SEG_RE.fullmatch(s) for s in segments):
        console.print('[error]error:[/error] path must be [accent]folder/leaf[/accent] '
                      '(lowercase words and hyphens), e.g. [accent]number-theory/primes[/accent]')
        return ExitCodes.EXIT_ERROR
    target = config.topics_dir.joinpath(*segments).with_suffix('.md')
    if target.exists():
        console.print(f'[error]error:[/error] {target.relative_to(config.topics_dir)} already exists')
        return ExitCodes.EXIT_ERROR

    vocab = _load_central()['tags']
    known = {t['slug'] for t in vocab}
    if tags:
        chosen = list(dict.fromkeys(tags))                 # de-dupe, keep order
        unknown = [t for t in chosen if t not in known]
        if unknown:
            console.print(f'[error]error:[/error] not in the vocabulary: {", ".join(unknown)}')
            return ExitCodes.EXIT_ERROR
    else:
        if not sys.stdin.isatty():
            console.print('[error]error:[/error] no tags given and not an interactive shell — '
                          'pass the slugs as arguments (e.g. [accent]create-topic '
                          f'{path} prime-number sieve-of-eratosthenes[/accent])')
            return ExitCodes.EXIT_ERROR
        console.print(f'[primary]New topic[/primary] [accent]{"/".join(segments)}[/accent] — '
                      'choose the tags it covers.')
        picked = _select_tags_interactively(vocab)
        if picked is None:
            console.print('[muted]aborted — nothing written[/muted]')
            return ExitCodes.EXIT_OK
        chosen = picked

    title = segments[-1].replace('-', ' ').title()
    from solver.templates.engine import Templates, get_template
    body = get_template(Templates.ARTICLE).substitute(
        slug=', '.join(chosen), title=title, gen_open=_GEN_OPEN, gen_close=_GEN_CLOSE,
        reference='Curated topic — draw the through-line across the tags below yourself.')
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body)
    console.print(f'[accent]created[/accent] {target.relative_to(config.topics_dir)} '
                  f'covering {len(chosen)} tag(s): {", ".join(chosen)}')
    rc = update_tags()                                     # index it and fill its Problems section
    console.print(f'[muted]write it with [accent]claude-blog {"/".join(segments)}[/accent][/muted]')
    return rc
