#!/usr/bin/env python3.14
# -*- coding: utf-8 -*-
"""Migrated from
    euler_solver/solutions/solutions_0001_0100/solution_0012/p0012.py

Project Euler Problem 12: Highly Divisible Triangular Number.

Problem Statement:
    The sequence of triangle numbers is generated by adding the natural numbers.
    So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
    ten terms would be:
    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    Let us list the factors of the first seven triangle numbers:
    1: 1
    3: 1, 3
    6: 1, 2, 3, 6
    10: 1, 2, 5, 10
    15: 1, 3, 5, 15
    21: 1, 3, 7, 21
    28: 1, 2, 4, 7, 14, 28

    We can see that 28 is the first triangle number to have over five divisors.

    What is the value of the first triangle number to have over five hundred divisors?

Solution Approach:
    Use number theory and prime factorization to efficiently count divisors.
    Recognize that the nth triangle number is n*(n+1)/2. Factor n and n+1 separately,
    combine divisor counts, and check for the first exceeding 500 divisors. Use
    efficient trial division or a sieve for factoring. Aim for O(n log n) or better.

Answer: 76576500
URL: https://projecteuler.net/problem=12"""
from __future__ import annotations


def prime_factorization(n: int) -> tuple[tuple[int, int], ...]:
    if n <= 1:
        return ()
    factors = []
    d = 2
    while d * d <= n:
        if n % d == 0:
            exp = 0
            while n % d == 0:
                n //= d
                exp += 1
            factors.append((d, exp))
        d += 1
    if n > 1:
        factors.append((n, 1))
    return tuple(factors)


def num_factors(n: int) -> int:
    if n == 0:
        return 0
    result = 1
    for _, exp in prime_factorization(n):
        result *= exp + 1
    return result


def solve(*, num_divisors: int) -> int:
    i, triangle_number = (1, 1)
    while num_factors(triangle_number) < num_divisors:
        i += 1
        triangle_number = i * (i + 1) // 2
    return triangle_number


if __name__ == '__main__':
    import sys

    print(solve(num_divisors=int(sys.argv[1])))
