#!/usr/bin/env python3.14
# -*- coding: utf-8 -*-
"""Migrated from
    euler_solver/solutions/solutions_0001_0100/solution_0044/p0044.py :: solve_pentagon_numbers_p0044_s0.

Project Euler Problem 44: Pentagon Numbers.

Problem Statement:
    Pentagonal numbers are generated by the formula, P_n = n(3n-1)/2. The first ten pentagonal
    numbers are:
    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

    It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their difference, 70 - 22 = 48,
    is not pentagonal.

    Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are
    pentagonal and D = |P_k - P_j| is minimised; what is the value of D?

Solution Approach:
    Use number theory and combinatorics to generate pentagonal numbers. Efficiently test if
    a number is pentagonal using a direct inverse formula or a search. Search for pairs (P_j, P_k)
    with both sum and difference pentagonal, minimizing difference D. Use optimized iteration
    and caching of pentagonal sets for quick membership testing.

Answer: 5482660
URL: https://projecteuler.net/problem=44"""
from __future__ import annotations

from math import sqrt


def is_pentagonal_number(n: int) -> bool:
    return ((1 + sqrt(1 + 24 * n)) / 6).is_integer()


def nth_pentagonal_number(n: int) -> int:
    return n * (3 * n - 1) // 2


def solve() -> int:
    i = 0
    while (i := (i + 1)):
        p_i = nth_pentagonal_number(i)
        for j in range(i - 1, 0, -1):
            p_j = nth_pentagonal_number(j)
            if is_pentagonal_number(p_i - p_j) and is_pentagonal_number(p_i + p_j):
                return p_i - p_j
    else:
        raise ValueError('No solution found')


if __name__ == '__main__':
    print(solve())
